// The published facts about the Beyond BIM programme, in one place.
//
// WHY A FILE AND NOT A READ OF THE PAGE
// The page itself (src/ds/pages/DsBeyondBim.jsx) is generated by
// scripts/port-ds-html.mjs from Richard's markup and must never be hand
// edited, so it cannot carry an export. Scraping dates out of its copy would
// break the first time a word moves. These are the same figures the page
// prints, written down where code can read them: cohort dates, the fee, and
// the date registration closes.
//
// Every value here is one the programme page already states publicly. Nothing
// is rounded, nothing is projected. If a figure on the page changes, change it
// here in the same commit or the site will tell a crawler something it no
// longer tells a visitor.

export const BEYOND_BIM = {
  name: "Beyond BIM",
  cohort: "October 2026",

  // The page says a live online cohort, two sessions a week, running 6 October
  // to 7 November 2026, and that the exact days and times are set once the
  // cohort is confirmed. So these are calendar dates with no time of day, which
  // is all anyone can honestly publish yet.
  startDate: "2026-10-06",
  endDate: "2026-11-07",
  registrationClosesOn: "2026-10-05",

  online: true,
  path: "/beyondbim",
  registerPath: "/beyondbim/register",

  // Per participant, as printed in the fee section. One fee: no separate
  // software charge for the duration and no separate certification charge.
  feeNGN: 180000,

  description:
    "A live online cohort that runs one project from model to cashflow: quantity takeoff, a priced bill of quantities, a programme of works, an interim valuation and a cashflow forecast. Ten sessions, two a week, with marked assignments.",
};

export default BEYOND_BIM;
