// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site index.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";

export default function DsFooter() {
  return (
    <>
      <footer className="foot">
        {" "}
        <div className="shell">
          {" "}
          <div className="foot-top">
            {" "}
            <div>
              {" "}
              <img className="logo-l" src="/ds/logo-light.svg" alt="ADLM Studio" />
              {" "}
              <img className="logo-d" src="/ds/logo-dark.svg" alt="ADLM Studio" />
              {" "}
              <p className="small" style={{ maxWidth: "32ch" }}>
                Digital tools and training for modern Quantity Surveyors. Built in Lagos, for African construction.
              </p>
              {" "}
              <div className="foot-social">
                {" "}
                <a href="https://www.linkedin.com/company/adlm-studio" aria-label="LinkedIn">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-in" />
                  </svg>
                </a>
                {" "}
                <a href="https://x.com/ADLMStudio" aria-label="X">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-x" />
                  </svg>
                </a>
                {" "}
                <a href="https://www.youtube.com/@ADLMStudio" aria-label="YouTube">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-yt" />
                  </svg>
                </a>
                {" "}
                <a href="https://www.instagram.com/adlmstudio" aria-label="Instagram">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-ig" />
                  </svg>
                </a>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div>
              <h5>
                Products
              </h5>
              <ul>
                {" "}
                <li>
                  <Link to="/product/revit" data-ds-page="quiv">
                    QUIV
                  </Link>
                </li>
                <li>
                  <Link to="/product/planswift" data-ds-page="heron">
                    HERON
                  </Link>
                </li>
                <li>
                  <Link to="/product/rategen" data-ds-page="rategen">
                    RateGen
                  </Link>
                </li>
                {" "}
                <li>
                  <Link to="/product/mep" data-ds-page="mep">
                    Revit MEP
                  </Link>
                </li>
                <li>
                  <Link to="/product/qs-takeoff" data-ds-page="timepro">
                    Time Pro
                  </Link>
                </li>
                <li>
                  <Link to="/product/civil3d" data-ds-page="civiq">
                    CIVIQ
                  </Link>
                </li>
                {" "}
              </ul>
            </div>
            {" "}
            <div>
              <h5>
                Solutions
              </h5>
              <ul>
                {" "}
                <li>
                  <Link to="/solutions/firms" data-ds-page="solutions-firms">
                    For firms
                  </Link>
                </li>
                <li>
                  <Link to="/solutions/professionals" data-ds-page="solutions-professionals">
                    For individual QS
                  </Link>
                </li>
                {" "}
                <li>
                  <Link to="/solutions/students" data-ds-page="solutions-students">
                    For students
                  </Link>
                </li>
                <li>
                  <Link to="/solutions/institutions" data-ds-page="solutions-institutions">
                    For institutions
                  </Link>
                </li>
                {" "}
                <li>
                  <Link to="/pricing" data-ds-page="pricing">
                    Pricing
                  </Link>
                </li>
                <li>
                  <Link to="/quote" data-ds-page="quote">
                    Build a quotation
                  </Link>
                </li>
              </ul>
            </div>
            {" "}
            <div>
              <h5>
                Learn
              </h5>
              <ul>
                {" "}
                <li>
                  <Link to="/learn#courses" data-ds-page="learn">
                    Courses
                  </Link>
                </li>
                <li>
                  <Link to="/learn#lessons" data-ds-page="learn">
                    Free lessons
                  </Link>
                </li>
                {" "}
                <li>
                  <Link to="/learn#events" data-ds-page="learn">
                    Events &amp; training
                  </Link>
                </li>
                <li>
                  <Link to="/learn#guides" data-ds-page="learn">
                    Guides &amp; docs
                  </Link>
                </li>
                {" "}
                <li>
                  <Link to="/whats-new" data-ds-page="whats-new">
                    What's New
                  </Link>
                </li>
              </ul>
            </div>
            {" "}
            <div>
              <h5>
                Company
              </h5>
              <ul>
                {" "}
                <li>
                  <Link to="/about" data-ds-page="about">
                    About
                  </Link>
                </li>
                <li>
                  <Link to="/testimonials" data-ds-page="customers">
                    Customers
                  </Link>
                </li>
                <li>
                  <Link to="/careers" data-ds-page="careers">
                    Careers
                  </Link>
                </li>
                {" "}
                <li>
                  <Link to="/press" data-ds-page="press">
                    Press
                  </Link>
                </li>
                <li>
                  <Link to="/contact" data-ds-page="contact">
                    Contact
                  </Link>
                </li>
                <li>
                  <Link to="/contact#support" data-ds-page="contact">
                    Support
                  </Link>
                </li>
                {" "}
                <li>
                  <Link to="/privacy" data-ds-page="privacy">
                    Legal
                  </Link>
                </li>
              </ul>
            </div>
            {" "}
          </div>
          {" "}
          <div className="foot-bot">
            {" "}
            <span>
              © 2026 ADLM Studio. All rights reserved.
            </span>
            {" "}
            <span>
              Lagos, Nigeria · Mon–Fri 9am–6pm WAT · admin@adlmstudio.net · +234 810 650 3524
            </span>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </footer>
    </>
  );
}
