// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site index.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";

export default function DsPromo() {
  return (
    <>
      <section className="promo" id="promo" hidden={true}>
        {" "}
        <div className="shell">
          {" "}
          <span className="host">
            Latest from ADLM
          </span>
          {" "}
          <div className="promo-fr">
            {" "}
            <div className="promo-track">
            </div>
            {" "}
            <div className="promo-dots">
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
