// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/admin-login.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";

export default function DsAdminLogin() {
  return (
    <>
      <div className="adm-gate">
        {" "}
        <div className="adm-gate-art" aria-hidden="true">
        </div>
        {" "}
        <form className="adm-gate-card" id="adm-login" noValidate={true}>
          {" "}
          <Link className="adm-gate-mark" to="/" aria-label="ADLM Studio">
            {" "}
            <img className="logo-l" src="/ds/logo-light.svg" alt="ADLM Studio" />
            {" "}
            <img className="logo-d" src="/ds/logo-dark.svg" alt="ADLM Studio" />
            {" "}
            <span className="tag">
              Admin
            </span>
            {" "}
          </Link>
          {" "}
          <h1>
            Sign in to admin
          </h1>
          {" "}
          <p className="adm-gate-sub">
            Not the account you use as a customer. Admin rights are granted by ADLM, and two people hold them.
          </p>
          {" "}
          <label>
            {" "}Work email{" "}
            <input type="email" id="adm-email" name="email" autoComplete="username" placeholder="you@adlmstudio.net" required={true} />
            {" "}
          </label>
          {" "}
          <label>
            {" "}Password{" "}
            <span className="adm-gate-pw">
              {" "}
              <input type="password" id="adm-pw" name="pw" autoComplete="current-password" required={true} />
              {" "}
              <button type="button" className="adm-gate-eye" data-adm-eye="" aria-label="Show password">
                Show
              </button>
              {" "}
            </span>
            {" "}
          </label>
          {" "}
          <p className="adm-gate-err" id="adm-err" role="alert" hidden={true}>
          </p>
          {" "}
          <button className="ds-btn btn-p" type="submit" id="adm-go">
            Sign in
          </button>
          {" "}
          <p className="adm-gate-foot">
            Everything done from here is written against your name, who did it, to what, and what it looked like before. Viewing a customer account as they see it is a separate action, and it is announced on their timeline.
          </p>
          {" "}
        </form>
        {" "}
      </div>
    </>
  );
}
