// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/beyondbim.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";
import DsPromoLive from "../DsPromoLive.jsx";

export default function DsBeyondBim() {
  const DsPromoSlot = <DsPromoLive />;
  return (
    <>
      {/* bb-icons */}
      {" "}
      <svg width="0" height="0" aria-hidden="true" focusable="false" style={{ position: "absolute" }}>
        {" "}
        <defs>
          {" "}
          <symbol id="bb-i-calendar" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M16 2V6M8 2V6" />
            <path d="M13 4H11C7.22876 4 5.34315 4 4.17157 5.17157C3 6.34315 3 8.22876 3 12V14C3 17.7712 3 19.6569 4.17157 20.8284C5.34315 22 7.22876 22 11 22H13C16.7712 22 18.6569 22 19.8284 20.8284C21 19.6569 21 17.7712 21 14V12C21 8.22876 21 6.34315 19.8284 5.17157C18.6569 4 16.7712 4 13 4Z" />
            <path d="M3 10H21" />
            <path d="M12.1258 14H12.0008M12.1258 18H12.0008M7.625 14H7.5M7.625 18H7.5M16.625 14H16.5M12.2508 14C12.2508 14.1381 12.1389 14.25 12.0008 14.25C11.8628 14.25 11.7508 14.1381 11.7508 14C11.7508 13.8619 11.8628 13.75 12.0008 13.75C12.1389 13.75 12.2508 13.8619 12.2508 14ZM12.2508 18C12.2508 18.1381 12.1389 18.25 12.0008 18.25C11.8628 18.25 11.7508 18.1381 11.7508 18C11.7508 17.8619 11.8628 17.75 12.0008 17.75C12.1389 17.75 12.2508 17.8619 12.2508 18ZM7.75 14C7.75 14.1381 7.63807 14.25 7.5 14.25C7.36193 14.25 7.25 14.1381 7.25 14C7.25 13.8619 7.36193 13.75 7.5 13.75C7.63807 13.75 7.75 13.8619 7.75 14ZM7.75 18C7.75 18.1381 7.63807 18.25 7.5 18.25C7.36193 18.25 7.25 18.1381 7.25 18C7.25 17.8619 7.36193 17.75 7.5 17.75C7.63807 17.75 7.75 17.8619 7.75 18ZM16.75 14C16.75 14.1381 16.6381 14.25 16.5 14.25C16.3619 14.25 16.25 14.1381 16.25 14C16.25 13.8619 16.3619 13.75 16.5 13.75C16.6381 13.75 16.75 13.8619 16.75 14Z" />
          </symbol>
          {" "}
          <symbol id="bb-i-weeks" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M8.64298 3.14559L6.93816 3.93362C4.31272 5.14719 3 5.75397 3 6.75C3 7.74603 4.31272 8.35281 6.93817 9.56638L8.64298 10.3544C10.2952 11.1181 11.1214 11.5 12 11.5C12.8786 11.5 13.7048 11.1181 15.357 10.3544L17.0618 9.56638C19.6873 8.35281 21 7.74603 21 6.75C21 5.75397 19.6873 5.14719 17.0618 3.93362L15.357 3.14559C13.7048 2.38186 12.8786 2 12 2C11.1214 2 10.2952 2.38186 8.64298 3.14559Z" />
            <path d="M20.788 11.0972C20.9293 11.2959 21 11.5031 21 11.7309C21 12.7127 19.6873 13.3109 17.0618 14.5072L15.357 15.284C13.7048 16.0368 12.8786 16.4133 12 16.4133C11.1214 16.4133 10.2952 16.0368 8.64298 15.284L6.93817 14.5072C4.31272 13.3109 3 12.7127 3 11.7309C3 11.5031 3.07067 11.2959 3.212 11.0972" />
            <path d="M20.3767 16.2661C20.7922 16.5971 21 16.927 21 17.3176C21 18.2995 19.6873 18.8976 17.0618 20.0939L15.357 20.8707C13.7048 21.6236 12.8786 22 12 22C11.1214 22 10.2952 21.6236 8.64298 20.8707L6.93817 20.0939C4.31272 18.8976 3 18.2995 3 17.3176C3 16.927 3.20778 16.5971 3.62334 16.2661" />
          </symbol>
          {" "}
          <symbol id="bb-i-video" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M14 2H10C6.72077 2 5.08116 2 3.91891 2.81382C3.48891 3.1149 3.1149 3.48891 2.81382 3.91891C2 5.08116 2 6.72077 2 10C2 13.2792 2 14.9188 2.81382 16.0811C3.1149 16.5111 3.48891 16.8851 3.91891 17.1862C5.08116 18 6.72077 18 10 18H14C17.2792 18 18.9188 18 20.0811 17.1862C20.5111 16.8851 20.8851 16.5111 21.1862 16.0811C22 14.9188 22 13.2792 22 10C22 6.72077 22 5.08116 21.1862 3.91891C20.8851 3.48891 20.5111 3.1149 20.0811 2.81382C18.9188 2 17.2792 2 14 2Z" />
            <path d="M14.5 22L14.1845 21.5811C13.4733 20.6369 13.2969 19.1944 13.7468 18M9.5 22L9.8155 21.5811C10.5267 20.6369 10.7031 19.1944 10.2532 18" />
            <path d="M7 22H17" />
            <path d="M8 14C9.83846 11.4046 14.1188 11.263 16 14M14 8C14 9.10457 13.1046 10 12 10C10.8954 10 10 9.10457 10 8C10 6.89543 10.8954 6 12 6C13.1046 6 14 6.89543 14 8Z" />
          </symbol>
          {" "}
          <symbol id="bb-i-money" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M20.9427 16.8354C20.2864 12.8866 18.2432 9.94613 16.467 8.219C15.9501 7.71642 15.6917 7.46513 15.1208 7.23257C14.5499 7 14.0592 7 13.0778 7H10.9222C9.94081 7 9.4501 7 8.87922 7.23257C8.30834 7.46513 8.04991 7.71642 7.53304 8.219C5.75682 9.94613 3.71361 12.8866 3.05727 16.8354C2.56893 19.7734 5.27927 22 8.30832 22H15.6917C18.7207 22 21.4311 19.7734 20.9427 16.8354Z" />
            <path d="M7.25662 4.44287C7.05031 4.14258 6.75128 3.73499 7.36899 3.64205C8.00392 3.54651 8.66321 3.98114 9.30855 3.97221C9.89237 3.96413 10.1898 3.70519 10.5089 3.33548C10.8449 2.94617 11.3652 2 12 2C12.6348 2 13.1551 2.94617 13.4911 3.33548C13.8102 3.70519 14.1076 3.96413 14.6914 3.97221C15.3368 3.98114 15.9961 3.54651 16.631 3.64205C17.2487 3.73499 16.9497 4.14258 16.7434 4.44287L15.8105 5.80064C15.4115 6.38146 15.212 6.67187 14.7944 6.83594C14.3769 7 13.8373 7 12.7582 7H11.2418C10.1627 7 9.6231 7 9.20556 6.83594C8.78802 6.67187 8.5885 6.38146 8.18945 5.80064L7.25662 4.44287Z" />
          </symbol>
          {" "}
          <symbol id="bb-i-clock" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <circle cx="12" cy="12" r="10" />
            <path d="M12 8V12L14 14" />
          </symbol>
          {" "}
          <symbol id="bb-i-cube" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M2.79289 21.2071C3.08579 21.5 3.55719 21.5 4.5 21.5H14.5C15.4428 21.5 15.9142 21.5 16.2071 21.2071M2.79289 21.2071C2.5 20.9142 2.5 20.4428 2.5 19.5V9.5C2.5 8.55719 2.5 8.08579 2.79289 7.79289M2.79289 21.2071L8.79289 15.2071M16.2071 21.2071C16.5 20.9142 16.5 20.4428 16.5 19.5V9.5C16.5 8.55719 16.5 8.08579 16.2071 7.79289M16.2071 21.2071L21.2071 16.2071C21.5 15.9142 21.5 15.4428 21.5 14.5V4.5C21.5 3.55719 21.5 3.08579 21.2071 2.79289M16.2071 7.79289C15.9142 7.5 15.4428 7.5 14.5 7.5H4.5C3.55719 7.5 3.08579 7.5 2.79289 7.79289M16.2071 7.79289L21.2071 2.79289M2.79289 7.79289L7.79289 2.79289C8.08579 2.5 8.55719 2.5 9.5 2.5H19.5C20.4428 2.5 20.9142 2.5 21.2071 2.79289M8.79289 15.2071C9.08579 15.5 9.55719 15.5 10.5 15.5H14M8.79289 15.2071C8.5 14.9142 8.5 14.4428 8.5 13.5V10.5" />
          </symbol>
          {" "}
          <symbol id="bb-i-doc" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M8 7L16 7" />
            <path d="M8 11L12 11" />
            <path d="M13 21.5V21C13 18.1716 13 16.7574 13.8787 15.8787C14.7574 15 16.1716 15 19 15H19.5M20 13.3431V10C20 6.22876 20 4.34315 18.8284 3.17157C17.6569 2 15.7712 2 12 2C8.22877 2 6.34315 2 5.17157 3.17157C4 4.34314 4 6.22876 4 10L4 14.5442C4 17.7892 4 19.4117 4.88607 20.5107C5.06508 20.7327 5.26731 20.9349 5.48933 21.1139C6.58831 22 8.21082 22 11.4558 22C12.1614 22 12.5141 22 12.8372 21.886C12.9044 21.8623 12.9702 21.835 13.0345 21.8043C13.3436 21.6564 13.593 21.407 14.0919 20.9081L18.8284 16.1716C19.4065 15.5935 19.6955 15.3045 19.8478 14.9369C20 14.5694 20 14.1606 20 13.3431Z" />
          </symbol>
          {" "}
          <symbol id="bb-i-check" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M5 14L8.5 17.5L19 6.5" />
          </symbol>
          {" "}
          <symbol id="bb-i-user" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M18.4995 20.5C18.2663 17.5685 15.8417 15.2477 12.808 15.0521L11.9995 15C11.7107 15.0076 11.4416 15.0178 11.1877 15.0298C8.18075 15.1723 5.7304 17.5974 5.49951 20.5" />
            <path d="M15.2495 9.25C15.2495 11.0449 13.7944 12.5 11.9995 12.5C10.2046 12.5 8.74952 11.0449 8.74952 9.25C8.74952 7.45507 10.2046 6 11.9995 6C13.7944 6 15.2495 7.45507 15.2495 9.25Z" />
            <path d="M5.50249 8.5C5.17908 7.99485 4.99158 7.39432 4.99158 6.75C4.99158 4.95507 6.44665 3.5 8.24157 3.5C8.68752 3.5 9.1125 3.58982 9.49939 3.75235" />
            <path d="M18.4963 8.5C18.8197 7.99485 19.0072 7.39432 19.0072 6.75C19.0072 4.95507 17.5521 3.5 15.7572 3.5C15.3113 3.5 14.8863 3.58982 14.4994 3.75235" />
            <path d="M22.0007 17.9996C21.8208 15.7374 19.9995 13.5 17.9995 13" />
            <path d="M1.99927 17.9996C2.17923 15.7374 4.00049 13.5 6.00049 13" />
          </symbol>
          {" "}
          <symbol id="bb-i-screen" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M14 21H16M14 21C13.1716 21 12.5 20.3284 12.5 19.5V17L12 17M14 21H10M10 21H8M10 21C10.8284 21 11.5 20.3284 11.5 19.5V17L12 17M12 17V21" />
            <path d="M16 3H8C5.17157 3 3.75736 3 2.87868 3.87868C2 4.75736 2 6.17157 2 9V11C2 13.8284 2 15.2426 2.87868 16.1213C3.75736 17 5.17157 17 8 17H16C18.8284 17 20.2426 17 21.1213 16.1213C22 15.2426 22 13.8284 22 11V9C22 6.17157 22 4.75736 21.1213 3.87868C20.2426 3 18.8284 3 16 3Z" />
          </symbol>
          {" "}
          <symbol id="bb-i-cloud" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M17.4776 8.00005C17.485 8.00002 17.4925 8 17.5 8C19.9853 8 22 10.0147 22 12.5C22 14.9853 19.9853 17 17.5 17H7C4.23858 17 2 14.7614 2 12C2 9.40034 3.98398 7.26407 6.52042 7.0227M17.4776 8.00005C17.4924 7.83536 17.5 7.66856 17.5 7.5C17.5 4.46243 15.0376 2 12 2C9.12324 2 6.76233 4.20862 6.52042 7.0227M17.4776 8.00005C17.3753 9.1345 16.9286 10.1696 16.2428 11M6.52042 7.0227C6.67826 7.00768 6.83823 7 7 7C8.12582 7 9.16474 7.37209 10.0005 8" />
            <path d="M14 20.75V20.5C14 19.9477 13.5523 19.5 13 19.5H12M14 20.75V21C14 21.5523 13.5523 22 13 22H11C10.4477 22 10 21.5523 10 21V20.75M14 20.75H19M10 20.75V20.5C10 19.9477 10.4477 19.5 11 19.5H12M10 20.75H5M12 19.5V17" />
          </symbol>
          {" "}
          <symbol id="bb-i-down" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M16.9504 12.1817C17.1981 12.814 16.5076 13.5726 15.1267 15.0899C13.6702 16.6902 12.9201 17.4904 12 17.5C11.0799 17.4904 10.3298 16.6902 8.87331 15.0899C7.49239 13.5726 6.80193 12.814 7.04964 12.1817C7.05868 12.1586 7.06851 12.1359 7.0791 12.1135C7.34928 11.542 8.24477 11.5029 10 11.5002V4.99998C10 4.53501 10 4.30253 10.0511 4.11179C10.1898 3.59414 10.5941 3.1898 11.1118 3.05111C11.3025 3 11.535 3 12 3C12.4649 3 12.6974 3 12.8882 3.05111C13.4058 3.1898 13.8102 3.59414 13.9489 4.11179C14 4.30253 14 4.53501 14 4.99998V11.5002C15.7552 11.5029 16.6507 11.542 16.9209 12.1135C16.9315 12.1359 16.9413 12.1586 16.9504 12.1817Z" />
            <path d="M5.00006 21H19.0001" />
          </symbol>
          {" "}
          <symbol id="bb-i-arrow" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M9.00005 6C9.00005 6 15 10.4189 15 12C15 13.5812 9 18 9 18" />
          </symbol>
          {" "}
          <symbol id="bb-i-cert" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M11.5 22C7.49306 22 5.48959 22 4.2448 20.5355C3 19.0711 3 16.714 3 12C3 7.28596 3 4.92893 4.2448 3.46447C5.48959 2 7.49306 2 11.5 2C15.5069 2 17.5104 2 18.7552 3.46447C19.7572 4.64332 19.9527 6.40054 19.9908 9.5" />
            <path d="M8 8H15M8 13H11" />
            <path d="M19.6092 18.1054C20.4521 17.4918 21 16.4974 21 15.375C21 13.511 19.489 12 17.625 12H17.375C15.511 12 14 13.511 14 15.375C14 16.4974 14.5479 17.4918 15.3908 18.1054M19.6092 18.1054C19.0523 18.5108 18.3666 18.75 17.625 18.75H17.375C16.6334 18.75 15.9477 18.5108 15.3908 18.1054M19.6092 18.1054L20.192 19.9404C20.4143 20.6403 20.5255 20.9903 20.4951 21.2082C20.4318 21.6617 20.0619 21.9984 19.6252 22C19.4154 22.0008 19.101 21.8358 18.4723 21.5059C18.2027 21.3644 18.0679 21.2936 17.93 21.252C17.649 21.1673 17.351 21.1673 17.07 21.252C16.9321 21.2936 16.7973 21.3644 16.5277 21.5059C15.899 21.8358 15.5846 22.0008 15.3748 22C14.9381 21.9984 14.5682 21.6617 14.5049 21.2082C14.4745 20.9903 14.5857 20.6403 14.808 19.9404L15.3908 18.1054" />
          </symbol>
          {" "}
        </defs>
      </svg>
      {" "}
      {" "}
      {/* light-art keeps site.js from flipping the nav to its over-dark colours: this
     hero's copy sits on the artwork's own empty ground, which is light in the
     light theme and dark in the dark one. */}
      {" "}
      <header className="phero bb-hero light-art" id="top">
        {" "}
        <div className="phero-bg bb-art">
          {" "}
          <img className="art-l" src="/ds/bb-hero-light.jpg" alt="" fetchpriority="high" width="1800" height="1172" />
          {" "}
          <img className="art-d" src="/ds/bb-hero-dark.jpg" alt="" fetchpriority="high" width="1800" height="1364" />
          {" "}
        </div>
        {" "}
        <div className="phero-in">
          {" "}
          <div className="bb-with">
            {" "}
            <img className="bb-logo art-l" src="/ds/logo-light.svg" alt="ADLM Studio" />
            {" "}
            <img className="bb-logo art-d" src="/ds/logo-dark.svg" alt="ADLM Studio" />
            {" "}
            <i className="bb-with-x" aria-hidden="true">
            </i>
            {" "}
            <img className="bb-niqs art-l" src="/ds/niqs-light.svg" alt="Nigerian Institute of Quantity Surveyors" />
            {" "}
            <img className="bb-niqs art-d" src="/ds/niqs-dark.svg" alt="Nigerian Institute of Quantity Surveyors" />
            {" "}
          </div>
          {" "}
          <span className="host">
            Live cohort · Online · 6 Oct – 7 Nov 2026
          </span>
          {" "}
          <h1 className="bb-h1">
            {" "}
            <img src="/ds/bb-wordmark.png" alt="Beyond BIM" width="1200" height="239" />
            {" "}
            <span className="ds-sub">
              The modern roles of a Quantity Surveyor
            </span>
            {" "}
          </h1>
          {" "}
          <p className="ds-lede">
            One project, from the 3D model to cashflow. Five weeks, ten live sessions, run end to end on the Burj Khalifa Revit model: with the tools a modern QS is expected to use.
          </p>
          {" "}
          <div className="bb-facts">
            {" "}
            <div>
              {" "}
              <span className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#bb-i-calendar" />
                </svg>
              </span>
              {" "}
              <b>
                6 Oct – 7 Nov
              </b>
              <span>
                2026
              </span>
              {" "}
            </div>
            {" "}
            <div>
              {" "}
              <span className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#bb-i-weeks" />
                </svg>
              </span>
              {" "}
              <b>
                5 weeks
              </b>
              <span>
                10 sessions
              </span>
              {" "}
            </div>
            {" "}
            <div>
              {" "}
              <span className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#bb-i-video" />
                </svg>
              </span>
              {" "}
              <b>
                Live online
              </b>
              <span>
                Google Meet
              </span>
              {" "}
            </div>
            {" "}
            <div>
              {" "}
              <span className="ico ico-a">
                <svg viewBox="0 0 24 24">
                  <use href="#bb-i-money" />
                </svg>
              </span>
              {" "}
              <b>
                ₦180,000
              </b>
              <span>
                Per person
              </span>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
          <div className="bb-count" id="bb-count" hidden={true}>
            {" "}
            <div className="u">
              <b data-c="d">
                ,{" "}
              </b>
              <span>
                Days
              </span>
            </div>
            {" "}
            <div className="u">
              <b data-c="h">
                ,{" "}
              </b>
              <span>
                Hrs
              </span>
            </div>
            {" "}
            <div className="u">
              <b data-c="m">
                ,{" "}
              </b>
              <span>
                Min
              </span>
            </div>
            {" "}
            <div className="u">
              <b data-c="s">
                ,{" "}
              </b>
              <span>
                Sec
              </span>
            </div>
            {" "}
            <span className="lab">
              until the first session
            </span>
            {" "}
          </div>
          {" "}
          <div className="hero-cta">
            {" "}
            <Link to="/beyondbim/register" data-ds-page="beyondbim-register" className="ds-btn btn-p">
              Register for the cohort
            </Link>
            {" "}
            <a href="#sessions" className="ds-btn btn-o">
              See the ten sessions
            </a>
            {" "}
          </div>
          {" "}
          <p className="phero-note">
            <span className="pulse">
            </span>
            Registration open · session days and times confirmed to registered participants
          </p>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <div className="bb-rail" id="bb-rail">
        {" "}
        <div className="bb-rail-in">
          {" "}
          <nav aria-label="On this page">
            {" "}
            <a href="#overview">
              Overview
            </a>
            {" "}
            <a href="#programme">
              Programme
            </a>
            {" "}
            <a href="#sessions">
              Sessions
            </a>
            {" "}
            <a href="#tools">
              Tools
            </a>
            {" "}
            <a href="#outcomes">
              Outcomes
            </a>
            {" "}
            <a href="#fee">
              Fee
            </a>
            {" "}
            <a href="#faq">
              FAQ
            </a>
            {" "}
          </nav>
          {" "}
          <Link to="/beyondbim/register" data-ds-page="beyondbim-register" className="ds-btn btn-p ds-btn-sm">
            Register
          </Link>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
      {/* ============================================================ overview */}
      {" "}
      <section className="sec" id="overview">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              What this is
            </span>
            {" "}
            <h2>
              Not a tour of the software.{" "}
              <span className="tone">
                One project, run properly.
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              Most BIM training stops at the model. This one keeps going: through takeoff, into a priced bill, out to a programme, a valuation, and a cashflow forecast you can defend in a meeting. You leave with a complete workflow you have run yourself.
            </p>
            {" "}
          </div>
          {" "}
          <div className="statframe rise">
            {" "}
            <div className="stat">
              {" "}
              <span className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#bb-i-clock" />
                </svg>
              </span>
              {" "}
              <b>
                20
              </b>
              <span>
                Live contact hours
              </span>
              {" "}
            </div>
            {" "}
            <div className="stat">
              {" "}
              <span className="ico ico-a">
                <svg viewBox="0 0 24 24">
                  <use href="#bb-i-cube" />
                </svg>
              </span>
              {" "}
              <b>
                2
              </b>
              <span>
                Live project models
              </span>
              {" "}
            </div>
            {" "}
            <div className="stat">
              {" "}
              <span className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#bb-i-weeks" />
                </svg>
              </span>
              {" "}
              <b>
                7
              </b>
              <span>
                Tools in the toolkit
              </span>
              {" "}
            </div>
            {" "}
            <div className="stat">
              {" "}
              <span className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#bb-i-doc" />
                </svg>
              </span>
              {" "}
              <b>
                10
              </b>
              <span>
                Guided assignments
              </span>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <div className="frame frame-soft">
        {" "}
        <section className="sec band-dark amb" id="project">
          {" "}
          <div className="shell">
            {" "}
            <div className="bb-project">
              {" "}
              <div className="bb-project-copy rise">
                {" "}
                <span className="eyebrow">
                  The live project
                </span>
                {" "}
                <h2>
                  The Burj Khalifa model,{" "}
                  <span className="grad">
                    and a civil works project
                  </span>
                </h2>
                {" "}
                <p className="ds-lede" style={{ marginTop: "18px" }}>
                  You are not measuring a demo file. Week one you open a real, complicated model and learn to read it the way a quantity surveyor has to, then you audit it, and everything you measure afterwards rests on that audit.
                </p>
                {" "}
                <ul className="ticks">
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-check" />
                    </svg>
                    Building works from the Burj Khalifa Revit model
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-check" />
                    </svg>
                    Earthworks, roads and drainage from a civil works model
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-check" />
                    </svg>
                    Each participant is allocated their own section to carry through
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-check" />
                    </svg>
                    Measured to BESMM 4R and NRM 2
                  </li>
                  {" "}
                </ul>
                {" "}
                <div className="frag" style={{ marginTop: "26px" }}>
                  {" "}
                  <div className="frag-t">
                    Where the chain starts
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Model audit
                    </span>
                    <span className="frag-v">
                      Week 1
                    </span>
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Quantities
                    </span>
                    <span className="frag-v">
                      Week 2
                    </span>
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Priced bill
                    </span>
                    <span className="frag-v">
                      Week 3
                    </span>
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Valuation
                    </span>
                    <span className="frag-v">
                      Week 4
                    </span>
                  </div>
                  {" "}
                  <div className="frag-sum">
                    <span>
                      Cashflow forecast
                    </span>
                    <span className="frag-v">
                      Week 5
                    </span>
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <figure className="bb-project-art rise">
                {" "}
                <img className="art-l" src="/ds/bb-art-light.jpg" alt="The Burj Khalifa as a BIM model over a set of drawings" loading="lazy" width="1100" height="1375" />
                {" "}
                <img className="art-d" src="/ds/bb-art-dark.jpg" alt="The Burj Khalifa as a BIM model over a set of drawings" loading="lazy" width="1100" height="1375" />
                {" "}
                <figcaption>
                  Every stage feeds the next. The quantities you take off in week two price the bill in week three; that bill and the programme drive the valuation in week four.
                </figcaption>
                {" "}
              </figure>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </div>
      {" "}
      {/* =========================================================== programme */}
      {" "}
      <section className="sec" id="programme">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise">
            {" "}
            <span className="eyebrow">
              Programme flow
            </span>
            {" "}
            <h2>
              Five stages,{" "}
              <span className="grad">
                one continuous chain
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              Nothing here is a standalone module. This is one project moving forward.
            </p>
            {" "}
          </div>
          {" "}
          <div className="bb-chain rise">
            {" "}
            <a className="bb-link" href="#week-1">
              <i>
                01
              </i>
              {" "}
              <b>
                Read &amp; audit
              </b>
              {" "}
              <p>
                Navigate the model, interrogate it, and audit it for takeoff readiness.
              </p>
            </a>
            {" "}
            <a className="bb-link" href="#week-2">
              <i>
                02
              </i>
              {" "}
              <b>
                Take off
              </b>
              {" "}
              <p>
                Building, civil and MEP quantities: model-based, with 2D where the model stops.
              </p>
            </a>
            {" "}
            <a className="bb-link" href="#week-3">
              <i>
                03
              </i>
              {" "}
              <b>
                Bill &amp; price
              </b>
              {" "}
              <p>
                Build the BoQ, price it with market rates, produce the schedules and the budget.
              </p>
            </a>
            {" "}
            <a className="bb-link" href="#week-4">
              <i>
                04
              </i>
              {" "}
              <b>
                Programme &amp; value
              </b>
              {" "}
              <p>
                Sequence the works, run an interim valuation, price the variations.
              </p>
            </a>
            {" "}
            <a className="bb-link" href="#week-5">
              <i>
                05
              </i>
              {" "}
              <b>
                Forecast
              </b>
              {" "}
              <p>
                Cashflow from the priced bill and programme, then present the whole workflow.
              </p>
            </a>
            {" "}
          </div>
          {" "}
          <div className="tbl-wrap rise" style={{ marginTop: "56px" }}>
            {" "}
            <table className="tbl">
              <thead>
                <tr>
                  <th>
                    Week
                  </th>
                  <th>
                    Stage
                  </th>
                  <th>
                    What you do
                  </th>
                  <th>
                    Tools
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    Week 1
                  </td>
                  <td>
                    3D model basics and design check
                  </td>
                  <td>
                    Navigate and interrogate a Revit model, understand how a QS reads a model, audit it for takeoff readiness and clash issues
                  </td>
                  <td className="num">
                    Revit · QUIV
                  </td>
                </tr>
                <tr>
                  <td>
                    Week 2
                  </td>
                  <td>
                    Quantity takeoff
                  </td>
                  <td>
                    Model-based takeoff for building and civil works, 2D takeoff where the model stops, quantity reconciliation
                  </td>
                  <td className="num">
                    QUIV · HERON · MEP Suite
                  </td>
                </tr>
                <tr>
                  <td>
                    Week 3
                  </td>
                  <td>
                    Bill preparation, pricing and schedules
                  </td>
                  <td>
                    Build the BoQ, price it with market rates, produce material and labour schedules and the budget
                  </td>
                  <td className="num">
                    QUIV · RateGen
                  </td>
                </tr>
                <tr>
                  <td>
                    Week 4
                  </td>
                  <td>
                    Programme, valuation and variations
                  </td>
                  <td>
                    Programme of works, interim valuation from the priced bill, variation pricing and the change record
                  </td>
                  <td className="num">
                    ADLM TimePro · ADLM Cloud
                  </td>
                </tr>
                <tr>
                  <td>
                    Week 5
                  </td>
                  <td>
                    Cashflow forecast and capstone
                  </td>
                  <td>
                    Cashflow forecast from bill and programme, AI in the QS workflow, full-workflow presentation
                  </td>
                  <td className="num">
                    ADLM Cloud · all tools
                  </td>
                </tr>
              </tbody>
            </table>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      {/* ============================================================ sessions */}
      {" "}
      <section className="sec-half" id="sessions" style={{ paddingBottom: "120px" }}>
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              Session by session
            </span>
            {" "}
            <h2>
              Every one of the ten sessions,{" "}
              <span className="tone">
                and what you hand in
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              Two live sessions a week of two hours each, plus a guided assignment on the live project between them. Open a week to see it.
            </p>
            {" "}
          </div>
          {" "}
          <div className="bb-weeks rise" id="bb-weeks">
            {" "}
            {/* WEEK 1 */}
            {" "}
            <article className="bb-week open" id="week-1">
              {" "}
              <button type="button" className="bb-wk-head" aria-expanded="true" aria-controls="wkb-1">
                {" "}
                <span className="bb-wk-n">
                  <i>
                    Week
                  </i>
                  <b>
                    01
                  </b>
                </span>
                {" "}
                <span className="bb-wk-t">
                  {" "}
                  <h3>
                    3D model basics and design check
                  </h3>
                  {" "}
                  <p>
                    What BIM changes for a quantity surveyor, and how to prove a model is fit to measure before you measure it.
                  </p>
                  {" "}
                  <span className="bb-chips">
                    {" "}
                    <span className="bb-chip">
                      Autodesk Revit
                    </span>
                    {" "}
                    <span className="bb-chip">
                      <img src="/ds/bb-ic-quiv.png" alt="" />
                      QUIV
                    </span>
                    {" "}
                  </span>
                  {" "}
                </span>
                {" "}
                <span className="bb-wk-x">
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-arrow" />
                  </svg>
                </span>
                {" "}
              </button>
              {" "}
              <div className="bb-wk-body" id="wkb-1">
                <div>
                  <div className="bb-wk-in">
                    {" "}
                    <div className="bb-sess">
                      {" "}
                      <span className="host">
                        Session 1
                      </span>
                      {" "}
                      <h4>
                        The model as the QS's document
                      </h4>
                      {" "}
                      <ul>
                        {" "}
                        <li>
                          What BIM changes for the quantity surveyor: from drawings to a database of elements
                        </li>
                        {" "}
                        <li>
                          Revit interface for the non-modeller: views, levels, categories, families, types and parameters
                        </li>
                        {" "}
                        <li>
                          Reading the Burj Khalifa model: structure, architecture, MEP, and where quantities live
                        </li>
                        {" "}
                        <li>
                          Levels of development and what each means for takeoff reliability
                        </li>
                        {" "}
                      </ul>
                      {" "}
                      <p className="bb-task">
                        <b>
                          Assignment.
                        </b>
                        {" "}Model exploration checklist on the live project.
                      </p>
                      {" "}
                    </div>
                    {" "}
                    <div className="bb-sess">
                      {" "}
                      <span className="host">
                        Session 2
                      </span>
                      {" "}
                      <h4>
                        Design check before takeoff
                      </h4>
                      {" "}
                      <ul>
                        {" "}
                        <li>
                          Model audit: missing elements, duplicates, unjoined geometry, wrong categories, placeholder families
                        </li>
                        {" "}
                        <li>
                          Clash and coordination issues that change quantities
                        </li>
                        {" "}
                        <li>
                          Parameter and naming checks so takeoff rules work
                        </li>
                        {" "}
                        <li>
                          Raising a model query register and closing it with the design team
                        </li>
                        {" "}
                      </ul>
                      {" "}
                      <p className="bb-task">
                        <b>
                          Assignment.
                        </b>
                        {" "}Audit report and query register on the live project.
                      </p>
                      {" "}
                    </div>
                    {" "}
                  </div>
                </div>
              </div>
              {" "}
            </article>
            {" "}
            {/* WEEK 2 */}
            {" "}
            <article className="bb-week" id="week-2">
              {" "}
              <button type="button" className="bb-wk-head" aria-expanded="false" aria-controls="wkb-2">
                {" "}
                <span className="bb-wk-n">
                  <i>
                    Week
                  </i>
                  <b>
                    02
                  </b>
                </span>
                {" "}
                <span className="bb-wk-t">
                  {" "}
                  <h3>
                    Quantity takeoff
                  </h3>
                  {" "}
                  <p>
                    Building, civil and MEP quantities out of the models, and 2D takeoff for everywhere the model runs out.
                  </p>
                  {" "}
                  <span className="bb-chips">
                    {" "}
                    <span className="bb-chip">
                      <img src="/ds/bb-ic-quiv.png" alt="" />
                      QUIV
                    </span>
                    {" "}
                    <span className="bb-chip">
                      <img src="/ds/bb-ic-heron.png" alt="" />
                      HERON
                    </span>
                    {" "}
                    <span className="bb-chip">
                      <img src="/ds/bb-ic-mep.png" alt="" />
                      MEP Suite
                    </span>
                    {" "}
                  </span>
                  {" "}
                </span>
                {" "}
                <span className="bb-wk-x">
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-arrow" />
                  </svg>
                </span>
                {" "}
              </button>
              {" "}
              <div className="bb-wk-body" id="wkb-2">
                <div>
                  <div className="bb-wk-in">
                    {" "}
                    <div className="bb-sess">
                      {" "}
                      <span className="host">
                        Session 1
                      </span>
                      {" "}
                      <h4>
                        Model-based takeoff for building works
                      </h4>
                      {" "}
                      <ul>
                        {" "}
                        <li>
                          QUIV setup: measurement rules, units and classification (BESMM 4R and NRM 2)
                        </li>
                        {" "}
                        <li>
                          Substructure, frame, upper floors, roof, walls, finishes: takeoff by category
                        </li>
                        {" "}
                        <li>
                          Handling voids, openings, deductions and partial elements
                        </li>
                        {" "}
                        <li>
                          Exporting and reconciling quantities against a manual check
                        </li>
                        {" "}
                      </ul>
                      {" "}
                      <p className="bb-task">
                        <b>
                          Assignment.
                        </b>
                        {" "}Building takeoff for your allocated section of the model.
                      </p>
                      {" "}
                    </div>
                    {" "}
                    <div className="bb-sess">
                      {" "}
                      <span className="host">
                        Session 2
                      </span>
                      {" "}
                      <h4>
                        Civil works, MEP and 2D gaps
                      </h4>
                      {" "}
                      <ul>
                        {" "}
                        <li>
                          Civil works takeoff: earthworks, roads, drainage and retaining structures from the civil model
                        </li>
                        {" "}
                        <li>
                          MEP takeoff with MEP Suite: pipework, ductwork, cable containment and fittings
                        </li>
                        {" "}
                        <li>
                          HERON for 2D takeoff where the model is incomplete or unavailable
                        </li>
                        {" "}
                        <li>
                          Bringing all quantities into one consistent set
                        </li>
                        {" "}
                      </ul>
                      {" "}
                      <p className="bb-task">
                        <b>
                          Assignment.
                        </b>
                        {" "}Civil and MEP takeoff, merged into one quantity set.
                      </p>
                      {" "}
                    </div>
                    {" "}
                  </div>
                </div>
              </div>
              {" "}
            </article>
            {" "}
            {/* WEEK 3 */}
            {" "}
            <article className="bb-week" id="week-3">
              {" "}
              <button type="button" className="bb-wk-head" aria-expanded="false" aria-controls="wkb-3">
                {" "}
                <span className="bb-wk-n">
                  <i>
                    Week
                  </i>
                  <b>
                    03
                  </b>
                </span>
                {" "}
                <span className="bb-wk-t">
                  {" "}
                  <h3>
                    Bill preparation, pricing and schedules
                  </h3>
                  {" "}
                  <p>
                    Quantities become a bill, the bill gets a defensible rate, and the schedules and cost plan come off the back of it.
                  </p>
                  {" "}
                  <span className="bb-chips">
                    {" "}
                    <span className="bb-chip">
                      <img src="/ds/bb-ic-quiv.png" alt="" />
                      QUIV
                    </span>
                    {" "}
                    <span className="bb-chip">
                      <img src="/ds/bb-ic-rategen.png" alt="" />
                      RateGen
                    </span>
                    {" "}
                  </span>
                  {" "}
                </span>
                {" "}
                <span className="bb-wk-x">
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-arrow" />
                  </svg>
                </span>
                {" "}
              </button>
              {" "}
              <div className="bb-wk-body" id="wkb-3">
                <div>
                  <div className="bb-wk-in">
                    {" "}
                    <div className="bb-sess">
                      {" "}
                      <span className="host">
                        Session 1
                      </span>
                      {" "}
                      <h4>
                        Bill of quantities
                      </h4>
                      {" "}
                      <ul>
                        {" "}
                        <li>
                          From quantities to bill items: descriptions, units and the rules of measurement
                        </li>
                        {" "}
                        <li>
                          Bill structure: preliminaries, elements, work sections, provisional sums and dayworks
                        </li>
                        {" "}
                        <li>
                          Generating the bill from QUIV and cleaning it for issue
                        </li>
                        {" "}
                        <li>
                          Pricing with RateGen: rate build-up, market rate checks and outlier flags
                        </li>
                        {" "}
                      </ul>
                      {" "}
                      <p className="bb-task">
                        <b>
                          Assignment.
                        </b>
                        {" "}Priced BoQ for your allocated section.
                      </p>
                      {" "}
                    </div>
                    {" "}
                    <div className="bb-sess">
                      {" "}
                      <span className="host">
                        Session 2
                      </span>
                      {" "}
                      <h4>
                        Material and labour schedules, and the budget
                      </h4>
                      {" "}
                      <ul>
                        {" "}
                        <li>
                          Material schedule from the bill: quantities, waste allowances, delivery batches
                        </li>
                        {" "}
                        <li>
                          Labour schedule: gang composition, productivity rates and labour hours by trade
                        </li>
                        {" "}
                        <li>
                          Plant and equipment schedule
                        </li>
                        {" "}
                        <li>
                          Building the project budget: cost plan, contingency and cost limits
                        </li>
                        {" "}
                      </ul>
                      {" "}
                      <p className="bb-task">
                        <b>
                          Assignment.
                        </b>
                        {" "}Material and labour schedules and a cost plan summary.
                      </p>
                      {" "}
                    </div>
                    {" "}
                  </div>
                </div>
              </div>
              {" "}
            </article>
            {" "}
            {/* WEEK 4 */}
            {" "}
            <article className="bb-week" id="week-4">
              {" "}
              <button type="button" className="bb-wk-head" aria-expanded="false" aria-controls="wkb-4">
                {" "}
                <span className="bb-wk-n">
                  <i>
                    Week
                  </i>
                  <b>
                    04
                  </b>
                </span>
                {" "}
                <span className="bb-wk-t">
                  {" "}
                  <h3>
                    Programme, valuation and variations
                  </h3>
                  {" "}
                  <p>
                    The commercial half of the job: sequence the works, value what has been done, and price what changed.
                  </p>
                  {" "}
                  <span className="bb-chips">
                    {" "}
                    <span className="bb-chip">
                      <img src="/ds/bb-ic-timepro.png" alt="" />
                      ADLM TimePro
                    </span>
                    {" "}
                    <span className="bb-chip">
                      ADLM Cloud
                    </span>
                    {" "}
                  </span>
                  {" "}
                </span>
                {" "}
                <span className="bb-wk-x">
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-arrow" />
                  </svg>
                </span>
                {" "}
              </button>
              {" "}
              <div className="bb-wk-body" id="wkb-4">
                <div>
                  <div className="bb-wk-in">
                    {" "}
                    <div className="bb-sess">
                      {" "}
                      <span className="host">
                        Session 1
                      </span>
                      {" "}
                      <h4>
                        Programme of works
                      </h4>
                      {" "}
                      <ul>
                        {" "}
                        <li>
                          Activities, sequencing, durations and dependencies from the bill
                        </li>
                        {" "}
                        <li>
                          Building the programme in ADLM TimePro and linking it to bill items
                        </li>
                        {" "}
                        <li>
                          Critical path, float and resource loading
                        </li>
                        {" "}
                        <li>
                          Baselines and progress updates
                        </li>
                        {" "}
                      </ul>
                      {" "}
                      <p className="bb-task">
                        <b>
                          Assignment.
                        </b>
                        {" "}Baseline programme for your allocated section.
                      </p>
                      {" "}
                    </div>
                    {" "}
                    <div className="bb-sess">
                      {" "}
                      <span className="host">
                        Session 2
                      </span>
                      {" "}
                      <h4>
                        Valuation and variations
                      </h4>
                      {" "}
                      <ul>
                        {" "}
                        <li>
                          Interim valuation: measured work, materials on site, preliminaries and retention
                        </li>
                        {" "}
                        <li>
                          Valuation from the priced bill and programme progress in ADLM Cloud
                        </li>
                        {" "}
                        <li>
                          Variations: identifying, measuring, pricing and agreeing changes
                        </li>
                        {" "}
                        <li>
                          Change record, claims trail and the contract clauses that matter
                        </li>
                        {" "}
                      </ul>
                      {" "}
                      <p className="bb-task">
                        <b>
                          Assignment.
                        </b>
                        {" "}Valuation number one, and two priced variations.
                      </p>
                      {" "}
                    </div>
                    {" "}
                  </div>
                </div>
              </div>
              {" "}
            </article>
            {" "}
            {/* WEEK 5 */}
            {" "}
            <article className="bb-week" id="week-5">
              {" "}
              <button type="button" className="bb-wk-head" aria-expanded="false" aria-controls="wkb-5">
                {" "}
                <span className="bb-wk-n">
                  <i>
                    Week
                  </i>
                  <b>
                    05
                  </b>
                </span>
                {" "}
                <span className="bb-wk-t">
                  {" "}
                  <h3>
                    Cashflow forecast and capstone
                  </h3>
                  {" "}
                  <p>
                    Where the money actually lands, where AI helps and where it does not, then you present the whole thing.
                  </p>
                  {" "}
                  <span className="bb-chips">
                    {" "}
                    <span className="bb-chip">
                      ADLM Cloud
                    </span>
                    {" "}
                    <span className="bb-chip">
                      All tools
                    </span>
                    {" "}
                  </span>
                  {" "}
                </span>
                {" "}
                <span className="bb-wk-x">
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-arrow" />
                  </svg>
                </span>
                {" "}
              </button>
              {" "}
              <div className="bb-wk-body" id="wkb-5">
                <div>
                  <div className="bb-wk-in">
                    {" "}
                    <div className="bb-sess">
                      {" "}
                      <span className="host">
                        Session 1
                      </span>
                      {" "}
                      <h4>
                        Cashflow forecast and cost reporting
                      </h4>
                      {" "}
                      <ul>
                        {" "}
                        <li>
                          Cashflow forecast from the priced bill and programme: S-curve, monthly draw-down, retention and payment terms
                        </li>
                        {" "}
                        <li>
                          Cash-in versus cash-out for the contractor and the client view
                        </li>
                        {" "}
                        <li>
                          Updating the forecast with actual valuations
                        </li>
                        {" "}
                        <li>
                          Cost reports and dashboards in ADLM Cloud
                        </li>
                        {" "}
                      </ul>
                      {" "}
                      <p className="bb-task">
                        <b>
                          Assignment.
                        </b>
                        {" "}Cashflow forecast for the project.
                      </p>
                      {" "}
                    </div>
                    {" "}
                    <div className="bb-sess">
                      {" "}
                      <span className="host">
                        Session 2
                      </span>
                      {" "}
                      <h4>
                        AI in the workflow, and the capstone
                      </h4>
                      {" "}
                      <ul>
                        {" "}
                        <li>
                          Where AI fits: rate checking, bill review, catalogue extraction and report drafting, and where it does not
                        </li>
                        {" "}
                        <li>
                          Capstone: you present the full workflow on your section, from model audit to cashflow
                        </li>
                        {" "}
                        <li>
                          Feedback, certification and next steps
                        </li>
                        {" "}
                      </ul>
                      {" "}
                      <p className="bb-task">
                        <b>
                          Capstone.
                        </b>
                        {" "}A presentation of the whole workflow on your own section.
                      </p>
                      {" "}
                    </div>
                    {" "}
                  </div>
                </div>
              </div>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      {/* =============================================================== tools */}
      {" "}
      <div className="frame frame-soft">
        {" "}
        <section className="sec band-dark amb" id="tools">
          {" "}
          <div className="shell">
            {" "}
            <div className="sec-head rise">
              {" "}
              <span className="eyebrow">
                The toolkit
              </span>
              {" "}
              <h2>
                Seven tools,{" "}
                <span className="grad">
                  and a month of access included
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                Every participant receives one month of ADLM software access with the programme. You use the tools on the live project during the sessions, not in a sandbox.
              </p>
              {" "}
            </div>
            {" "}
            <div className="bb-tools rise">
              {" "}
              <a className="bb-tool" href="#week-1">
                {" "}
                <span className="bb-tool-ico">
                  <span className="ico">
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-cube" />
                    </svg>
                  </span>
                </span>
                {" "}
                <b>
                  Autodesk Revit
                </b>
                {" "}
                <span>
                  The model itself: reading it, interrogating it, auditing it.
                </span>
                {" "}
              </a>
              {" "}
              <Link className="bb-tool" to="/product/revit" data-ds-page="quiv">
                {" "}
                <span className="bb-tool-ico">
                  <img src="/ds/bb-ic-quiv.png" alt="" width="192" height="192" />
                </span>
                {" "}
                <b>
                  QUIV
                </b>
                {" "}
                <span>
                  Model-based takeoff and bill generation, inside Revit.
                </span>
                {" "}
              </Link>
              {" "}
              <Link className="bb-tool" to="/product/planswift" data-ds-page="heron">
                {" "}
                <span className="bb-tool-ico">
                  <img src="/ds/bb-ic-heron.png" alt="" width="192" height="192" />
                </span>
                {" "}
                <b>
                  HERON
                </b>
                {" "}
                <span>
                  2D takeoff for everywhere the model is incomplete.
                </span>
                {" "}
              </Link>
              {" "}
              <Link className="bb-tool" to="/product/rategen" data-ds-page="rategen">
                {" "}
                <span className="bb-tool-ico">
                  <img src="/ds/bb-ic-rategen.png" alt="" width="192" height="192" />
                </span>
                {" "}
                <b>
                  RateGen
                </b>
                {" "}
                <span>
                  Rate build-ups, market rate checks and outlier flags.
                </span>
                {" "}
              </Link>
              {" "}
              <Link className="bb-tool" to="/product/mep" data-ds-page="mep">
                {" "}
                <span className="bb-tool-ico">
                  <img src="/ds/bb-ic-mep.png" alt="" width="192" height="192" />
                </span>
                {" "}
                <b>
                  MEP Suite
                </b>
                {" "}
                <span>
                  Pipework, ductwork, containment and fittings.
                </span>
                {" "}
              </Link>
              {" "}
              <Link className="bb-tool" to="/product/qs-takeoff" data-ds-page="timepro">
                {" "}
                <span className="bb-tool-ico">
                  <img src="/ds/bb-ic-timepro.png" alt="" width="192" height="192" />
                </span>
                {" "}
                <b>
                  ADLM TimePro
                </b>
                {" "}
                <span>
                  The programme of works, linked back to bill items.
                </span>
                {" "}
              </Link>
              {" "}
              <Link className="bb-tool" to="/how-it-works" data-ds-page="how-it-works">
                {" "}
                <span className="bb-tool-ico">
                  <span className="ico ico-a">
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-cloud" />
                    </svg>
                  </span>
                </span>
                {" "}
                <b>
                  ADLM Cloud
                </b>
                {" "}
                <span>
                  Valuations, variations, cost reports and the cashflow forecast.
                </span>
                {" "}
              </Link>
              {" "}
              <Link className="bb-tool" to="/learn#guides" data-ds-page="learn">
                {" "}
                <span className="bb-tool-ico">
                  <span className="ico">
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-down" />
                    </svg>
                  </span>
                </span>
                {" "}
                <b>
                  The user guides
                </b>
                {" "}
                <span>
                  Free illustrated PDFs for every product, yours before day one.
                </span>
                {" "}
              </Link>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </div>
      {" "}
      {/* ============================================================ outcomes */}
      {" "}
      <section className="sec" id="outcomes">
        {" "}
        <div className="shell">
          {" "}
          <div className="bb-out" id="bb-out">
            {" "}
            {/* the pin is the outer element and .rise the inner one: .rise animates
           transform, and a transform on the sticky element itself is asking for
           trouble */}
            {" "}
            <div className="bb-out-pin">
              <div className="rise">
                {" "}
                <span className="eyebrow">
                  Outcomes
                </span>
                {" "}
                <h2>
                  What you can do{" "}
                  <span className="tone">
                    on 7 November
                  </span>
                </h2>
                {" "}
                <p className="ds-lede" style={{ marginTop: "18px" }}>
                  Not "understands the principles of". These are the things you will have done yourself, on a real model, and can do again on Monday.
                </p>
                {" "}
                <ul className="ticks">
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-check" />
                    </svg>
                    Audit a Revit model and raise a query register before any quantity is taken
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-check" />
                    </svg>
                    Take off building, civil and MEP quantities from a model and reconcile them
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-check" />
                    </svg>
                    Produce and price a bill of quantities with market rates
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-check" />
                    </svg>
                    Prepare material, labour and plant schedules and a cost plan
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-check" />
                    </svg>
                    Build and update a programme of works linked to the bill
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-check" />
                    </svg>
                    Prepare interim valuations and price variations
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#bb-i-check" />
                    </svg>
                    Produce a cashflow forecast and cost reports from the priced bill and programme
                  </li>
                  {" "}
                </ul>
                {" "}
              </div>
            </div>
            {" "}
            <div className="bb-cert">
              {" "}
              <figure>
                {" "}
                <img className="art-l" src="/ds/bb-cert-light.jpg" alt="The ADLM Studio training certificate" loading="lazy" width="1200" height="900" />
                {" "}
                <img className="art-d" src="/ds/bb-cert-dark.jpg" alt="The ADLM Studio training certificate" loading="lazy" width="1200" height="900" />
                {" "}
              </figure>
              {" "}
              <div className="bb-cert-in">
                {" "}
                <span className="eyebrow">
                  Assessment and certification
                </span>
                {" "}
                <h3>
                  Ten assignments, a capstone, then your certificate
                </h3>
                {" "}
                <p>
                  Every week you hand in work on the live project. In week five you present the full workflow on your own section, model audit through to cashflow.
                </p>
                {" "}
                <p>
                  Pass and you receive a certificate of completion from ADLM Studio, issued in collaboration with the Nigerian Institute of Quantity Surveyors, subject to that collaboration being confirmed.
                </p>
                {" "}
                <div className="frag">
                  {" "}
                  <div className="frag-t">
                    How it is marked
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Weekly assignments
                    </span>
                    <span className="frag-v">
                      10 submissions
                    </span>
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Capstone presentation
                    </span>
                    <span className="frag-v">
                      Week 5
                    </span>
                  </div>
                  {" "}
                  <div className="frag-sum">
                    <span>
                      Certificate of completion
                    </span>
                    <span className="frag-v">
                      On passing
                    </span>
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      {/* ============================================================= who for */}
      {" "}
      <section className="sec-half alt blend" id="whofor">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "44px" }}>
            {" "}
            <span className="eyebrow">
              Before you register
            </span>
            {" "}
            <h2>
              Who it is for,{" "}
              <span className="grad">
                and what you need
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="bb-needs rise">
            {" "}
            <article className="bb-need">
              {" "}
              <div className="bb-need-art">
                <img src="/ds/hd-team.jpg" alt="" loading="lazy" />
              </div>
              {" "}
              <div className="bb-need-in">
                {" "}
                <span className="ico">
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-user" />
                  </svg>
                </span>
                {" "}
                <h4>
                  Who it is for
                </h4>
                {" "}
                <p>
                  Practising quantity surveyors and cost managers, graduate and assistant QSs, and commercial teams on the contractor side who want the whole chain rather than one tool. Final-year students get the most out of it if they already model a little.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="bb-need">
              {" "}
              <div className="bb-need-art">
                <img src="/ds/hd-cad.jpg" alt="" loading="lazy" />
              </div>
              {" "}
              <div className="bb-need-in">
                {" "}
                <span className="ico ico-a">
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-screen" />
                  </svg>
                </span>
                {" "}
                <h4>
                  What you need
                </h4>
                {" "}
                <p>
                  A Windows machine able to run Autodesk Revit, a Revit installation of your own, and a connection steady enough for a two-hour Google Meet with screen sharing. Your one month of ADLM software access comes with the programme.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="bb-need">
              {" "}
              <div className="bb-need-art">
                <img src="/ds/hd-work.jpg" alt="" loading="lazy" />
              </div>
              {" "}
              <div className="bb-need-in">
                {" "}
                <span className="ico">
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-clock" />
                  </svg>
                </span>
                {" "}
                <h4>
                  What it costs you in time
                </h4>
                {" "}
                <p>
                  Four live hours a week, plus the assignment between sessions. Every session is recorded and released to registered participants, so a clash with work is something you catch up on rather than something you lose.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      {/* ================================================================= fee */}
      {" "}
      <section className="sec" id="fee">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              Fee
            </span>
            {" "}
            <h2>
              ₦180,000 per participant,{" "}
              <span className="tone">
                everything included
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              One fee. No separate software charge for the duration, no separate certification charge.
            </p>
            {" "}
          </div>
          {" "}
          <div className="bb-fee rise">
            {" "}
            <div className="bb-price">
              {" "}
              <span className="eyebrow">
                Beyond BIM · October 2026 cohort
              </span>
              {" "}
              <div className="amt">
                ₦180,000
                <small>
                  per participant
                </small>
              </div>
              {" "}
              <p className="note">
                Payable on registration. Registration closes when the cohort fills or on 5 October 2026, whichever comes first.
              </p>
              {" "}
              <ul className="ticks">
                {" "}
                <li>
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-check" />
                  </svg>
                  Ten live sessions, two hours each, on Google Meet
                </li>
                {" "}
                <li>
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-check" />
                  </svg>
                  Every session recorded and released to you
                </li>
                {" "}
                <li>
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-check" />
                  </svg>
                  One month of ADLM software access
                </li>
                {" "}
                <li>
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-check" />
                  </svg>
                  The Burj Khalifa and civil works project files
                </li>
                {" "}
                <li>
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-check" />
                  </svg>
                  Ten guided assignments, marked with feedback
                </li>
                {" "}
                <li>
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-check" />
                  </svg>
                  Certificate of completion on passing the capstone
                </li>
                {" "}
              </ul>
              {" "}
              <Link to="/beyondbim/register" data-ds-page="beyondbim-register" className="ds-btn btn-p btn-full" style={{ marginTop: "24px" }}>
                Register for the cohort
              </Link>
              {" "}
            </div>
            {" "}
            <div className="bb-side">
              {" "}
              <h4>
                Sending more than one person?
              </h4>
              {" "}
              <p>
                Firms, NIQS chapters and departments training a group should talk to us before registering. We will price the cohort and can run the assignments against your own project instead of the Burj Khalifa model.
              </p>
              {" "}
              <div className="row">
                <span>
                  Programme
                </span>
                <b>
                  Beyond BIM · 5 weeks
                </b>
              </div>
              {" "}
              <div className="row">
                <span>
                  Dates
                </span>
                <b>
                  6 Oct – 7 Nov 2026
                </b>
              </div>
              {" "}
              <div className="row">
                <span>
                  Delivery
                </span>
                <b>
                  Live online · Google Meet
                </b>
              </div>
              {" "}
              <div className="row">
                <span>
                  Session days
                </span>
                <b>
                  Confirmed on registration
                </b>
              </div>
              {" "}
              <div className="row">
                <span>
                  Fee
                </span>
                <b>
                  ₦180,000 per person
                </b>
              </div>
              {" "}
              <div className="bb-side-cta">
                {" "}
                <a href="https://wa.me/2348106503524" className="ds-btn btn-p ds-btn-sm">
                  Talk to us on WhatsApp
                </a>
                {" "}
                <a href="mailto:admin@adlmstudio.net?subject=Beyond%20BIM%20—%20group%20registration" className="ds-btn btn-o ds-btn-sm">
                  Email us
                </a>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      {/* ============================================================== poster */}
      {" "}
      <section className="sec-half alt blend" id="share">
        {" "}
        <div className="shell">
          {" "}
          <div className="bb-poster">
            {" "}
            <figure className="rise">
              {" "}
              <img className="art-l" src="/ds/bb-poster-light.jpg" alt="Beyond BIM programme flyer" loading="lazy" width="1000" height="1250" />
              {" "}
              <img className="art-d" src="/ds/bb-poster.jpg" alt="Beyond BIM programme flyer" loading="lazy" width="1000" height="1250" />
              {" "}
            </figure>
            {" "}
            <div className="rise">
              {" "}
              <span className="eyebrow">
                Pass it on
              </span>
              {" "}
              <h2>
                Someone on your team{" "}
                <span className="grad">
                  should be on this
                </span>
              </h2>
              {" "}
              <p className="ds-lede" style={{ marginTop: "18px" }}>
                Take the flyer, or send them the link. The whole programme is on this page. There is nothing behind a form except your own place on it.
              </p>
              {" "}
              <div className="hero-cta" style={{ justifyContent: "flex-start" }}>
                {" "}
                <Link to="/ds/bb-poster.jpg" className="ds-btn btn-p" download="ADLM-Beyond-BIM-Oct-2026.jpg">
                  Download the flyer{" "}
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-down" />
                  </svg>
                </Link>
                {" "}
                <button type="button" className="ds-btn btn-o" id="bb-share">
                  Copy the link
                </button>
                {" "}
              </div>
              {" "}
              <p className="small" style={{ marginTop: "18px", color: "var(--ink-3)" }}>
                adlmstudio.net/beyondbim
              </p>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      {/* ================================================================= faq */}
      {" "}
      <section className="sec-half blend" id="faq">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "38px" }}>
            {" "}
            <span className="eyebrow">
              Questions
            </span>
            {" "}
            <h2>
              About Beyond BIM
            </h2>
            {" "}
          </div>
          {" "}
          <div className="faq rise">
            {" "}
            <details open={true}>
              {" "}
              <summary>
                Do I need to own Revit or any ADLM product first?
              </summary>
              {" "}
              <div className="faq-a">
                Every participant receives one month of ADLM software access with the programme, so QUIV, HERON, RateGen, MEP Suite, TimePro and ADLM Cloud are covered. You bring your own Revit installation and a Windows machine able to run it.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                What are the session days and times?
              </summary>
              {" "}
              <div className="faq-a">
                Two sessions a week across October 2026, running 6 October to 7 November. The exact days and times are set once the cohort is confirmed and go out to registered participants, that way they suit the people actually in the room.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                What happens if I miss a live session?
              </summary>
              {" "}
              <div className="faq-a">
                Every session is recorded and released to registered participants. You catch up on the recording and still hand in the assignment. The chain only works if you do each stage, so the assignment matters more than attendance on the night.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Is this the same as the six-week certificated courses?
              </summary>
              {" "}
              <div className="faq-a">
                No. The{" "}
                <Link to="/learn#courses" data-ds-page="learn">
                  certificated courses
                </Link>
                {" "}are self-paced through Google Classroom and go deep on one discipline. Beyond BIM is a live cohort that runs one project end to end across every stage of the QS role.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Is the certificate recognised?
              </summary>
              {" "}
              <div className="faq-a">
                It is a certificate of completion from ADLM Studio, issued in collaboration with the Nigerian Institute of Quantity Surveyors, subject to that collaboration being confirmed. It evidences the work you did; it is not a professional accreditation.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Can my firm run this on our own project?
              </summary>
              {" "}
              <div className="faq-a">
                Yes. For a group we can run the assignments against your own model instead of the Burj Khalifa. That is priced on cohort size,{" "}
                <a href="https://wa.me/2348106503524">
                  start on WhatsApp
                </a>
                {" "}or email admin@adlmstudio.net.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                How do I pay, and when?
              </summary>
              {" "}
              <div className="faq-a">
                Register first. We confirm your place by email and send the payment details and the joining instructions with it. Your place is held while you pay.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                What if I have never opened Revit?
              </summary>
              {" "}
              <div className="faq-a">
                Week one is built for the non-modeller: the interface, views, levels, categories, families and parameters, taught from a quantity surveyor's side of the desk. You are not being trained to model. You are being trained to read and interrogate one.
              </div>
              {" "}
            </details>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      {/* ==================================================== registration band */}
      {" "}
      <section className="sec-half" id="register">
        {" "}
        <div className="shell">
          {" "}
          <div className="bb-banner band-dark rise">
            {" "}
            <div className="bb-banner-art">
              <img src="/ds/bb-art-dark.jpg" alt="" loading="lazy" />
            </div>
            {" "}
            <div className="bb-banner-in">
              {" "}
              <span className="eyebrow">
                Registration
              </span>
              {" "}
              <h2>
                Take your place in the{" "}
                <span className="grad">
                  October cohort
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                Two minutes to register. We confirm by email with the session days, the payment details and your joining instructions.
              </p>
              {" "}
              <div className="bb-banner-facts">
                {" "}
                <div>
                  <b>
                    6 Oct – 7 Nov 2026
                  </b>
                  <span>
                    Five weeks, ten sessions
                  </span>
                </div>
                {" "}
                <div>
                  <b>
                    ₦180,000
                  </b>
                  <span>
                    Per participant, all in
                  </span>
                </div>
                {" "}
                <div>
                  <b>
                    Places are limited
                  </b>
                  <span>
                    Closes 5 Oct or when full
                  </span>
                </div>
                {" "}
              </div>
              {" "}
              <div className="hero-cta" style={{ justifyContent: "flex-start" }}>
                {" "}
                <Link to="/beyondbim/register" data-ds-page="beyondbim-register" className="ds-btn btn-p">
                  Register for Beyond BIM{" "}
                  <svg viewBox="0 0 24 24">
                    <use href="#bb-i-arrow" />
                  </svg>
                </Link>
                {" "}
                <a href="https://wa.me/2348106503524" className="ds-btn btn-o">
                  Ask a question first
                </a>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <div className="bb-bar" id="bb-bar">
        {" "}
        <div className="bb-bar-in">
          {" "}
          <div>
            {" "}
            <b>
              Beyond BIM · ₦180,000
            </b>
            {" "}
            <span>
              6 Oct – 7 Nov 2026 · live online · 10 sessions
            </span>
            {" "}
          </div>
          {" "}
          <Link to="/beyondbim/register" data-ds-page="beyondbim-register" className="ds-btn btn-p ds-btn-sm">
            Register
          </Link>
          {" "}
        </div>
        {" "}
      </div>
      {" "}{DsPromoSlot}{" "}
      <section className="cta">
        {" "}
        <div className="cta-bp">
        </div>
        <div className="cta-dots">
        </div>
        <div className="cta-g">
        </div>
        {" "}
        <h2>
          Train the{" "}
          <span className="grad">
            whole department
          </span>
        </h2>
        {" "}
        <p className="ds-lede">
          Chapters, universities and commercial teams. We will run Beyond BIM against your own project instead of ours.
        </p>
        {" "}
        <div className="hero-cta">
          {" "}
          <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
            Talk to us
          </Link>
          {" "}
          <Link to="/learn" data-ds-page="learn" className="ds-btn btn-o">
            All ADLM training
          </Link>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
