// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/cart.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";

export default function DsCart() {
  return (
    <>
      <section className="sec" style={{ paddingTop: "150px" }}>
        {" "}
        <div className="shell">
          {" "}
          <div className="flowsteps">
            {" "}
            <div className="on">
              <i>
                1
              </i>
              Cart
            </div>
            {" "}
            <s>
            </s>
            {" "}
            <div className="">
              <i>
                2
              </i>
              Account
            </div>
            {" "}
            <s>
            </s>
            {" "}
            <div className="">
              <i>
                3
              </i>
              Payment
            </div>
            {" "}
            <s>
            </s>
            {" "}
            <div className="">
              <i>
                4
              </i>
              Install
            </div>
            {" "}
          </div>
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "38px" }}>
            {" "}
            <span className="eyebrow">
              Step 1 of 4
            </span>
            {" "}
            <h2>
              Your cart
            </h2>
            {" "}
            <p className="ds-lede">
              Set how many PCs each licence covers. Yearly billing costs ten months, so two are free.
            </p>
            {" "}
          </div>
          {" "}
          <div className="chk" id="cart">
            {" "}
            <div className="panel rise">
              {" "}
              <h3>
                Licences
              </h3>
              {" "}
              <p className="ds-sub">
                Prices are per PC. Install fees are charged once.
              </p>
              {" "}
              <div className="toggle2" id="bill-toggle" role="group" aria-label="Billing period">
                {" "}
                <button type="button" className="on" data-bill="monthly">
                  Monthly
                </button>
                {" "}
                <button type="button" data-bill="yearly">
                  Yearly · 2 months free
                </button>
                {" "}
              </div>
              {" "}
              <div className="line" data-sku="quiv" data-price="50000" data-install="25000">
                {" "}
                <img src="/ds/ic-quiv.png" alt="" />
                {" "}
                <div>
                  {" "}
                  <b>
                    QUIV
                  </b>
                  <span>
                    3D takeoff · Autodesk Revit
                  </span>
                  {" "}
                  <div className="qty">
                    {" "}
                    <button type="button" data-step="-1" aria-label="Fewer QUIV seats">
                      −
                    </button>
                    {" "}
                    <span data-qty="">
                      2
                    </span>
                    {" "}
                    <button type="button" data-step="1" aria-label="More QUIV seats">
                      +
                    </button>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="amt2">
                  <span data-lt="">
                    ₦100,000
                  </span>
                  <small data-lu="">
                    2 × ₦50,000 / mo
                  </small>
                </div>
                {" "}
              </div>
              {" "}
              <div className="line" data-sku="rategen" data-price="8000" data-install="0">
                {" "}
                <img src="/ds/ic-rategen.png" alt="" />
                {" "}
                <div>
                  {" "}
                  <b>
                    RateGen
                  </b>
                  <span>
                    Rate build-ups · desktop
                  </span>
                  {" "}
                  <div className="qty">
                    {" "}
                    <button type="button" data-step="-1" aria-label="Fewer RateGen seats">
                      −
                    </button>
                    {" "}
                    <span data-qty="">
                      2
                    </span>
                    {" "}
                    <button type="button" data-step="1" aria-label="More RateGen seats">
                      +
                    </button>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="amt2">
                  <span data-lt="">
                    ₦16,000
                  </span>
                  <small data-lu="">
                    2 × ₦8,000 / mo
                  </small>
                </div>
                {" "}
              </div>
              {" "}
              <div className="line" data-sku="heron" data-price="12000" data-install="15000">
                {" "}
                <img src="/ds/ic-heron.png" alt="" />
                {" "}
                <div>
                  {" "}
                  <b>
                    HERON
                  </b>
                  <span>
                    2D takeoff · PlanSwift
                  </span>
                  {" "}
                  <div className="qty">
                    {" "}
                    <button type="button" data-step="-1" aria-label="Fewer HERON seats">
                      −
                    </button>
                    {" "}
                    <span data-qty="">
                      1
                    </span>
                    {" "}
                    <button type="button" data-step="1" aria-label="More HERON seats">
                      +
                    </button>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="amt2">
                  <span data-lt="">
                    ₦12,000
                  </span>
                  <small data-lu="">
                    1 × ₦12,000 / mo
                  </small>
                </div>
                {" "}
              </div>
              {" "}
              <p className="small" style={{ marginTop: "20px" }}>
                Need something not listed, or more than ten seats?{" "}
                <Link to="/quote" data-ds-page="quote" style={{ color: "var(--action)" }}>
                  Build a quotation instead
                </Link>
                .
              </p>
              {" "}
            </div>
            {" "}
            <div className="panel rise">
              {" "}
              <h3>
                Summary
              </h3>
              {" "}
              <p className="ds-sub" id="sum-note">
                Billed monthly, cancel anytime.
              </p>
              {" "}
              <div id="sum-rows">
              </div>
              {" "}
              <Link to="/signup" data-ds-page="signup" className="ds-btn btn-p btn-full" style={{ marginTop: "22px" }} id="to-account">
                Continue to account
              </Link>
              {" "}
              <Link to="/products" data-ds-page="products" className="ds-btn btn-o btn-full" style={{ marginTop: "10px" }}>
                Keep browsing
              </Link>
              {" "}
              <div className="trust">
                {" "}
                <span>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                  Secure checkout via Paystack
                </span>
                {" "}
                <span>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                  Instant licence activation
                </span>
                {" "}
                <span>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                  Cancel anytime
                </span>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
