// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/customers.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";
import DsPromoLive from "../DsPromoLive.jsx";

export default function DsCustomers() {
  const DsPromoSlot = <DsPromoLive />;
  return (
    <>
      <header className="phero phero-sm">
        {" "}
        <div className="phero-bg">
          <img src="/ds/ev3.jpg" alt="" />
        </div>
        {" "}
        <div className="phero-in">
          {" "}
          <span className="host">
            Customers
          </span>
          {" "}
          <h1>
            {" "}
            <span className="w" style={{ "--i": "0" }}>
              Who
            </span>
            {" "}
            <span className="w" style={{ "--i": "1" }}>
              we've
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "2" }}>
              worked
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "3" }}>
              with.
            </span>
            {" "}
          </h1>
          {" "}
          <p className="ds-lede">
            Institutions, firms and universities across Nigeria — and the events where most of them first met the tools.
          </p>
          {" "}
          <div className="hero-cta">
            {" "}
            <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
              Talk to us
            </Link>
            {" "}
            <Link to="/learn#events" data-ds-page="learn" className="ds-btn btn-o">
              See training
            </Link>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <section className="sec-sm">
        {" "}
        <div className="shell">
          {" "}
          <div className="statframe rise">
            {" "}
            <div className="stat">
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-user" />
                </svg>
              </div>
              {" "}
              <b data-count="3100" data-suffix="+">
                3,100+
              </b>
              <span>
                Professionals trained
              </span>
            </div>
            {" "}
            <div className="stat">
              <div className="ico ico-a">
                <svg viewBox="0 0 24 24">
                  <use href="#i-screen" />
                </svg>
              </div>
              {" "}
              <b data-count="30" data-suffix="+">
                30+
              </b>
              <span>
                Events delivered
              </span>
            </div>
            {" "}
            <div className="stat">
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-layers" />
                </svg>
              </div>
              {" "}
              <b data-count="25" data-suffix="+">
                25+
              </b>
              <span>
                Organisations trained
              </span>
            </div>
            {" "}
            <div className="stat">
              <div className="ico ico-a">
                <svg viewBox="0 0 24 24">
                  <use href="#i-cloud" />
                </svg>
              </div>
              {" "}
              <b data-count="10" data-suffix="+">
                10+
              </b>
              <span>
                Countries reached
              </span>
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <div className="frame frame-soft">
        {" "}
        <section className="sec band-dark amb">
          {" "}
          <div className="shell">
            {" "}
            <div className="sec-head mid rise">
              {" "}
              <span className="eyebrow">
                Where we've taught
              </span>
              {" "}
              <h2>
                Rooms we've{" "}
                <span className="grad">
                  stood in front of
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                A selection of the institutions and events that have hosted ADLM training.
              </p>
              {" "}
            </div>
            {" "}
            <div className="fgrid fgrid-4">
              {" "}
              <article className="fcard tilt rise">
                {" "}
                <div className="fviz" style={{ padding: "0" }}>
                  <img src="/ds/ev3.jpg" alt="The Big 5 Construct Nigeria" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                </div>
                {" "}
                <div className="fcard-body">
                  <h4>
                    The Big 5 Construct Nigeria
                  </h4>
                  {" "}
                  <p>
                    Panel on cost versus sustainability in building projects, Landmark Centre, Lagos —{" "}
                    <strong>
                      1,480 attendees
                    </strong>
                    .
                  </p>
                </div>
                {" "}
              </article>
              {" "}
              <article className="fcard tilt rise">
                {" "}
                <div className="fviz" style={{ padding: "0" }}>
                  <img src="/ds/ev1.jpg" alt="NIQS workshop" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                </div>
                {" "}
                <div className="fcard-body">
                  <h4>
                    NIQS chapters
                  </h4>
                  {" "}
                  <p>
                    Rivers, Cross River, Ogun and the NIQS Foundation — including a three-day workshop on AI in quantity surveying,{" "}
                    <strong>
                      200 attendees
                    </strong>
                    .
                  </p>
                </div>
                {" "}
              </article>
              {" "}
              <article className="fcard tilt rise">
                {" "}
                <div className="fviz" style={{ padding: "0" }}>
                  <img src="/ds/ev2.jpg" alt="Institutional training" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                </div>
                {" "}
                <div className="fcard-body">
                  <h4>
                    Federal Airport Authority Nigeria
                  </h4>
                  {" "}
                  <p>
                    Hands-on 4D and 5D BIM training for the Quantity Surveying department, delivered on site.
                  </p>
                </div>
                {" "}
              </article>
              {" "}
              <article className="fcard tilt rise">
                {" "}
                <div className="fviz" style={{ padding: "0" }}>
                  <img src="/ds/ev4.jpg" alt="YQSF Lagos session" style={{ width: "100%", height: "100%", objectFit: "cover" }} />
                </div>
                {" "}
                <div className="fcard-body">
                  <h4>
                    YQSF Lagos &amp; ConTech Nigeria
                  </h4>
                  {" "}
                  <p>
                    Evening sessions for the Young Quantity Surveyors Forum and the ConTech Nigeria community, on measuring from a model instead of a sheet.
                  </p>
                </div>
                {" "}
              </article>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </div>
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              Organisations
            </span>
            {" "}
            <h2>
              Trained, hosted{" "}
              <span className="tone">
                or partnered
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="bento bento-4">
            {" "}
            <article className="bento-c tilt rise">
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-layers" />
                </svg>
              </div>
              {" "}
              <div className="bento-body">
                <h4>
                  Practices &amp; consultancies
                </h4>
                {" "}
                <p>
                  Construworth Consult · BEC Associates · Godaret Consultant · ITB Nigeria
                </p>
              </div>
            </article>
            {" "}
            <article className="bento-c tilt rise">
              <div className="ico ico-a">
                <svg viewBox="0 0 24 24">
                  <use href="#i-user" />
                </svg>
              </div>
              {" "}
              <div className="bento-body">
                <h4>
                  Professional bodies
                </h4>
                {" "}
                <p>
                  NIQS (Rivers, Cross River, Ogun, Foundation) · NIOB · YQSF Lagos · ConTech Nigeria
                </p>
              </div>
            </article>
            {" "}
            <article className="bento-c tilt rise">
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-doc" />
                </svg>
              </div>
              {" "}
              <div className="bento-body">
                <h4>
                  Universities
                </h4>
                {" "}
                <p>
                  Joseph Ayo Babalola University · Rivers State University · Yaba College of Technology
                </p>
              </div>
            </article>
            {" "}
            <article className="bento-c tilt rise">
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-cube" />
                </svg>
              </div>
              {" "}
              <div className="bento-body">
                <h4>
                  Agencies &amp; industry
                </h4>
                {" "}
                <p>
                  Federal Airport Authority Nigeria · AC &amp; Ventilation Systems Ltd · Synthanalytics
                </p>
              </div>
            </article>
            {" "}
          </div>
          {" "}
          <p className="small" style={{ marginTop: "22px" }}>
            Attendance figures are drawn from our own event records. Client quotes are being collected and will be published as they are approved.
          </p>
          {" "}
        </div>
        {" "}
      </section>
      {" "}{DsPromoSlot}{" "}
      <section className="cta">
        {" "}
        <div className="cta-bp">
        </div>
        <div className="cta-dots">
        </div>
        <div className="cta-g">
        </div>
        {" "}
        <h2>
          Bring us to{" "}
          <span className="grad">
            your team
          </span>
        </h2>
        {" "}
        <p className="ds-lede">
          On-site training, priced on cohort size and location. Thirty events delivered so far.
        </p>
        {" "}
        <div className="hero-cta">
          {" "}
          <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
            Request a quote
          </Link>
          {" "}
          <Link to="/learn#events" data-ds-page="learn" className="ds-btn btn-o">
            See the events
          </Link>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
