// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/doc-preview.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";

export default function DsDocPreview() {
  return (
    <>
      <div className="docp">
        {" "}
        <aside className="docp-side doc-noprint">
          {" "}
          <div className="docp-brandbar">
            {" "}
            <b>
              Documents
            </b>
            {" "}
            <span>
              One renderer, seven templates
            </span>
            {" "}
          </div>
          {" "}
          <div className="docp-grp">
            Templates
          </div>
          {" "}
          <ul className="docp-list" id="docp-list">
          </ul>
          {" "}
          <div className="docp-grp">
            Issued as
          </div>
          {" "}
          <div className="docp-seg" id="docp-brand">
            {" "}
            <button type="button" data-brand="adlm" className="on">
              ADLM Studio
            </button>
            {" "}
            <button type="button" data-brand="practice">
              Adeyemi &amp; Partners
            </button>
            {" "}
          </div>
          {" "}
          <p className="docp-note" id="docp-brandnote">
            {" "}ADLM's own paper. Invoices and receipts carry VAT at 7.5%, and nothing credits ADLM to itself.{" "}
          </p>
          {" "}
          <div className="docp-grp">
            Page
          </div>
          {" "}
          <div className="docp-seg" id="docp-zoom">
            {" "}
            <button type="button" data-zoom="0.6">
              60%
            </button>
            {" "}
            <button type="button" data-zoom="0.85" className="on">
              85%
            </button>
            {" "}
            <button type="button" data-zoom="1">
              100%
            </button>
            {" "}
          </div>
          {" "}
          <div className="docp-acts">
            {" "}
            <button type="button" className="ds-btn btn-p ds-btn-sm btn-full" id="docp-print">
              Print or save as PDF
            </button>
            {" "}
          </div>
          {" "}
          <p className="docp-note">
            {" "}What you see is the document. There is no separate print version — printing uses these same sheets at A4, which is why the preview is drawn in points.{" "}
          </p>
          {" "}
        </aside>
        {" "}
        <main className="docp-main">
          {" "}
          <div className="docp-bar doc-noprint">
            {" "}
            <div>
              {" "}
              <h1 id="docp-title">
                Invoice
              </h1>
              {" "}
              <p id="docp-sub">
                The canonical document. Every other template is a configuration of it.
              </p>
              {" "}
            </div>
            {" "}
            <div className="docp-count" id="docp-count">
            </div>
            {" "}
          </div>
          {" "}
          <div className="doc-stage" id="docp-stage">
          </div>
          {" "}
        </main>
        {" "}
      </div>
      {" "}
    </>
  );
}
