// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/how-it-works.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";
import DsPromoLive from "../DsPromoLive.jsx";

export default function DsHowItWorks() {
  const DsPromoSlot = <DsPromoLive />;
  return (
    <>
      <header className="phero">
        {" "}
        <div className="phero-bg">
          <img src="/ds/hd-cad.jpg" alt="" />
        </div>
        {" "}
        <div className="phero-in">
          {" "}
          <span className="host">
            How ADLM works
          </span>
          {" "}
          <h1>
            {" "}
            <span className="w" style={{ "--i": "0" }}>
              One
            </span>
            {" "}
            <span className="w" style={{ "--i": "1" }}>
              account.
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "2" }}>
              Every
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "3" }}>
              product.
            </span>
            {" "}
          </h1>
          {" "}
          <p className="ds-lede">
            What you actually get when you buy, and how it reaches the machines you work on.
          </p>
          {" "}
          <div className="hero-cta">
            {" "}
            <Link to="/products" data-ds-page="products" className="ds-btn btn-p">
              See the toolkit
            </Link>
            {" "}
            <Link to="/pricing" data-ds-page="pricing" className="ds-btn btn-o">
              See pricing
            </Link>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              The four steps
            </span>
            {" "}
            <h2>
              From buying it{" "}
              <span className="tone">
                to measuring with it
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="steps">
            {" "}
            <article className="ds-card tilt rise">
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-user" />
                </svg>
              </div>
              {" "}
              <span className="step-n">
                Step 01
              </span>
              <h4 style={{ marginTop: "10px" }}>
                Create your ADLM account
              </h4>
              {" "}
              <p>
                One identity for every product, your subscriptions, and your team's seats.
              </p>
            </article>
            {" "}
            <article className="ds-card tilt rise">
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-down" />
                </svg>
              </div>
              {" "}
              <span className="step-n">
                Step 02
              </span>
              <h4 style={{ marginTop: "10px" }}>
                Install from the Hub
              </h4>
              {" "}
              <p>
                The Installer Hub puts everything you own on the machine and keeps it updated.
              </p>
            </article>
            {" "}
            <article className="ds-card tilt rise">
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-screen" />
                </svg>
              </div>
              {" "}
              <span className="step-n">
                Step 03
              </span>
              <h4 style={{ marginTop: "10px" }}>
                Work inside your CAD tools
              </h4>
              {" "}
              <p>
                QUIV, HERON and Revit MEP dock into Revit and PlanSwift. RateGen runs on its own.
              </p>
            </article>
            {" "}
            <article className="ds-card tilt rise">
              <div className="ico ico-a">
                <svg viewBox="0 0 24 24">
                  <use href="#i-phone" />
                </svg>
              </div>
              {" "}
              <span className="step-n">
                Step 04
              </span>
              <h4 style={{ marginTop: "10px" }}>
                Carry the cost work with you
              </h4>
              {" "}
              <p>
                Anything that doesn't need the drawing moves to your phone.
              </p>
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <div className="frame frame-soft">
        {" "}
        <section className="sec band-dark amb">
          {" "}
          <div className="shell">
            {" "}
            <div className="split">
              {" "}
              <div className="rise">
                {" "}
                <span className="eyebrow">
                  The Installer Hub
                </span>
                {" "}
                <h2>
                  One app that{" "}
                  <span className="grad">
                    keeps you current
                  </span>
                </h2>
                {" "}
                <p className="ds-lede" style={{ marginTop: "18px" }}>
                  Sign in once and the Hub shows every product your subscription covers, installs it, and updates it when a release lands. No chasing download links.
                </p>
                {" "}
                <ul className="ticks">
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Installs and updates every product you own
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Shows exactly what your subscription covers
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Free 21-page user guide, no sign-in needed
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Where you go first when something breaks
                  </li>
                  {" "}
                </ul>
                {" "}
              </div>
              {" "}
              <div className="split-m rise">
                {" "}
                <div className="ds-card tilt orbit-card">
                  {" "}
                  <div className="orbit" aria-hidden="true">
                    {" "}
                    <span className="orb-ring orb-r1">
                    </span>
                    {" "}
                    <span className="orb-ring orb-r2">
                    </span>
                    {" "}
                    <span className="orb-ring orb-r3">
                    </span>
                    {" "}
                    <span className="orb-ring orb-r4">
                    </span>
                    {" "}
                    <span className="orb-ring orb-r5">
                    </span>
                    {" "}
                    <span className="orb-ring orb-r6">
                    </span>
                    {" "}
                    <span className="orb-core">
                      <img src="/ds/mark.svg" alt="" />
                    </span>
                    {" "}
                    <span className="orb-i" style={{ "--r": "100", "--dur": "30s", "--dl": "0.00s", "--a": "0deg" }}>
                      <span className="orb-o">
                        <img src="/ds/ic-quiv.png" alt="" />
                      </span>
                    </span>
                    {" "}
                    <span className="orb-i" style={{ "--r": "120", "--dur": "36s", "--dl": "-14.50s", "--a": "145deg" }}>
                      <span className="orb-o">
                        <img src="/ds/ic-rategen.png" alt="" />
                      </span>
                    </span>
                    {" "}
                    <span className="orb-i" style={{ "--r": "141", "--dur": "42s", "--dl": "-29.17s", "--a": "250deg" }}>
                      <span className="orb-o">
                        <img src="/ds/ic-heron.png" alt="" />
                      </span>
                    </span>
                    {" "}
                    <span className="orb-i" style={{ "--r": "162", "--dur": "48s", "--dl": "-6.00s", "--a": "45deg" }}>
                      <span className="orb-o">
                        <img src="/ds/ic-timepro.png" alt="" />
                      </span>
                    </span>
                    {" "}
                    <span className="orb-i" style={{ "--r": "183", "--dur": "54s", "--dl": "-28.50s", "--a": "190deg" }}>
                      <span className="orb-o">
                        <img src="/ds/ic-mep.png" alt="" />
                      </span>
                    </span>
                    {" "}
                    <span className="orb-i" style={{ "--r": "204", "--dur": "60s", "--dl": "-50.83s", "--a": "305deg" }}>
                      <span className="orb-o">
                        <img src="/ds/ic-civiq.png" alt="" />
                      </span>
                    </span>
                    {" "}
                  </div>
                  {" "}
                  <h4>
                    One account, every tool
                  </h4>
                  {" "}
                  <p>
                    Your ADLM sign-in sits at the centre. Everything your subscription covers, six products and counting, installs, updates and licenses itself from it.
                  </p>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </div>
      {" "}
      <section className="sec-half blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "36px" }}>
            {" "}
            <span className="eyebrow">
              What syncs
            </span>
            {" "}
            <h2>
              Change machine,{" "}
              <span className="tone">
                not method
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="bento bento-4">
            {" "}
            <article className="bento-c pal-hv pal-deep tilt rise">
              <img className="picon picon-lg" src="/ds/ic-rategen.png" alt="" aria-hidden="true" />
              {" "}
              <div className="bento-body">
                <h4>
                  Your rate library
                </h4>
                <p>
                  One library, every tool, every machine.
                </p>
              </div>
            </article>
            {" "}
            <article className="bento-c pal-hv pal-light tilt rise">
              <img className="picon picon-lg" src="/ds/ic-quiv.png" alt="" aria-hidden="true" />
              {" "}
              <div className="bento-body">
                <h4>
                  Projects &amp; takeoffs
                </h4>
                <p>
                  Open the same project wherever you sign in.
                </p>
              </div>
            </article>
            {" "}
            <article className="bento-c pal-hv pal-grad tilt rise">
              <img className="picon picon-lg" src="/ds/ic-heron.png" alt="" aria-hidden="true" />
              {" "}
              <div className="bento-body">
                <h4>
                  Budgets &amp; valuations
                </h4>
                <p>
                  Priced work stays attached to the project.
                </p>
              </div>
            </article>
            {" "}
            <article className="bento-c pal-hv pal-orange tilt rise">
              <img className="picon picon-lg" src="/ds/ic-civiq.png" alt="" aria-hidden="true" />
              {" "}
              <div className="bento-body">
                <h4>
                  Invoices &amp; licences
                </h4>
                <p>
                  Billing history and seat assignment in one account.
                </p>
              </div>
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}{DsPromoSlot}{" "}
      <section className="cta">
        {" "}
        <div className="cta-bp">
        </div>
        <div className="cta-dots">
        </div>
        <div className="cta-g">
        </div>
        {" "}
        <h2>
          Ready to{" "}
          <span className="grad">
            set it up?
          </span>
        </h2>
        {" "}
        <p className="ds-lede">
          We'll walk your team through the account, the Hub and the first project.
        </p>
        {" "}
        <div className="hero-cta">
          {" "}
          <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
            Book a demo
          </Link>
          {" "}
          <Link to="/pricing" data-ds-page="pricing" className="ds-btn btn-o">
            See pricing
          </Link>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
