// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/learn.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";
import DsPromoLive from "../DsPromoLive.jsx";

export default function DsLearnPage({ d }) {
  const DsPromoSlot = <DsPromoLive />;
  return (
    <>
      <header className="phero">
        {" "}
        <div className="phero-bg">
          <img src="/ds/ln-analysts.jpg" alt="" />
        </div>
        {" "}
        <div className="phero-in">
          {" "}
          <span className="host">
            ADLM Learn
          </span>
          {" "}
          <h1>
            {" "}
            <span className="w" style={{ "--i": "0" }}>
              Tools
            </span>
            {" "}
            <span className="w" style={{ "--i": "1" }}>
              are
            </span>
            {" "}
            <span className="w" style={{ "--i": "2" }}>
              half
            </span>
            {" "}
            <span className="w" style={{ "--i": "3" }}>
              of
            </span>
            {" "}
            <span className="w" style={{ "--i": "4" }}>
              it.
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "5" }}>
              We
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "6" }}>
              teach
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "7" }}>
              the
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "8" }}>
              rest.
            </span>
            {" "}
          </h1>
          {" "}
          <p className="ds-lede">
            Certificated courses, a free lesson library, and hands-on training delivered to firms, NIQS chapters and universities.
          </p>
          {" "}
          <div className="hero-cta">
            {" "}
            <a href="#courses" className="ds-btn btn-p">
              Browse courses
            </a>
            {" "}
            <a href="#lessons" className="ds-btn btn-o">
              Free lessons
            </a>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <section className="sec" id="courses">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              Certificated courses
            </span>
            {" "}
            <h2>
              Six weeks,{" "}
              <span className="tone">
                self-paced, assessed
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              Structured roadmaps that end in a capstone project and a certificate — not a folder of videos.
            </p>
            {" "}
          </div>
          {" "}
          <div className="pgrid pgrid-4">
            {" "}
            <article className="pcard2 pc-ico pal-deep tilt rise">
              {" "}
              <div className="pcard2-body">
                {" "}
                <img className="picon" src="/ds/ic-quiv.png" alt="" width="66" height="66" />
                {" "}
                <span className="host">
                  Certificated · 6 weeks
                </span>
                {" "}
                <h3>
                  BIM for Building Works
                </h3>
                {" "}
                <p className="blurb">
                  Architectural and structural, from 3D through to 5D cost.
                </p>
                {" "}
                <div className="amt">
                  {d.bimbld.yearly}
                  <small>
                    {" "}/ yr
                  </small>
                </div>
                {" "}
                <p className="inst" style={{ marginTop: "10px" }}>
                  100% online · Google Classroom · self-paced
                </p>
                {" "}
                <ul>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Revit, Navisworks, MS Project
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Weekly assessments and practical tasks
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Capstone BIM Manager demo project
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Certificate of completion
                  </li>
                  {" "}
                </ul>
                {" "}
                <Link to="/learn#courses" data-ds-page="learn" className="ds-btn btn-p btn-full">
                  View course
                </Link>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="pcard2 pc-ico pal-grad feat tilt rise">
              {" "}
              <span className="pc-tag">
                Most enrolled
              </span>
              {" "}
              <div className="pcard2-body">
                {" "}
                <img className="picon" src="/ds/ic-mep.png" alt="" width="66" height="66" />
                {" "}
                <span className="host">
                  Certificated · 6 weeks
                </span>
                {" "}
                <h3>
                  BIM for MEP &amp; HVAC
                </h3>
                {" "}
                <p className="blurb">
                  Services, coordination, 4D/5D and reporting.
                </p>
                {" "}
                <div className="amt">
                  {d.bimmep.yearly}
                  <small>
                    {" "}/ yr
                  </small>
                </div>
                {" "}
                <p className="inst" style={{ marginTop: "10px" }}>
                  100% online · Google Classroom · self-paced
                </p>
                {" "}
                <ul>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Revit MEP + clash detection in Navisworks
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    4D TimeLiner linked to MS Project
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Power BI dashboards for cost tracking
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Top three projects featured on ADLM channels
                  </li>
                  {" "}
                </ul>
                {" "}
                <Link to="/learn#courses" data-ds-page="learn" className="ds-btn btn-p btn-full">
                  View course
                </Link>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="pcard2 pc-ico pal-orange tilt rise">
              {" "}
              <div className="pcard2-body">
                {" "}
                <span className="pc-mark">
                  <img src="/ds/mark.svg" alt="" />
                </span>
                {" "}
                <span className="host">
                  In your office
                </span>
                {" "}
                <h3>
                  On-site training
                </h3>
                {" "}
                <p className="blurb">
                  An instructor comes to your team.
                </p>
                {" "}
                <div className="amt">
                  On enquiry
                </div>
                {" "}
                <p className="inst" style={{ marginTop: "10px" }}>
                  Priced on cohort size and location
                </p>
                {" "}
                <ul>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Tailored to the tools you actually bought
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Hands-on, on your own projects
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    30 events delivered to date
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    NIQS chapters, universities and firms
                  </li>
                  {" "}
                </ul>
                {" "}
                <Link to="/contact" data-ds-page="contact" className="ds-btn btn-o btn-full">
                  Request a quote
                </Link>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="pcard2 pc-ico pal-light tilt rise" id="course-4">
              {" "}
              <div className="pcard2-body">
                {" "}
                <img className="picon" src="/ds/ic-rategen.png" alt="" width="66" height="66" />
                {" "}
                <span className="host">
                  Certificated · 4 weeks
                </span>
                {" "}
                <h3>
                  Rates &amp; 2D Takeoff
                </h3>
                {" "}
                <p className="blurb">
                  Measure from drawings, then build a rate you can defend.
                </p>
                {" "}
                <div className="amt">
                  ₦85,000
                  <small>
                    {" "}/ yr
                  </small>
                </div>
                {" "}
                <p className="inst" style={{ marginTop: "10px" }}>
                  100% online · Google Classroom · self-paced
                </p>
                {" "}
                <ul>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    HERON 2D takeoff on PlanSwift
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    RateGen build-ups from first principles
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Materials, waste and labour output
                  </li>
                  {" "}
                  <li>
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    Certificate of completion
                  </li>
                  {" "}
                </ul>
                {" "}
                <Link to="/learn#courses" data-ds-page="learn" className="ds-btn btn-p btn-full">
                  View course
                </Link>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <div className="frame frame-soft">
        {" "}
        <section className="sec band-dark amb" id="certificate">
          {" "}
          <div className="shell">
            {" "}
            <div className="wcard wcard-dark rise">
              {" "}
              <div className="wcard-copy">
                {" "}
                <span className="host">
                  At the end of the six weeks
                </span>
                {" "}
                <span className="ico ico-a" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-doc" />
                  </svg>
                </span>
                {" "}
                <h3>
                  You finish with a certificate, not a folder of videos
                </h3>
                {" "}
                <p>
                  Every course ends in a capstone you actually build — a coordinated model, a priced bill, a programme. Pass the assessment and your certificate is issued to your ADLM account, with your name on it and something real to show behind it.
                </p>
                {" "}
                <a href="#courses" className="ds-btn btn-p ds-btn-sm">
                  Browse the courses{" "}
                  <svg viewBox="0 0 24 24">
                    <use href="#i-arrow" />
                  </svg>
                </a>
                {" "}
              </div>
              {" "}
              <div className="wcard-art">
                <img src="/ds/hd-team.jpg" alt="" loading="lazy" />
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </div>
      {" "}
      <section className="sec" id="lessons">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise">
            {" "}
            <span className="eyebrow">
              Free lessons
            </span>
            {" "}
            <h2>
              Watch the whole library,{" "}
              <span className="grad">
                no sign-in
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              Short, specific walkthroughs on the things people actually get stuck on.
            </p>
            {" "}
          </div>
          {" "}
          <div className="filters rise" id="lesson-filters">
            {" "}
            <button type="button" className="on" data-f="all">
              All
            </button>
            {" "}
            <button type="button" data-f="Revit">
              Revit
            </button>
            {" "}
            <button type="button" data-f="PlanSwift">
              PlanSwift
            </button>
            {" "}
            <button type="button" data-f="Rates">
              Rates
            </button>
            {" "}
            <button type="button" data-f="Getting started">
              Getting started
            </button>
            {" "}
          </div>
          {" "}
          <div className="lgrid" id="lesson-grid">
            {" "}
            <article className="ltile" data-cat="Revit">
              {" "}
              <img src="/ds/ls-frame.jpg" alt="" />
              {" "}
              <div className="lt">
                {" "}
                <span className="playbtn">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-play" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow">
                  Revit · 12:41
                </span>
                {" "}
                <h4>
                  Master architectural quantity takeoff
                </h4>
                {" "}
                <p>
                  Walls, windows, doors and more, measured element by element.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="ltile" data-cat="PlanSwift">
              {" "}
              <img src="/ds/ls-steel.jpg" alt="" />
              {" "}
              <div className="lt">
                {" "}
                <span className="playbtn">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-play" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow">
                  PlanSwift · 11:27
                </span>
                {" "}
                <h4>
                  Foundation takeoff tutorial
                </h4>
                {" "}
                <p>
                  Preparing a bill of quantities from a flat foundation drawing.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="ltile" data-cat="Rates">
              {" "}
              <img src="/ds/bg-rategen.jpg" alt="" />
              {" "}
              <div className="lt">
                {" "}
                <span className="playbtn">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-play" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow">
                  Rates · 14:20
                </span>
                {" "}
                <h4>
                  Building a defensible rate
                </h4>
                {" "}
                <p>
                  Materials, waste and labour output in RateGen.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="ltile" data-cat="Revit">
              {" "}
              <img src="/ds/bg-quiv.jpg" alt="" />
              {" "}
              <div className="lt">
                {" "}
                <span className="playbtn">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-play" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow">
                  Revit · 09:18
                </span>
                {" "}
                <h4>
                  Columns, beams and slabs
                </h4>
                {" "}
                <p>
                  Simplify structural takeoff with the ADLM Revit plugin.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="ltile" data-cat="PlanSwift">
              {" "}
              <img src="/ds/bg-heron.jpg" alt="" />
              {" "}
              <div className="lt">
                {" "}
                <span className="playbtn">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-play" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow">
                  PlanSwift · 10:44
                </span>
                {" "}
                <h4>
                  Frame takeoff tutorial
                </h4>
                {" "}
                <p>
                  Columns, beams and slabs measured from 2D sheets.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="ltile" data-cat="Getting started">
              {" "}
              <img src="/ds/bg-timepro.jpg" alt="" />
              {" "}
              <div className="lt">
                {" "}
                <span className="playbtn">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-play" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow">
                  Getting started · 06:35
                </span>
                {" "}
                <h4>
                  Installing with the Hub
                </h4>
                {" "}
                <p>
                  Signing in, installing your products and applying updates.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="ltile" data-cat="Revit">
              {" "}
              <img src="/ds/ls-city.jpg" alt="" />
              {" "}
              <div className="lt">
                {" "}
                <span className="playbtn">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-play" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow">
                  Revit · 15:02
                </span>
                {" "}
                <h4>
                  Generate a BoQ in minutes
                </h4>
                {" "}
                <p>
                  From a coordinated model to a priced bill of quantities.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="ltile" data-cat="PlanSwift">
              {" "}
              <img src="/ds/ls-survey.jpg" alt="" />
              {" "}
              <div className="lt">
                {" "}
                <span className="playbtn">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-play" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow">
                  PlanSwift · 13:09
                </span>
                {" "}
                <h4>
                  Walls, windows and doors
                </h4>
                {" "}
                <p>
                  Measuring openings correctly so the bill nets off.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="ltile" data-cat="PlanSwift">
              {" "}
              <img src="/ds/ls-crane.jpg" alt="" />
              {" "}
              <div className="lt">
                {" "}
                <span className="playbtn">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-play" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow">
                  PlanSwift · 08:52
                </span>
                {" "}
                <h4>
                  Roof works
                </h4>
                {" "}
                <p>
                  Pitched and flat roof coverings, measured to SMM.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
          <div className="lmore">
            {" "}
            <button type="button" className="ds-btn btn-o" id="more-lessons">
              Show more lessons
            </button>
            {" "}
            <span className="lcount" id="lesson-count">
            </span>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec" id="events">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              Events &amp; training
            </span>
            {" "}
            <h2>
              Thirty events,{" "}
              <span className="tone">
                3,100+ trained
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              Conferences, chapter workshops, university sessions and in-office programmes since 2022. Six are featured below, and every one of the thirty is listed underneath.
            </p>
            {" "}
          </div>
          {" "}
          <div className="gal">
            {" "}
            <article className="gcard tilt rise">
              {" "}
              <div className="gcard-bg">
                <img src="/ds/ev3.jpg" alt="The Big 5 Construct" />
              </div>
              {" "}
              <span className="host">
                Conference · Lagos
              </span>
              {" "}
              <h3>
                The Big 5 Construct
              </h3>
              {" "}
              <p>
                Cost versus sustainability in building projects — a panel on lifecycle cost and BIM-driven takeoff.
              </p>
              {" "}
              <p className="gprice">
                <b>
                  1,480
                </b>
                {" "}attendees
              </p>
              {" "}
            </article>
            {" "}
            <article className="gcard tilt rise">
              {" "}
              <div className="gcard-bg">
                <img src="/ds/ev5.jpg" alt="NIQS Rivers" />
              </div>
              {" "}
              <span className="host">
                Workshop · Rivers State
              </span>
              {" "}
              <h3>
                NIQS Rivers
              </h3>
              {" "}
              <p>
                Three days on harnessing AI for the future of quantity surveying and cost estimation.
              </p>
              {" "}
              <p className="gprice">
                <b>
                  200
                </b>
                {" "}attendees
              </p>
              {" "}
            </article>
            {" "}
            <article className="gcard tilt rise">
              {" "}
              <div className="gcard-bg">
                <img src="/ds/ev4.jpg" alt="Practical 4D &amp; 5D" />
              </div>
              {" "}
              <span className="host">
                In-office · Lagos
              </span>
              {" "}
              <h3>
                Practical 4D &amp; 5D
              </h3>
              {" "}
              <p>
                Applying BIM to real project workflows for time and cost management.
              </p>
              {" "}
              <p className="gprice">
                <b>
                  Hands-on
                </b>
                {" "}session
              </p>
              {" "}
            </article>
            {" "}
            <article className="gcard tilt rise">
              {" "}
              <div className="gcard-bg">
                <img src="/ds/ev6.jpg" alt="Driving innovation in QS" />
              </div>
              {" "}
              <span className="host">
                Conference · Akwa Ibom
              </span>
              {" "}
              <h3>
                Driving innovation in QS
              </h3>
              {" "}
              <p>
                How emerging tools and forward-thinking practice are reshaping the profession.
              </p>
              {" "}
              <p className="gprice">
                <b>
                  248
                </b>
                {" "}attendees
              </p>
              {" "}
            </article>
            {" "}
            <article className="gcard tilt rise">
              {" "}
              <div className="gcard-bg">
                <img src="/ds/ev2.jpg" alt="NIQS Ogun · BESMM4R &amp; ICMS3" />
              </div>
              {" "}
              <span className="host">
                Workshop · Ogun State
              </span>
              {" "}
              <h3>
                NIQS Ogun · BESMM4R &amp; ICMS3
              </h3>
              {" "}
              <p>
                Two days upskilling surveyors on BIM across 1D to 8D, with ICMS3 cost reporting.
              </p>
              {" "}
              <p className="gprice">
                <b>
                  95
                </b>
                {" "}attendees
              </p>
              {" "}
            </article>
            {" "}
            <article className="gcard tilt rise">
              {" "}
              <div className="gcard-bg">
                <img src="/ds/ev1.jpg" alt="Digital Frontiers, NIQS Foundation" />
              </div>
              {" "}
              <span className="host">
                Hybrid · Abuja
              </span>
              {" "}
              <h3>
                Digital Frontiers, NIQS Foundation
              </h3>
              {" "}
              <p>
                A two-day leadership programme on BIM and AI, supported by the Aubrey Barker Fund.
              </p>
              {" "}
              <p className="gprice">
                <b>
                  74
                </b>
                {" "}attendees
              </p>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
          <div className="evstats rise">
            {" "}
            <div className="evstat">
              <b>
                30
              </b>
              <span>
                Events delivered
              </span>
            </div>
            {" "}
            <div className="evstat">
              <b>
                12
              </b>
              <span>
                Online sessions
              </span>
            </div>
            {" "}
            <div className="evstat">
              <b>
                7
              </b>
              <span>
                In-office trainings
              </span>
            </div>
            {" "}
            <div className="evstat">
              <b>
                11
              </b>
              <span>
                Conferences &amp; workshops
              </span>
            </div>
            {" "}
            <div className="evstat">
              <b>
                3,103
              </b>
              <span>
                People in the room
              </span>
            </div>
            {" "}
          </div>
          {" "}
          <div className="filters rise" id="ev-filters">
            {" "}
            <button type="button" className="on" data-f="all">
              All 30
            </button>
            {" "}
            <button type="button" data-f="online">
              Online
            </button>
            {" "}
            <button type="button" data-f="office">
              In-office
            </button>
            {" "}
            <button type="button" data-f="conference">
              Conferences
            </button>
            {" "}
          </div>
          {" "}
          <ul className="evlist rise" id="ev-list">
            {" "}
            <li className="evhead">
              {" "}
              <span>
                Date
              </span>
              <span>
                Kind
              </span>
              <span>
                Session
              </span>
              <span>
                Where
              </span>
              <span>
                Attended
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="online">
              {" "}
              <span className="ev-when">
                Jan 2026
              </span>
              {" "}
              <span className="ev-tag ev-online">
                Online
              </span>
              {" "}
              <span className="ev-title">
                Digital QS &amp; Future-Proof Skills Session
              </span>
              {" "}
              <span className="ev-loc">
                Google Meet
              </span>
              {" "}
              <span className="ev-att">
                32
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="office">
              {" "}
              <span className="ev-when">
                Jan 2026
              </span>
              {" "}
              <span className="ev-tag ev-office">
                In-office
              </span>
              {" "}
              <span className="ev-title">
                Hands-on training at Joseph Ayo Babalola University
              </span>
              {" "}
              <span className="ev-loc">
                Ikeji-Arakeji, Osun State
              </span>
              {" "}
              <span className="ev-att">
                35
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="online">
              {" "}
              <span className="ev-when">
                Oct 2025
              </span>
              {" "}
              <span className="ev-tag ev-online">
                Online
              </span>
              {" "}
              <span className="ev-title">
                Numbers That Build — planning with Microsoft Project
              </span>
              {" "}
              <span className="ev-loc">
                Nigeria / Tanzania
              </span>
              {" "}
              <span className="ev-att">
                70
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="conference">
              {" "}
              <span className="ev-when">
                Sep 2025
              </span>
              {" "}
              <span className="ev-tag ev-conference">
                Conference
              </span>
              {" "}
              <span className="ev-title">
                Cost vs Sustainability — The Big 5 Construct Nigeria
              </span>
              {" "}
              <span className="ev-loc">
                Landmark Centre, Lagos
              </span>
              {" "}
              <span className="ev-att">
                1,480
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="office">
              {" "}
              <span className="ev-when">
                Sep 2025
              </span>
              {" "}
              <span className="ev-tag ev-office">
                In-office
              </span>
              {" "}
              <span className="ev-title">
                Practical 4D &amp; 5D applications for project delivery
              </span>
              {" "}
              <span className="ev-loc">
                Construworth Consult, Lagos
              </span>
              {" "}
              <span className="ev-att">
                —
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="online">
              {" "}
              <span className="ev-when">
                Aug 2025
              </span>
              {" "}
              <span className="ev-tag ev-online">
                Online
              </span>
              {" "}
              <span className="ev-title">
                BIM training for MEP &amp; HVAC cost estimators
              </span>
              {" "}
              <span className="ev-loc">
                Google Meet
              </span>
              {" "}
              <span className="ev-att">
                50
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="conference">
              {" "}
              <span className="ev-when">
                Aug 2025
              </span>
              {" "}
              <span className="ev-tag ev-conference">
                Conference
              </span>
              {" "}
              <span className="ev-title">
                Digital Frontiers in Quantity Surveying Leadership
              </span>
              {" "}
              <span className="ev-loc">
                Mabushi, Abuja
              </span>
              {" "}
              <span className="ev-att">
                74
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="conference">
              {" "}
              <span className="ev-when">
                Jun 2025
              </span>
              {" "}
              <span className="ev-tag ev-conference">
                Conference
              </span>
              {" "}
              <span className="ev-title">
                Harnessing AI for the future of quantity surveying
              </span>
              {" "}
              <span className="ev-loc">
                Rivers State University
              </span>
              {" "}
              <span className="ev-att">
                59
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="conference">
              {" "}
              <span className="ev-when">
                Jun 2025
              </span>
              {" "}
              <span className="ev-tag ev-conference">
                Conference
              </span>
              {" "}
              <span className="ev-title">
                Three-day workshop — NIQS Rivers State Chapter
              </span>
              {" "}
              <span className="ev-loc">
                Amphitheatre, Rivers State University
              </span>
              {" "}
              <span className="ev-att">
                200
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="online">
              {" "}
              <span className="ev-when">
                Apr 2025
              </span>
              {" "}
              <span className="ev-tag ev-online">
                Online
              </span>
              {" "}
              <span className="ev-title">
                BIM training for the Class of 2025
              </span>
              {" "}
              <span className="ev-loc">
                Google Meet
              </span>
              {" "}
              <span className="ev-att">
                42
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="conference">
              {" "}
              <span className="ev-when">
                Nov 2024
              </span>
              {" "}
              <span className="ev-tag ev-conference">
                Conference
              </span>
              {" "}
              <span className="ev-title">
                ConTech Nigeria 2024 — AEC technology event
              </span>
              {" "}
              <span className="ev-loc">
                Lagos
              </span>
              {" "}
              <span className="ev-att">
                145
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="conference">
              {" "}
              <span className="ev-when">
                Oct 2024
              </span>
              {" "}
              <span className="ev-tag ev-conference">
                Conference
              </span>
              {" "}
              <span className="ev-title">
                Driving innovation in quantity surveying
              </span>
              {" "}
              <span className="ev-loc">
                Akwa Ibom
              </span>
              {" "}
              <span className="ev-att">
                248
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="conference">
              {" "}
              <span className="ev-when">
                Oct 2024
              </span>
              {" "}
              <span className="ev-tag ev-conference">
                Conference
              </span>
              {" "}
              <span className="ev-title">
                Upskilling quantity surveyors with BIM tools
              </span>
              {" "}
              <span className="ev-loc">
                Ogun State
              </span>
              {" "}
              <span className="ev-att">
                95
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="conference">
              {" "}
              <span className="ev-when">
                Sep 2024
              </span>
              {" "}
              <span className="ev-tag ev-conference">
                Conference
              </span>
              {" "}
              <span className="ev-title">
                Tech, innovation and startups in AEC
              </span>
              {" "}
              <span className="ev-loc">
                Landmark Centre, Lagos
              </span>
              {" "}
              <span className="ev-att">
                145
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="conference">
              {" "}
              <span className="ev-when">
                Aug 2024
              </span>
              {" "}
              <span className="ev-tag ev-conference">
                Conference
              </span>
              {" "}
              <span className="ev-title">
                Young Builders, Big Impact
              </span>
              {" "}
              <span className="ev-loc">
                Akwa Ibom
              </span>
              {" "}
              <span className="ev-att">
                120
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="conference">
              {" "}
              <span className="ev-when">
                Jun 2024
              </span>
              {" "}
              <span className="ev-tag ev-conference">
                Conference
              </span>
              {" "}
              <span className="ev-title">
                NIQS Cross River Chapter development workshop
              </span>
              {" "}
              <span className="ev-loc">
                Cross River
              </span>
              {" "}
              <span className="ev-att">
                83
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="online">
              {" "}
              <span className="ev-when">
                Jun 2024
              </span>
              {" "}
              <span className="ev-tag ev-online">
                Online
              </span>
              {" "}
              <span className="ev-title">
                AI and BIM for MEP and HVAC works
              </span>
              {" "}
              <span className="ev-loc">
                Google Meet
              </span>
              {" "}
              <span className="ev-att">
                52
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="online">
              {" "}
              <span className="ev-when">
                May 2024
              </span>
              {" "}
              <span className="ev-tag ev-online">
                Online
              </span>
              {" "}
              <span className="ev-title">
                Kick-starting a tech career as an AEC professional
              </span>
              {" "}
              <span className="ev-loc">
                LinkedIn Live
              </span>
              {" "}
              <span className="ev-att">
                53
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="office">
              {" "}
              <span className="ev-when">
                May 2024
              </span>
              {" "}
              <span className="ev-tag ev-office">
                In-office
              </span>
              {" "}
              <span className="ev-title">
                BIM training for quantity surveying professionals
              </span>
              {" "}
              <span className="ev-loc">
                Lagos Free Zone
              </span>
              {" "}
              <span className="ev-att">
                —
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="online">
              {" "}
              <span className="ev-when">
                Feb 2024
              </span>
              {" "}
              <span className="ev-tag ev-online">
                Online
              </span>
              {" "}
              <span className="ev-title">
                Construction management &amp; project planning for undergraduates
              </span>
              {" "}
              <span className="ev-loc">
                Google Meet
              </span>
              {" "}
              <span className="ev-att">
                25
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="online">
              {" "}
              <span className="ev-when">
                Feb 2024
              </span>
              {" "}
              <span className="ev-tag ev-online">
                Online
              </span>
              {" "}
              <span className="ev-title">
                Mastering BIM &amp; AI in quantity surveying
              </span>
              {" "}
              <span className="ev-loc">
                Google Meet
              </span>
              {" "}
              <span className="ev-att">
                26
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="online">
              {" "}
              <span className="ev-when">
                Jun 2023
              </span>
              {" "}
              <span className="ev-tag ev-online">
                Online
              </span>
              {" "}
              <span className="ev-title">
                Transferable skills for career growth in quantity surveying
              </span>
              {" "}
              <span className="ev-loc">
                Google Meet
              </span>
              {" "}
              <span className="ev-att">
                25
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="online">
              {" "}
              <span className="ev-when">
                Jun 2023
              </span>
              {" "}
              <span className="ev-tag ev-online">
                Online
              </span>
              {" "}
              <span className="ev-title">
                Work readiness &amp; engineering professional skills
              </span>
              {" "}
              <span className="ev-loc">
                Google Meet
              </span>
              {" "}
              <span className="ev-att">
                14
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="office">
              {" "}
              <span className="ev-when">
                May 2023
              </span>
              {" "}
              <span className="ev-tag ev-office">
                In-office
              </span>
              {" "}
              <span className="ev-title">
                BIM in practical quantity surveying and project workflows
              </span>
              {" "}
              <span className="ev-loc">
                Abuja
              </span>
              {" "}
              <span className="ev-att">
                —
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="office">
              {" "}
              <span className="ev-when">
                Dec 2022
              </span>
              {" "}
              <span className="ev-tag ev-office">
                In-office
              </span>
              {" "}
              <span className="ev-title">
                BIM hybrid training on HVAC works
              </span>
              {" "}
              <span className="ev-loc">
                Lagos
              </span>
              {" "}
              <span className="ev-att">
                12
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="conference">
              {" "}
              <span className="ev-when">
                Nov 2022
              </span>
              {" "}
              <span className="ev-tag ev-conference">
                Conference
              </span>
              {" "}
              <span className="ev-title">
                Impact of BIM technology on the construction industry
              </span>
              {" "}
              <span className="ev-loc">
                Yaba College of Technology, Lagos
              </span>
              {" "}
              <span className="ev-att">
                —
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="online">
              {" "}
              <span className="ev-when">
                Oct 2022
              </span>
              {" "}
              <span className="ev-tag ev-online">
                Online
              </span>
              {" "}
              <span className="ev-title">
                Understanding BIM technology in the construction industry
              </span>
              {" "}
              <span className="ev-loc">
                Google Meet
              </span>
              {" "}
              <span className="ev-att">
                —
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="office">
              {" "}
              <span className="ev-when">
                Sep 2022
              </span>
              {" "}
              <span className="ev-tag ev-office">
                In-office
              </span>
              {" "}
              <span className="ev-title">
                BIM training for the Federal Airport Authority
              </span>
              {" "}
              <span className="ev-loc">
                Nigerian Port Authority, Lagos
              </span>
              {" "}
              <span className="ev-att">
                —
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="office">
              {" "}
              <span className="ev-when">
                Aug 2022
              </span>
              {" "}
              <span className="ev-tag ev-office">
                In-office
              </span>
              {" "}
              <span className="ev-title">
                Three-day 5D BIM training for QS software use
              </span>
              {" "}
              <span className="ev-loc">
                ITV, Lagos
              </span>
              {" "}
              <span className="ev-att">
                —
              </span>
              {" "}
            </li>
            {" "}
            <li className="evrow" data-cat="online">
              {" "}
              <span className="ev-when">
                Jun 2022
              </span>
              {" "}
              <span className="ev-tag ev-online">
                Online
              </span>
              {" "}
              <span className="ev-title">
                Freelancing with BIM &amp; project work skills
              </span>
              {" "}
              <span className="ev-loc">
                Google Meet
              </span>
              {" "}
              <span className="ev-att">
                —
              </span>
              {" "}
            </li>
            {" "}
          </ul>
          {" "}
          <p className="small" style={{ marginTop: "18px" }}>
            Attendance is taken from our own event records. A dash means the headcount was not recorded.
          </p>
          {" "}
          <div style={{ textAlign: "center", marginTop: "30px" }}>
            {" "}
            <Link to="/testimonials" data-ds-page="customers" className="ds-btn btn-o">
              See who we've trained{" "}
              <svg viewBox="0 0 24 24">
                <use href="#i-arrow" />
              </svg>
            </Link>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half alt amb blend" id="guides">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise" style={{ marginBottom: "36px" }}>
            {" "}
            <span className="eyebrow">
              Guides &amp; docs
            </span>
            {" "}
            <h2>
              Free PDF user guides{" "}
              <span className="tone">
                no sign-in needed
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              Illustrated, step-by-step, and written for people doing the work.
            </p>
            {" "}
          </div>
          {" "}
          <div className="mbento mb3">
            {" "}
            <article className="mtile m-art m-w2 tilt rise">
              {" "}
              <img src="/ds/ab-glass.jpg" alt="" loading="lazy" />
              {" "}
              <div className="mt">
                <span className="ico">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-down" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow" style={{ color: "var(--accent)", marginTop: "14px" }}>
                  21 pages · PDF
                </span>
                {" "}
                <h4>
                  Installer Hub
                </h4>
                {" "}
                <p style={{ maxWidth: "46ch" }}>
                  Signing in, installing your products, applying updates, and fixing the things that go wrong.
                </p>
                {" "}
                <div style={{ display: "flex", gap: "9px", marginTop: "16px" }}>
                  {" "}
                  <Link to="/docs/ADLM-Installer-Hub-User-Guide.pdf" className="ds-btn btn-p ds-btn-sm" download="">
                    Download{" "}
                    <svg viewBox="0 0 24 24">
                      <use href="#i-down" />
                    </svg>
                  </Link>
                  {" "}
                  <button type="button" className="ds-btn btn-o ds-btn-sm" data-doc="docs/ADLM-Installer-Hub-User-Guide.pdf" data-title="Installer Hub">
                    Preview
                  </button>
                  {" "}
                </div>
              </div>
              {" "}
            </article>
            {" "}
            <article className="mtile solid tilt rise">
              {" "}
              <div className="mid">
                {" "}
                <span className="ico">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-cube" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow" style={{ color: "var(--accent)", marginTop: "14px" }}>
                  22 pages · PDF
                </span>
                {" "}
                <h4>
                  QUIV for Revit
                </h4>
                {" "}
                <p style={{ maxWidth: "46ch" }}>
                  Opening your model, the Model Checker, taking off every element, and turning it into a priced bill.
                </p>
                {" "}
                <div style={{ display: "flex", gap: "9px", marginTop: "16px" }}>
                  {" "}
                  <Link to="/docs/ADLM-QUIV-Revit-User-Guide.pdf" className="ds-btn btn-p ds-btn-sm" download="">
                    Download{" "}
                    <svg viewBox="0 0 24 24">
                      <use href="#i-down" />
                    </svg>
                  </Link>
                  {" "}
                  <button type="button" className="ds-btn btn-o ds-btn-sm" data-doc="docs/ADLM-QUIV-Revit-User-Guide.pdf" data-title="QUIV for Revit">
                    Preview
                  </button>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="mtile m-art tilt rise">
              {" "}
              <img src="/ds/hd-cad.jpg" alt="" loading="lazy" />
              {" "}
              <div className="mt">
                <span className="ico">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-calc" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow" style={{ color: "var(--accent)", marginTop: "14px" }}>
                  19 pages · PDF
                </span>
                {" "}
                <h4>
                  ADLM RateGen
                </h4>
                {" "}
                <p style={{ maxWidth: "46ch" }}>
                  Rate build-ups, material and labour libraries, custom rates, and how rates reach QUIV and HERON.
                </p>
                {" "}
                <div style={{ display: "flex", gap: "9px", marginTop: "16px" }}>
                  {" "}
                  <Link to="/docs/ADLM-RateGen-User-Guide.pdf" className="ds-btn btn-p ds-btn-sm" download="">
                    Download{" "}
                    <svg viewBox="0 0 24 24">
                      <use href="#i-down" />
                    </svg>
                  </Link>
                  {" "}
                  <button type="button" className="ds-btn btn-o ds-btn-sm" data-doc="docs/ADLM-RateGen-User-Guide.pdf" data-title="ADLM RateGen">
                    Preview
                  </button>
                  {" "}
                </div>
              </div>
              {" "}
            </article>
            {" "}
            <article className="mtile ds-accent m-w2 tilt rise">
              {" "}
              <div className="mid">
                {" "}
                <span className="ico">
                  <svg viewBox="0 0 24 24">
                    <use href="#i-doc" />
                  </svg>
                </span>
                {" "}
                <span className="eyebrow" style={{ color: "var(--accent)", marginTop: "14px" }}>
                  48 pages · PDF
                </span>
                {" "}
                <h4>
                  Installer Hub &amp; HERON
                </h4>
                {" "}
                <p style={{ maxWidth: "46ch" }}>
                  The combined book — the Hub end to end, then HERON: scaling drawings, measuring, pricing and export.
                </p>
                {" "}
                <div style={{ display: "flex", gap: "9px", marginTop: "16px" }}>
                  {" "}
                  <Link to="/docs/ADLM-Complete-User-Guide.pdf" className="ds-btn btn-p ds-btn-sm" download="">
                    Download{" "}
                    <svg viewBox="0 0 24 24">
                      <use href="#i-down" />
                    </svg>
                  </Link>
                  {" "}
                  <button type="button" className="ds-btn btn-o ds-btn-sm" data-doc="docs/ADLM-Complete-User-Guide.pdf" data-title="Installer Hub &amp; HERON">
                    Preview
                  </button>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <div className="docviewer" id="docviewer" hidden={true}>
        {" "}
        <div className="dv-inner">
          {" "}
          <div className="dv-bar">
            <b id="dv-title">
              Preview
            </b>
            {" "}
            <button type="button" id="dv-close" aria-label="Close preview">
              ✕
            </button>
          </div>
          {" "}
          <iframe id="dv-frame" title="Document preview">
          </iframe>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
      <section className="sec-half blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "38px" }}>
            {" "}
            <span className="eyebrow">
              Questions
            </span>
            {" "}
            <h2>
              About learning with ADLM
            </h2>
            {" "}
          </div>
          {" "}
          <div className="faq rise">
            {" "}
            <details open={true}>
              {" "}
              <summary>
                Are the courses live or self-paced?
              </summary>
              {" "}
              <div className="faq-a">
                Self-paced, delivered through Google Classroom, with weekly assessments to keep you moving. Support is available while you work through it.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Do I need to own the software to take a course?
              </summary>
              {" "}
              <div className="faq-a">
                No, but you will get more out of it if you do. Course licences and product licences are priced separately — ask and we'll quote both together.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Is the certificate recognised?
              </summary>
              {" "}
              <div className="faq-a">
                It is a certificate of completion from ADLM Studio. It evidences the work you did; it is not a professional accreditation.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Can you train a whole department?
              </summary>
              {" "}
              <div className="faq-a">
                Yes. On-site training is our oldest business — thirty events so far, including NIQS chapters and government agencies.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Are the free lessons really free?
              </summary>
              {" "}
              <div className="faq-a">
                Yes, and no sign-in is needed. They live on our YouTube channel and are embedded here.
              </div>
              {" "}
            </details>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}{DsPromoSlot}{" "}
      <section className="cta">
        {" "}
        <div className="cta-bp">
        </div>
        <div className="cta-dots">
        </div>
        <div className="cta-g">
        </div>
        {" "}
        <h2>
          Train your{" "}
          <span className="grad">
            whole team
          </span>
        </h2>
        {" "}
        <p className="ds-lede">
          An instructor comes to your office and works through your own projects, not a demo file.
        </p>
        {" "}
        <div className="hero-cta">
          {" "}
          <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
            Request a quote
          </Link>
          {" "}
          <a href="#courses" className="ds-btn btn-o">
            Browse courses
          </a>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
