// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/mep.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";
import DsPromoLive from "../DsPromoLive.jsx";

export default function DsMepPage({ d }) {
  const DsPromoSlot = <DsPromoLive />;
  return (
    <>
      <header className="phero">
        {" "}
        <div className="phero-bg">
          <img src="/ds/bg-mep.jpg" alt="Revit MEP" />
        </div>
        {" "}
        <div className="phero-in">
          {" "}
          <span className="host">
            MEP &amp; HVAC · Autodesk Revit
          </span>
          {" "}
          <h1>
            {" "}
            <span className="w" style={{ "--i": "0" }}>
              Services
            </span>
            {" "}
            <span className="w" style={{ "--i": "1" }}>
              measured
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "2" }}>
              where
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "3" }}>
              they
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "4" }}>
              were
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "5" }}>
              modelled.
            </span>
            {" "}
          </h1>
          {" "}
          <p className="ds-lede">
            Ductwork, pipework, electrical and plumbing — from the model, in one workspace.
          </p>
          {" "}
          <div className="hero-cta">
            {" "}
            <Link to="/purchase" data-ds-page="cart" className="ds-btn btn-p">
              Get Revit MEP
            </Link>
            {" "}
            <Link to="/pricing" data-ds-page="pricing" className="ds-btn btn-o">
              See pricing
            </Link>
            {" "}
          </div>
          {" "}
          <p className="phero-note">
            <span className="pulse">
            </span>
            Latest v1.8.3 · Revit 2024, 2026 &amp; 2027
          </p>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              Core features
            </span>
            {" "}
            <h2>
              What Revit MEP does{" "}
              <span className="tone">
                and how it does it
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="fgrid">
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz">
                  <div className="vz-duct">
                    <i>
                    </i>
                    <i>
                    </i>
                    <i>
                    </i>
                    <b>
                    </b>
                    <b>
                    </b>
                  </div>
                  {" "}
                  <div style={{ display: "flex", gap: "7px", justifyContent: "center", marginTop: "6px" }}>
                    {" "}
                    <span className="vz-chip on">
                      184.6 m run
                    </span>
                    <span className="vz-chip">
                      18 fittings
                    </span>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Measurement
                </span>
                {" "}
                <h4>
                  Ductwork and pipework by run
                </h4>
                {" "}
                <p>
                  Measured along the run with fittings counted separately, so a duct schedule reads the way a services engineer describes it rather than as one lump length.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz">
                  <div className="vz-panel">
                    {" "}
                    <div className="vz-row">
                      <span>
                        Mechanical · ductwork
                      </span>
                      <b>
                        ₦14,208,400
                      </b>
                    </div>
                    {" "}
                    <div className="vz-row">
                      <span>
                        Plumbing · pipework
                      </span>
                      <b>
                        ₦8,641,200
                      </b>
                    </div>
                    {" "}
                    <div className="vz-row">
                      <span>
                        Electrical · containment
                      </span>
                      <b>
                        ₦6,320,900
                      </b>
                    </div>
                    {" "}
                    <div className="vz-sum">
                      <span>
                        Services total
                      </span>
                      <b>
                        ₦29,170,500
                      </b>
                    </div>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Coordination
                </span>
                {" "}
                <h4>
                  Every discipline, one bill
                </h4>
                {" "}
                <p>
                  Mechanical, electrical and plumbing collect into a single structured bill instead of three spreadsheets that disagree at the summary.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz">
                  <div className="vz-sync">
                    {" "}
                    <span className="hub">
                      <svg viewBox="0 0 24 24">
                        <use href="#i-calc" />
                      </svg>
                    </span>
                    {" "}
                    <span className="outs">
                      <span className="vz-chip on">
                        Duct · per m
                      </span>
                      {" "}
                      <span className="vz-chip on">
                        Pipe · per m
                      </span>
                      <span className="vz-chip on">
                        Fittings · per no
                      </span>
                    </span>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Shared library
                </span>
                {" "}
                <h4>
                  Priced from the same library
                </h4>
                {" "}
                <p>
                  Services rates come from RateGen exactly as architectural ones do, so the services bill and the building bill are built on one set of prices.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz">
                  <div className="xl">
                    {" "}
                    <div className="xl-h">
                      <span>
                        Ref
                      </span>
                      <span>
                        Asset
                      </span>
                      <span>
                        Qty
                      </span>
                      <span>
                        Unit
                      </span>
                    </div>
                    {" "}
                    <div className="xl-r">
                      <span>
                        AHU
                      </span>
                      <span>
                        Air handling unit
                      </span>
                      <span>
                        4
                      </span>
                      <span>
                        no
                      </span>
                    </div>
                    {" "}
                    <div className="xl-r">
                      <span>
                        FCU
                      </span>
                      <span>
                        Fan coil unit
                      </span>
                      <span>
                        62
                      </span>
                      <span>
                        no
                      </span>
                    </div>
                    {" "}
                    <div className="xl-r on">
                      <span>
                        VAV
                      </span>
                      <span>
                        VAV terminal
                      </span>
                      <span>
                        38
                      </span>
                      <span>
                        no
                      </span>
                    </div>
                    {" "}
                  </div>
                  <div style={{ display: "flex", justifyContent: "center", marginTop: "12px" }}>
                    {" "}
                    <span className="vz-chip on">
                      COBie ready
                    </span>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Handover
                </span>
                {" "}
                <h4>
                  COBie asset handover
                </h4>
                {" "}
                <p>
                  The same model that produced the quantities produces the asset register, so what facilities management receives matches what was actually installed.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz" style={{ maxWidth: "600px" }}>
                  <div className="vz-cols">
                    {" "}
                    <div className="vz-col">
                      Ductwork
                      <b>
                        184.6 m
                      </b>
                    </div>
                    {" "}
                    <div className="vz-col">
                      Pipework
                      <b>
                        312.4 m
                      </b>
                    </div>
                    {" "}
                    <div className="vz-col">
                      Fittings
                      <b>
                        486 no
                      </b>
                    </div>
                  </div>
                  {" "}
                  <div style={{ display: "flex", gap: "7px", justifyContent: "center", marginTop: "12px" }}>
                    {" "}
                    <span className="vz-chip on">
                      docked in Revit
                    </span>
                    <span className="vz-chip">
                      reflows when narrow
                    </span>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Workflow
                </span>
                {" "}
                <h4>
                  Docked beside the model you're reading
                </h4>
                {" "}
                <p>
                  The panel sits inside Revit next to the services model, so you measure while looking at the thing you are measuring — and the layout reflows when you dock it narrow.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <div className="frame frame-soft">
        {" "}
        <section className="sec band-dark amb">
          {" "}
          <div className="shell">
            {" "}
            <div className="sec-head mid rise">
              {" "}
              <span className="eyebrow">
                The output
              </span>
              {" "}
              <h2>
                Services that reconcile{" "}
                <span className="grad">
                  with the building
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                One model, one rate library, one summary — so the totals actually agree.
              </p>
              {" "}
            </div>
            {" "}
            <div className="chain rise">
              {" "}
              <article className="chain-c">
                {" "}
                <span className="chain-n">
                  01
                </span>
                {" "}
                <h3>
                  What Revit gives you
                </h3>
                {" "}
                <div className="frag">
                  {" "}
                  <div className="frag-t">
                    System type
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Duct · Rect 400x250
                    </span>
                    <span className="frag-v">
                      raw string
                    </span>
                  </div>
                  {" "}
                </div>
                {" "}
              </article>
              {" "}
              <span className="chain-link" aria-hidden="true">
              </span>
              {" "}
              <article className="chain-c">
                {" "}
                <span className="chain-n">
                  02
                </span>
                {" "}
                <h3>
                  What the bill says
                </h3>
                {" "}
                <div className="frag">
                  {" "}
                  <div className="frag-t">
                    Bill description
                  </div>
                  {" "}
                  <div className="pre">
                    Galvanised sheet metal ductwork, rectangular, to BS EN 1505
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      400 × 250mm · First floor
                    </span>
                    <span className="frag-v">
                      184.60 m
                    </span>
                  </div>
                  {" "}
                </div>
                {" "}
              </article>
              {" "}
              <span className="chain-link" aria-hidden="true">
              </span>
              {" "}
              <article className="chain-c">
                {" "}
                <span className="chain-n">
                  03
                </span>
                {" "}
                <h3>
                  What the client receives
                </h3>
                {" "}
                <div className="frag">
                  {" "}
                  <div className="frag-t">
                    Services summary · export
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Mechanical
                    </span>
                    <span className="frag-v">
                      ₦14,208,400
                    </span>
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Plumbing
                    </span>
                    <span className="frag-v">
                      ₦8,641,200
                    </span>
                  </div>
                  {" "}
                  <div className="frag-sum">
                    <span>
                      Services total
                    </span>
                    <span className="frag-v">
                      ₦32,670,960
                    </span>
                  </div>
                  {" "}
                </div>
                {" "}
              </article>
              {" "}
            </div>
            {" "}
            <p className="chain-note">
              One raw system string becomes a described bill line and a total that agrees. Nothing is retyped along the way.
            </p>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </div>
      {" "}
      <section className="sec-half blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise" style={{ marginBottom: "36px" }}>
            {" "}
            <span className="eyebrow">
              Compatibility
            </span>
            {" "}
            <h2>
              Where Revit MEP{" "}
              <span className="tone">
                fits in your setup
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="compat">
            {" "}
            <div className="compat-c rise">
              <h6>
                Host application
              </h6>
              {" "}
              <div className="big">
                Autodesk Revit
              </div>
              {" "}
              <div className="compat-tags">
                <span>
                  2024 · 2026 · 2027
                </span>
              </div>
            </div>
            {" "}
            <div className="compat-c rise">
              <h6>
                Disciplines
              </h6>
              {" "}
              <div className="big">
                Mechanical · Electrical
              </div>
              {" "}
              <div className="compat-tags">
                <span>
                  Plumbing · HVAC
                </span>
              </div>
            </div>
            {" "}
            <div className="compat-c rise">
              <h6>
                Output
              </h6>
              {" "}
              <div className="big">
                Excel · COBie
              </div>
              {" "}
              <div className="compat-tags">
                <span>
                  Asset register
                </span>
              </div>
            </div>
            {" "}
            <div className="compat-c rise">
              <h6>
                Standards
              </h6>
              {" "}
              <div className="big">
                BESMM4R · NRM2
              </div>
              {" "}
              <div className="compat-tags">
                <span>
                  ICMS3 reporting
                </span>
              </div>
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half alt amb blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "36px" }}>
            {" "}
            <span className="eyebrow">
              Pricing
            </span>
            {" "}
            <h2>
              {d.monthly} a month,{" "}
              <span className="tone">
                per PC
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              {d.priceLine}
            </p>
            {" "}
            <div className="hero-cta" style={{ justifyContent: "center" }}>
              {" "}
              <Link to="/purchase" data-ds-page="cart" className="ds-btn btn-p">
                Get Revit MEP
              </Link>
              {" "}
              <Link to="/contact" data-ds-page="contact" className="ds-btn btn-o">
                Build a quote
              </Link>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half blend" id="updates">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "40px" }}>
            {" "}
            <span className="eyebrow">
              Release history
            </span>
            {" "}
            <h2>
              What's changed{" "}
              <span className="tone">
                over time
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              Every release, in plain English — what shipped, what improved, what was fixed.
            </p>
            {" "}
          </div>
          {" "}{d.releases}{" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "38px" }}>
            {" "}
            <span className="eyebrow">
              Questions
            </span>
            {" "}
            <h2>
              About Revit MEP
            </h2>
            {" "}
          </div>
          {" "}
          <div className="faq rise">
            {" "}
            <details open={true}>
              {" "}
              <summary>
                Is this separate from QUIV?
              </summary>
              {" "}
              <div className="faq-a">
                Yes — separate licence, same workspace. QUIV measures the building fabric, Revit MEP measures the services. Many teams run both.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Does it need a well-modelled services model?
              </summary>
              {" "}
              <div className="faq-a">
                It needs systems that are actually connected. Loose components measure as counts; connected runs measure as runs, which is what you want.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Can it produce COBie on its own?
              </summary>
              {" "}
              <div className="faq-a">
                It exports the asset data from the model. Whether that satisfies a particular employer's information requirements depends on how the model was populated.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                What about clash detection?
              </summary>
              {" "}
              <div className="faq-a">
                Not in this plugin — that is Navisworks. Revit MEP is measurement and cost, and it is covered in the MEP course.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Does it price from RateGen too?
              </summary>
              {" "}
              <div className="faq-a">
                Yes, the same library. Services and building work read the same rates.
              </div>
              {" "}
            </details>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}{DsPromoSlot}{" "}
      <section className="cta">
        {" "}
        <div className="cta-bp">
        </div>
        <div className="cta-dots">
        </div>
        <div className="cta-g">
        </div>
        {" "}
        <h2>
          See it on{" "}
          <span className="grad">
            your project
          </span>
        </h2>
        {" "}
        <p className="ds-lede">
          We'll run Revit MEP against one of your live jobs — your drawings, your rates, your bill format.
        </p>
        {" "}
        <div className="hero-cta">
          {" "}
          <Link to="/purchase" data-ds-page="cart" className="ds-btn btn-p">
            Get Revit MEP
          </Link>
          {" "}
          <Link to="/products" data-ds-page="products" className="ds-btn btn-o">
            All products
          </Link>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
