// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/plugin-heron.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";

export default function DsPluginHeron() {
  return (
    <>
      {/* PlanSwift sits behind HERON rather than around it: the take-off is already
     done by the time HERON opens, so the QS is switching windows, not working
     in two panes. It shows through in dock mode. */}
      {" "}
      <div className="hn-behind" aria-hidden="true">
        {" "}
        <div className="hn-ps-title">
          <span className="hn-ps-logo">
            P
          </span>
          {" "}PlanSwift Pro Metric 11.0, 2026, qts 517 practise
        </div>
        {" "}
        <div className="hn-ps-body">
          {" "}
          <div className="hn-ps-panel">
            {" "}
            <b>
              Takeoff Summary
            </b>
            {" "}
            <ul>
              {" "}
              <li>
                SITE CLEARANCE{" "}
                <i>
                  90.68
                </i>
              </li>
              {" "}
              <li className="f">
                Ground FLoor
              </li>
              {" "}
              <li className="in">
                Site Area{" "}
                <i>
                  92.79
                </i>
              </li>
              {" "}
              <li className="f">
                Sub
              </li>
              {" "}
              <li className="in">
                Girth{" "}
                <i>
                  37.24
                </i>
              </li>
              {" "}
              <li className="in2">
                Trench Exc{" "}
                <i>
                  48.14
                </i>
              </li>
              {" "}
              <li className="in2">
                Surface Treatment{" "}
                <i>
                  166.92
                </i>
              </li>
              {" "}
              <li className="in2">
                Earth Work Support{" "}
                <i>
                  141.59
                </i>
              </li>
              {" "}
              <li className="in2">
                Concrete Footing{" "}
                <i>
                  0.00
                </i>
              </li>
              {" "}
            </ul>
            {" "}
          </div>
          {" "}
          <div className="hn-ps-sheet">
            <span>
              A-101 · Ground floor plan · 1:100
            </span>
          </div>
          {" "}
          <div className="hn-ps-panel r">
            {" "}
            <b>
              Templates, Parts, Inputs
            </b>
            {" "}
            <ul>
              {" "}
              <li className="t">
                Complete ADLM TakeOff
              </li>
              {" "}
              <li className="f">
                SUBSTRUCTURE
              </li>
              {" "}
              <li className="in">
                Site Area
              </li>
              {" "}
              <li className="in">
                Building Area
              </li>
              {" "}
              <li className="in">
                PAD FOUNDATION
              </li>
              {" "}
              <li className="in">
                STRIP FOUNDATION
              </li>
              {" "}
              <li className="f">
                FRAME
              </li>
              {" "}
              <li className="in">
                COLUMN
              </li>
              {" "}
              <li className="in">
                BEAM
              </li>
              {" "}
            </ul>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </div>
      {" "}
      <div className="hn mode-full" id="hn">
      </div>
    </>
  );
}
