// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/press.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";
import DsPromoLive from "../DsPromoLive.jsx";

export default function DsPress() {
  const DsPromoSlot = <DsPromoLive />;
  return (
    <>
      <header className="phero phero-sm">
        {" "}
        <div className="phero-bg">
          <img src="/ds/ab-glass.jpg" alt="" />
        </div>
        {" "}
        <div className="phero-in">
          {" "}
          <span className="host">
            Press
          </span>
          {" "}
          <h1>
            {" "}
            <span className="w" style={{ "--i": "0" }}>
              Facts,
            </span>
            {" "}
            <span className="w" style={{ "--i": "1" }}>
              assets
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "2" }}>
              and
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "3" }}>
              a
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "4" }}>
              contact.
            </span>
            {" "}
          </h1>
          {" "}
          <p className="ds-lede">
            Everything a journalist or conference organiser usually asks for, in one place.
          </p>
          {" "}
          <div className="hero-cta">
            {" "}
            <a href="mailto:admin@adlmstudio.net" className="ds-btn btn-p">
              Press enquiries
            </a>
            {" "}
            <Link to="/about" data-ds-page="about" className="ds-btn btn-o">
              About the studio
            </Link>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              The basics
            </span>
            {" "}
            <h2>
              Company facts
            </h2>
            {" "}
          </div>
          {" "}
          <div className="ctable-wrap rise">
            {" "}
            <table className="ctable">
              {" "}
              <tbody>
                {" "}
                <tr>
                  <th className="rowhead" scope="row">
                    Founded
                    <small>
                      Year of incorporation
                    </small>
                  </th>
                  <td>
                    2019
                  </td>
                </tr>
                {" "}
                <tr>
                  <th className="rowhead" scope="row">
                    Headquarters
                    <small>
                      Where the team works
                    </small>
                  </th>
                  <td>
                    Lagos, Nigeria
                  </td>
                </tr>
                {" "}
                <tr>
                  <th className="rowhead" scope="row">
                    What we make
                    <small>
                      In one line
                    </small>
                  </th>
                  <td>
                    Quantity surveying software and BIM training for the African construction market
                  </td>
                </tr>
                {" "}
                <tr>
                  <th className="rowhead" scope="row">
                    Products
                    <small>
                      Shipping and in development
                    </small>
                  </th>
                  <td>
                    QUIV · HERON · RateGen · Revit MEP · Time Pro · CIVIQ (in development)
                  </td>
                </tr>
                {" "}
                <tr>
                  <th className="rowhead" scope="row">
                    Training delivered
                    <small>
                      Since 2022
                    </small>
                  </th>
                  <td>
                    30 events · 3,100+ professionals
                  </td>
                </tr>
                {" "}
                <tr>
                  <th className="rowhead" scope="row">
                    Reach
                    <small>
                      Countries with users
                    </small>
                  </th>
                  <td>
                    10+
                  </td>
                </tr>
                {" "}
                <tr>
                  <th className="rowhead" scope="row">
                    Press contact
                    <small>
                      Fastest route
                    </small>
                  </th>
                  <td>
                    admin@adlmstudio.net
                  </td>
                </tr>
                {" "}
              </tbody>
              {" "}
            </table>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec" id="brand">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              Brand assets
            </span>
            {" "}
            <h2>
              The ADLM brand,{" "}
              <span className="tone">
                in detail
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              Everything you need to write about us or put our mark on a slide. Pick a section on the left, or just keep scrolling: the list follows you down.
            </p>
            {" "}
          </div>
          {" "}
          <div className="bkit rise" id="bkit">
            {" "}
            <nav className="bkit-nav" aria-label="Brand sections">
              {" "}
              <ol>
                {" "}
                <li>
                  <a href="#bk-logo" className="on">
                    Logo
                  </a>
                </li>
                {" "}
                <li>
                  <a href="#bk-colour">
                    Colour
                  </a>
                </li>
                {" "}
                <li>
                  <a href="#bk-type">
                    Typography
                  </a>
                </li>
                {" "}
                <li>
                  <a href="#bk-imagery">
                    Imagery
                  </a>
                </li>
                {" "}
                <li>
                  <a href="#bk-message">
                    Messaging
                  </a>
                </li>
                {" "}
                <li>
                  <a href="#bk-icons">
                    Icon pack
                  </a>
                </li>
                {" "}
                <li>
                  <a href="#bk-product">
                    Product assets
                  </a>
                </li>
                {" "}
              </ol>
              {" "}
              <a className="ds-btn btn-o ds-btn-sm bkit-all" href="mailto:admin@adlmstudio.net?subject=ADLM%20brand%20kit">
                Request the full kit
              </a>
              {" "}
            </nav>
            {" "}
            <div className="bkit-main">
              {" "}
              {/* ---------- Logo ---------- */}
              {" "}
              <article className="bkit-p" id="bk-logo">
                {" "}
                <span className="bkit-n">
                  01
                </span>
                {" "}
                <h3>
                  Logo
                </h3>
                {" "}
                <p className="bkit-lede">
                  The ADLM Studio identity is a mark and a wordmark. Use the supplied files: please do not redraw either of them, and do not set “ADLM Studio” in another typeface and call it the logo.
                </p>
                {" "}
                <div className="bkit-row">
                  {" "}
                  <figure className="bkit-tile">
                    {" "}
                    <div className="bkit-art bkit-art-l">
                      <img src="/ds/logo-light.svg" alt="ADLM Studio primary lockup" />
                    </div>
                    {" "}
                    <figcaption>
                      <b>
                        Primary lockup
                      </b>
                      <span>
                        Mark + wordmark. Light grounds.
                      </span>
                    </figcaption>
                    {" "}
                  </figure>
                  {" "}
                  <figure className="bkit-tile">
                    {" "}
                    <div className="bkit-art bkit-art-d">
                      <img src="/ds/logo-dark.svg" alt="ADLM Studio dark-ground lockup" />
                    </div>
                    {" "}
                    <figcaption>
                      <b>
                        Dark-ground lockup
                      </b>
                      <span>
                        Navy and darker photography.
                      </span>
                    </figcaption>
                    {" "}
                  </figure>
                  {" "}
                  <figure className="bkit-tile">
                    {" "}
                    <div className="bkit-art bkit-art-l">
                      <img src="/ds/mark.svg" alt="ADLM Studio mark" style={{ width: "74px", height: "74px" }} />
                    </div>
                    {" "}
                    <figcaption>
                      <b>
                        The mark alone
                      </b>
                      <span>
                        Avatars, favicons, app tiles.
                      </span>
                    </figcaption>
                    {" "}
                  </figure>
                  {" "}
                </div>
                {" "}
                <div className="bkit-rules">
                  {" "}
                  <div className="bkit-do">
                    {" "}
                    <h4>
                      <svg viewBox="0 0 24 24">
                        <use href="#i-check" />
                      </svg>
                      Please do
                    </h4>
                    {" "}
                    <ul>
                      {" "}
                      <li>
                        Leave clear space around the lockup equal to the height of the mark on every side.
                      </li>
                      {" "}
                      <li>
                        Use the dark-ground lockup on navy, on photography and on anything below 40% luminance.
                      </li>
                      {" "}
                      <li>
                        Keep the mark at 24px or larger on screen, 8mm or larger in print.
                      </li>
                      {" "}
                      <li>
                        Place the mark on a plain field when it sits over a busy image.
                      </li>
                      {" "}
                    </ul>
                    {" "}
                  </div>
                  {" "}
                  <div className="bkit-dont">
                    {" "}
                    <h4>
                      <svg viewBox="0 0 24 24">
                        <use href="#i-x" />
                      </svg>
                      Please don't
                    </h4>
                    {" "}
                    <ul>
                      {" "}
                      <li>
                        Recolour the mark, add a gradient to it, or outline it.
                      </li>
                      {" "}
                      <li>
                        Stretch, squash, rotate or add a drop shadow to the lockup.
                      </li>
                      {" "}
                      <li>
                        Rebuild the wordmark in a different typeface, or letterspace it.
                      </li>
                      {" "}
                      <li>
                        Put the light-ground lockup on a dark photograph and hope for the best.
                      </li>
                      {" "}
                    </ul>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="bkit-dl">
                  {" "}
                  <Link className="bkit-file" to="/ds/logo-light.svg" download="">
                    {" "}
                    <span className="bkit-ext">
                      SVG
                    </span>
                    <span>
                      <b>
                        Primary lockup
                      </b>
                      <span>
                        Vector · light grounds
                      </span>
                    </span>
                    {" "}
                    <svg viewBox="0 0 24 24">
                      <use href="#i-down" />
                    </svg>
                  </Link>
                  {" "}
                  <Link className="bkit-file" to="/ds/logo-dark.svg" download="">
                    {" "}
                    <span className="bkit-ext">
                      SVG
                    </span>
                    <span>
                      <b>
                        Dark-ground lockup
                      </b>
                      <span>
                        Vector · dark grounds
                      </span>
                    </span>
                    {" "}
                    <svg viewBox="0 0 24 24">
                      <use href="#i-down" />
                    </svg>
                  </Link>
                  {" "}
                  <Link className="bkit-file" to="/ds/mark.svg" download="">
                    {" "}
                    <span className="bkit-ext">
                      SVG
                    </span>
                    <span>
                      <b>
                        Mark only
                      </b>
                      <span>
                        Vector · 63 × 63
                      </span>
                    </span>
                    {" "}
                    <svg viewBox="0 0 24 24">
                      <use href="#i-down" />
                    </svg>
                  </Link>
                  {" "}
                </div>
                {" "}
              </article>
              {" "}
              {/* ---------- Colour ---------- */}
              {" "}
              <article className="bkit-p" id="bk-colour">
                {" "}
                <span className="bkit-n">
                  02
                </span>
                {" "}
                <h3>
                  Colour
                </h3>
                {" "}
                <p className="bkit-lede">
                  Three colours carry the brand. Navy is the ground, blue is the action, orange is the accent, and orange is used sparingly, on one thing at a time.
                </p>
                {" "}
                <div className="bkit-sw">
                  {" "}
                  <div className="bkit-c">
                    <span className="bkit-chip" style={{ background: "#091E39" }}>
                    </span>
                    {" "}
                    <b>
                      Navy
                    </b>
                    <code>
                      #091E39
                    </code>
                    <span>
                      Dark grounds, body ink, the mark.
                    </span>
                  </div>
                  {" "}
                  <div className="bkit-c">
                    <span className="bkit-chip" style={{ background: "#239CFF" }}>
                    </span>
                    {" "}
                    <b>
                      Blue
                    </b>
                    <code>
                      #239CFF
                    </code>
                    <span>
                      Links, focus, the gradient's bright end. A dark-ground colour.
                    </span>
                  </div>
                  {" "}
                  <div className="bkit-c">
                    <span className="bkit-chip" style={{ background: "#0B7FDB" }}>
                    </span>
                    {" "}
                    <b>
                      Action blue
                    </b>
                    <code>
                      #0B7FDB
                    </code>
                    <span>
                      Buttons and links on light grounds.
                    </span>
                  </div>
                  {" "}
                  <div className="bkit-c">
                    <span className="bkit-chip" style={{ background: "#E86A27" }}>
                    </span>
                    {" "}
                    <b>
                      Orange
                    </b>
                    <code>
                      #E86A27
                    </code>
                    <span>
                      Eyebrows, one emphasis per section. Never a whole panel.
                    </span>
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="bkit-sw bkit-sw-sm">
                  {" "}
                  <div className="bkit-c">
                    <span className="bkit-chip" style={{ background: "#04101F" }}>
                    </span>
                    <b>
                      Navy 950
                    </b>
                    <code>
                      #04101F
                    </code>
                  </div>
                  {" "}
                  <div className="bkit-c">
                    <span className="bkit-chip" style={{ background: "#143A66" }}>
                    </span>
                    <b>
                      Navy 700
                    </b>
                    <code>
                      #143A66
                    </code>
                  </div>
                  {" "}
                  <div className="bkit-c">
                    <span className="bkit-chip" style={{ background: "#EAF6FF" }}>
                    </span>
                    <b>
                      Blue 50
                    </b>
                    <code>
                      #EAF6FF
                    </code>
                  </div>
                  {" "}
                  <div className="bkit-c">
                    <span className="bkit-chip" style={{ background: "#FDF1E9" }}>
                    </span>
                    <b>
                      Orange 50
                    </b>
                    <code>
                      #FDF1E9
                    </code>
                  </div>
                  {" "}
                </div>
                {" "}
                <p className="bkit-note">
                  The action gradient is{" "}
                  <code>
                    #3FADFF → #1289E6 → #0768B6
                  </code>
                  , top to bottom. It belongs on primary buttons and on nothing else.
                </p>
                {" "}
              </article>
              {" "}
              {/* ---------- Typography ---------- */}
              {" "}
              <article className="bkit-p" id="bk-type">
                {" "}
                <span className="bkit-n">
                  03
                </span>
                {" "}
                <h3>
                  Typography
                </h3>
                {" "}
                <p className="bkit-lede">
                  One family:{" "}
                  <b>
                    Lexend
                  </b>
                  . It is open, legible at small sizes and holds up in a table of numbers, which is most of what our software shows.
                </p>
                {" "}
                <div className="bkit-spec">
                  {" "}
                  <div className="bkit-sp">
                    <span className="bkit-sp-t" style={{ fontWeight: "600", fontSize: "44px", letterSpacing: "-.04em" }}>
                      Measure once
                    </span>
                    {" "}
                    <span className="bkit-sp-m">
                      Display · 600 · −4% tracking · line-height 1.0
                    </span>
                  </div>
                  {" "}
                  <div className="bkit-sp">
                    <span className="bkit-sp-t" style={{ fontWeight: "500", fontSize: "28px", letterSpacing: "-.03em" }}>
                      Section headings
                    </span>
                    {" "}
                    <span className="bkit-sp-m">
                      Heading · 500 · −3% tracking
                    </span>
                  </div>
                  {" "}
                  <div className="bkit-sp">
                    <span className="bkit-sp-t" style={{ fontWeight: "300", fontSize: "17px", lineHeight: "1.6" }}>
                      Body copy runs at 300. Long paragraphs stay light so the headings carry the weight.
                    </span>
                    {" "}
                    <span className="bkit-sp-m">
                      Body · 300 · 17px · line-height 1.6
                    </span>
                  </div>
                  {" "}
                  <div className="bkit-sp">
                    <span className="bkit-sp-t" style={{ fontWeight: "500", fontSize: "11.5px", letterSpacing: ".17em", textTransform: "uppercase", color: "var(--accent)" }}>
                      Eyebrow label
                    </span>
                    {" "}
                    <span className="bkit-sp-m">
                      Eyebrow · 500 · 11.5px · +17% tracking · uppercase · orange
                    </span>
                  </div>
                  {" "}
                </div>
                {" "}
                <p className="bkit-note">
                  Weights in use: 300, 400, 500, 600, 700. Figures are set with{" "}
                  <code>
                    font-variant-numeric: tabular-nums
                  </code>
                  {" "}so columns of money line up. Lexend is open source and available from Google Fonts.
                </p>
                {" "}
                <div className="bkit-dl">
                  {" "}
                  <a className="bkit-file" href="https://fonts.google.com/specimen/Lexend" target="_blank" rel="noopener">
                    {" "}
                    <span className="bkit-ext">
                      WEB
                    </span>
                    <span>
                      <b>
                        Lexend on Google Fonts
                      </b>
                      <span>
                        Free · SIL Open Font Licence
                      </span>
                    </span>
                    {" "}
                    <svg viewBox="0 0 24 24">
                      <use href="#i-arrow" />
                    </svg>
                  </a>
                  {" "}
                </div>
                {" "}
              </article>
              {" "}
              {/* ---------- Imagery ---------- */}
              {" "}
              <article className="bkit-p" id="bk-imagery">
                {" "}
                <span className="bkit-n">
                  04
                </span>
                {" "}
                <h3>
                  Imagery
                </h3>
                {" "}
                <p className="bkit-lede">
                  Real sites, real drawings, real rooms. Our photography is Nigerian construction: scaffolding, rebar, site offices, training halls, not stock handshakes and not glass towers that could be anywhere.
                </p>
                {" "}
                <div className="bkit-row">
                  {" "}
                  <figure className="bkit-tile">
                    {" "}
                    <div className="bkit-art bkit-art-p">
                      <img src="/ds/ab-site.jpg" alt="Site photography" />
                    </div>
                    {" "}
                    <figcaption>
                      <b>
                        Site
                      </b>
                      <span>
                        Work in progress, daylight, people at it.
                      </span>
                    </figcaption>
                    {" "}
                  </figure>
                  {" "}
                  <figure className="bkit-tile">
                    {" "}
                    <div className="bkit-art bkit-art-p">
                      <img src="/ds/ev3.jpg" alt="Training photography" />
                    </div>
                    {" "}
                    <figcaption>
                      <b>
                        Training
                      </b>
                      <span>
                        Rooms we have actually stood in front of.
                      </span>
                    </figcaption>
                    {" "}
                  </figure>
                  {" "}
                  <figure className="bkit-tile">
                    {" "}
                    <div className="bkit-art bkit-art-p">
                      <img src="/ds/hd-cad.jpg" alt="Screen photography" />
                    </div>
                    {" "}
                    <figcaption>
                      <b>
                        Screen
                      </b>
                      <span>
                        The model and the sheet, shot close.
                      </span>
                    </figcaption>
                    {" "}
                  </figure>
                  {" "}
                </div>
                {" "}
                <ul className="bkit-list">
                  {" "}
                  <li>
                    Hero photography carries a navy gradient from the left, so copy sits on the dark end and the image breathes on the right.
                  </li>
                  {" "}
                  <li>
                    Never stretch an image to fit, crop it. Faces and drawings both suffer.
                  </li>
                  {" "}
                  <li>
                    Avoid heavy filters. If a photo needs a filter to work, it is the wrong photo.
                  </li>
                  {" "}
                  <li>
                    Screenshots are shown in a frame with a hairline, never floating on the page.
                  </li>
                  {" "}
                </ul>
                {" "}
              </article>
              {" "}
              {/* ---------- Messaging ---------- */}
              {" "}
              <article className="bkit-p" id="bk-message">
                {" "}
                <span className="bkit-n">
                  05
                </span>
                {" "}
                <h3>
                  Messaging
                </h3>
                {" "}
                <p className="bkit-lede">
                  If you quote one line, quote this one.
                </p>
                {" "}
                <blockquote className="bkit-quote">
                  Quantity surveying software and BIM training, built in Lagos for the way African construction actually works.
                </blockquote>
                {" "}
                <h4 className="bkit-h4">
                  Boilerplate
                </h4>
                {" "}
                <p className="bkit-body">
                  ADLM Studio builds quantity surveying software for the African construction market. Its products: QUIV, HERON, RateGen, Revit MEP and Time Pro: dock into Revit and PlanSwift so quantity surveyors can measure, price and programme work without leaving the drawing. Alongside the software, ADLM runs certificated BIM training: 30 events and more than 3,100 professionals trained since 2022, across NIQS chapters, universities, practices and government agencies. The company was founded in 2019 and works from Lagos, Nigeria.
                </p>
                {" "}
                <h4 className="bkit-h4">
                  How we write
                </h4>
                {" "}
                <ul className="bkit-list">
                  {" "}
                  <li>
                    Plain English. If a quantity surveyor would not say it out loud, do not print it.
                  </li>
                  {" "}
                  <li>
                    Say what the software does, not what it enables, empowers or unlocks.
                  </li>
                  {" "}
                  <li>
                    British spelling: “programme”, “licence” as a noun, “organisation”.
                  </li>
                  {" "}
                  <li>
                    Numbers stay honest: 3,100+ professionals, 30 events, 10+ countries. No rounding up.
                  </li>
                  {" "}
                </ul>
                {" "}
                <h4 className="bkit-h4">
                  Product names
                </h4>
                {" "}
                <ul className="bkit-list">
                  {" "}
                  <li>
                    <b>
                      QUIV
                    </b>
                    ,{" "}
                    <b>
                      HERON
                    </b>
                    {" "}and{" "}
                    <b>
                      CIVIQ
                    </b>
                    {" "}are set in full capitals.
                  </li>
                  {" "}
                  <li>
                    <b>
                      RateGen
                    </b>
                    {" "}and{" "}
                    <b>
                      Time Pro
                    </b>
                    {" "}are not: RateGen is one word, Time Pro is two.
                  </li>
                  {" "}
                  <li>
                    The company is{" "}
                    <b>
                      ADLM Studio
                    </b>
                    {" "}on first mention and{" "}
                    <b>
                      ADLM
                    </b>
                    {" "}after that.
                  </li>
                  {" "}
                  <li>
                    The desktop app is the{" "}
                    <b>
                      Installer Hub
                    </b>
                    , capital I and capital H.
                  </li>
                  {" "}
                </ul>
                {" "}
              </article>
              {" "}
              {/* ---------- Icon pack ---------- */}
              {" "}
              <article className="bkit-p" id="bk-icons">
                {" "}
                <span className="bkit-n">
                  06
                </span>
                {" "}
                <h3>
                  Icon pack
                </h3>
                {" "}
                <p className="bkit-lede">
                  The interface set is drawn on a 24px grid with a 2px stroke, round caps and round joins. It is stroked, never filled, so it inherits the colour of whatever it sits in.
                </p>
                {" "}
                <div className="bkit-icons">
                  {" "}
                  <span className="bkit-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                    <small>
                      check
                    </small>
                  </span>
                  {" "}
                  <span className="bkit-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-arrow" />
                    </svg>
                    <small>
                      arrow
                    </small>
                  </span>
                  {" "}
                  <span className="bkit-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-down" />
                    </svg>
                    <small>
                      download
                    </small>
                  </span>
                  {" "}
                  <span className="bkit-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-user" />
                    </svg>
                    <small>
                      user
                    </small>
                  </span>
                  {" "}
                  <span className="bkit-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-doc" />
                    </svg>
                    <small>
                      document
                    </small>
                  </span>
                  {" "}
                  <span className="bkit-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-layers" />
                    </svg>
                    <small>
                      layers
                    </small>
                  </span>
                  {" "}
                  <span className="bkit-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-cube" />
                    </svg>
                    <small>
                      cube
                    </small>
                  </span>
                  {" "}
                  <span className="bkit-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-screen" />
                    </svg>
                    <small>
                      screen
                    </small>
                  </span>
                  {" "}
                  <span className="bkit-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-phone" />
                    </svg>
                    <small>
                      phone
                    </small>
                  </span>
                  {" "}
                  <span className="bkit-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-clock" />
                    </svg>
                    <small>
                      clock
                    </small>
                  </span>
                  {" "}
                  <span className="bkit-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-chart" />
                    </svg>
                    <small>
                      chart
                    </small>
                  </span>
                  {" "}
                  <span className="bkit-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-x" />
                    </svg>
                    <small>
                      close
                    </small>
                  </span>
                  {" "}
                </div>
                {" "}
                <p className="bkit-note">
                  Icons carry meaning, not decoration: one per card, at the top, in a tinted tile. Orange tiles mark the one thing in a group that matters most.
                </p>
                {" "}
              </article>
              {" "}
              {/* ---------- Product assets ---------- */}
              {" "}
              <article className="bkit-p" id="bk-product">
                {" "}
                <span className="bkit-n">
                  07
                </span>
                {" "}
                <h3>
                  Product assets
                </h3>
                {" "}
                <p className="bkit-lede">
                  Each product has a rendered icon. They are three-dimensional and lit from above, so they need room: do not crowd them or sit them on a busy photograph.
                </p>
                {" "}
                <div className="bkit-prods">
                  {" "}
                  <Link className="bkit-prod" to="/ds/ic-quiv.png" download="">
                    <img src="/ds/ic-quiv.png" alt="QUIV icon" />
                    <b>
                      QUIV
                    </b>
                    <span>
                      PNG · 512px
                    </span>
                  </Link>
                  {" "}
                  <Link className="bkit-prod" to="/ds/ic-heron.png" download="">
                    <img src="/ds/ic-heron.png" alt="HERON icon" />
                    <b>
                      HERON
                    </b>
                    <span>
                      PNG · 512px
                    </span>
                  </Link>
                  {" "}
                  <Link className="bkit-prod" to="/ds/ic-rategen.png" download="">
                    <img src="/ds/ic-rategen.png" alt="RateGen icon" />
                    <b>
                      RateGen
                    </b>
                    <span>
                      PNG · 512px
                    </span>
                  </Link>
                  {" "}
                  <Link className="bkit-prod" to="/ds/ic-mep.png" download="">
                    <img src="/ds/ic-mep.png" alt="Revit MEP icon" />
                    <b>
                      Revit MEP
                    </b>
                    <span>
                      PNG · 512px
                    </span>
                  </Link>
                  {" "}
                  <Link className="bkit-prod" to="/ds/ic-timepro.png" download="">
                    <img src="/ds/ic-timepro.png" alt="Time Pro icon" />
                    <b>
                      Time Pro
                    </b>
                    <span>
                      PNG · 512px
                    </span>
                  </Link>
                  {" "}
                  <Link className="bkit-prod" to="/ds/ic-civiq.png" download="">
                    <img src="/ds/ic-civiq.png" alt="CIVIQ icon" />
                    <b>
                      CIVIQ
                    </b>
                    <span>
                      PNG · 512px
                    </span>
                  </Link>
                  {" "}
                </div>
                {" "}
                <p className="bkit-note">
                  Product screenshots, UI stills and higher-resolution renders are available on request. Tell us the publication and the deadline and we will send the right crop rather than a folder.
                </p>
                {" "}
                <div className="bkit-dl">
                  {" "}
                  <a className="bkit-file" href="mailto:admin@adlmstudio.net?subject=ADLM%20product%20screenshots">
                    {" "}
                    <span className="bkit-ext">
                      ASK
                    </span>
                    <span>
                      <b>
                        Screenshots &amp; renders
                      </b>
                      <span>
                        admin@adlmstudio.net
                      </span>
                    </span>
                    {" "}
                    <svg viewBox="0 0 24 24">
                      <use href="#i-arrow" />
                    </svg>
                  </a>
                  {" "}
                </div>
                {" "}
              </article>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}{DsPromoSlot}{" "}
      <section className="cta">
        {" "}
        <div className="cta-bp">
        </div>
        <div className="cta-dots">
        </div>
        <div className="cta-g">
        </div>
        {" "}
        <h2>
          Writing about{" "}
          <span className="grad">
            ADLM?
          </span>
        </h2>
        {" "}
        <p className="ds-lede">
          Tell us the angle and the deadline. We can usually provide figures, screenshots or a spokesperson.
        </p>
        {" "}
        <div className="hero-cta">
          {" "}
          <a href="mailto:admin@adlmstudio.net" className="ds-btn btn-p">
            Press enquiries
          </a>
          {" "}
          <Link to="/testimonials" data-ds-page="customers" className="ds-btn btn-o">
            Customers
          </Link>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
