// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/products.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";
import DsPromoLive from "../DsPromoLive.jsx";

export default function DsProducts() {
  const DsPromoSlot = <DsPromoLive />;
  return (
    <>
      <header className="hero hero-tall">
        {" "}
        <div className="hero-b">
        </div>
        <div className="hero-g">
        </div>
        {" "}
        <div className="shell">
          {" "}
          <span className="eyebrow">
            The toolkit
          </span>
          {" "}
          <h1 className="h1-lines">
            {" "}
            <span className="ln">
              <span className="w" style={{ "--i": "0" }}>
                Six
              </span>
              {" "}
              <span className="w" style={{ "--i": "1" }}>
                tools.
              </span>
            </span>
            {" "}
            <span className="ln">
              <span className="w grad" style={{ "--i": "2" }}>
                One
              </span>
              {" "}
              <span className="w grad" style={{ "--i": "3" }}>
                rate
              </span>
              {" "}
              <span className="w grad" style={{ "--i": "4" }}>
                library.
              </span>
            </span>
            {" "}
          </h1>
          {" "}
          <p className="ds-lede">
            Pick the one that matches the drawing in front of you. They all price from the same library and export the same bill format.
          </p>
          {" "}
          <div className="hero-cta">
            {" "}
            <Link to="/pricing" data-ds-page="pricing" className="ds-btn btn-p">
              See pricing
            </Link>
            {" "}
            <a href="#gallery" className="ds-btn btn-o">
              Browse the tools
            </a>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      {/* GALLERY */}
      {" "}
      <section className="sec" id="gallery">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              Choose your tool
            </span>
            {" "}
            <h2>
              Every product,{" "}
              <span className="tone">
                one click away
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="gal">
            {" "}
            <article className="gcard tilt rise">
              {" "}
              <div className="gcard-bg">
                <img src="/ds/bg-quiv.jpg" alt="QUIV" />
              </div>
              {" "}
              <span className="host">
                3D takeoff · Autodesk Revit
              </span>
              {" "}
              <img className="picon" src="/ds/ic-quiv.png" alt="" aria-hidden="true" />
              <h3>
                QUIV
              </h3>
              {" "}
              <p>
                Measures every element in a Revit model and returns a priced, structured bill.
              </p>
              {" "}
              <p className="gprice">
                from{" "}
                <b>
                  ₦50,000
                </b>
                {" "}/ month
              </p>
              {" "}
              <Link to="/product/revit" data-ds-page="quiv" className="ds-btn btn-p ds-btn-sm">
                Explore QUIV{" "}
                <svg viewBox="0 0 24 24">
                  <use href="#i-arrow" />
                </svg>
              </Link>
              {" "}
            </article>
            {" "}
            <article className="gcard light-art tilt rise">
              {" "}
              <div className="gcard-bg">
                <img src="/ds/bg-heron.jpg" alt="HERON" />
              </div>
              {" "}
              <span className="host">
                2D takeoff · PlanSwift
              </span>
              {" "}
              <img className="picon" src="/ds/ic-heron.png" alt="" aria-hidden="true" />
              <h3>
                HERON
              </h3>
              {" "}
              <p>
                Scales and measures scanned or PDF drawings, then pushes to a linked Excel bill.
              </p>
              {" "}
              <p className="gprice">
                from{" "}
                <b>
                  ₦12,000
                </b>
                {" "}/ month
              </p>
              {" "}
              <Link to="/product/planswift" data-ds-page="heron" className="ds-btn btn-p ds-btn-sm">
                Explore HERON{" "}
                <svg viewBox="0 0 24 24">
                  <use href="#i-arrow" />
                </svg>
              </Link>
              {" "}
            </article>
            {" "}
            <article className="gcard tilt rise">
              {" "}
              <div className="gcard-bg">
                <img src="/ds/bg-rategen.jpg" alt="RateGen" />
              </div>
              {" "}
              <span className="host">
                Rate build-ups · Desktop
              </span>
              {" "}
              <img className="picon" src="/ds/ic-rategen.png" alt="" aria-hidden="true" />
              <h3>
                RateGen
              </h3>
              {" "}
              <p>
                500+ materials, 200+ labour items. The pricing library every other tool reads from.
              </p>
              {" "}
              <p className="gprice">
                from{" "}
                <b>
                  ₦8,000
                </b>
                {" "}/ month
              </p>
              {" "}
              <Link to="/product/rategen" data-ds-page="rategen" className="ds-btn btn-p ds-btn-sm">
                Explore RateGen{" "}
                <svg viewBox="0 0 24 24">
                  <use href="#i-arrow" />
                </svg>
              </Link>
              {" "}
            </article>
            {" "}
            <article className="gcard tilt rise">
              {" "}
              <div className="gcard-bg">
                <img src="/ds/bg-mep.jpg" alt="Revit MEP" />
              </div>
              {" "}
              <span className="host">
                MEP &amp; HVAC · Autodesk Revit
              </span>
              {" "}
              <img className="picon" src="/ds/ic-mep.png" alt="" aria-hidden="true" />
              <h3>
                Revit MEP
              </h3>
              {" "}
              <p>
                Ductwork, pipework, electrical and plumbing from the same model and workspace.
              </p>
              {" "}
              <p className="gprice">
                from{" "}
                <b>
                  ₦18,000
                </b>
                {" "}/ month
              </p>
              {" "}
              <Link to="/product/mep" data-ds-page="mep" className="ds-btn btn-p ds-btn-sm">
                Explore Revit MEP{" "}
                <svg viewBox="0 0 24 24">
                  <use href="#i-arrow" />
                </svg>
              </Link>
              {" "}
            </article>
            {" "}
            <article className="gcard light-art tilt rise">
              {" "}
              <div className="gcard-bg">
                <img src="/ds/bg-timepro.jpg" alt="Time Pro" />
              </div>
              {" "}
              <span className="host">
                Site productivity · Desktop &amp; mobile
              </span>
              {" "}
              <img className="picon" src="/ds/ic-timepro.png" alt="" aria-hidden="true" />
              <h3>
                Time Pro
              </h3>
              {" "}
              <p>
                Turns daily site output into realistic durations and a priced MS Project programme.
              </p>
              {" "}
              <p className="gprice">
                from{" "}
                <b>
                  ₦2,000
                </b>
                {" "}/ month
              </p>
              {" "}
              <Link to="/product/qs-takeoff" data-ds-page="timepro" className="ds-btn btn-p ds-btn-sm">
                Explore Time Pro{" "}
                <svg viewBox="0 0 24 24">
                  <use href="#i-arrow" />
                </svg>
              </Link>
              {" "}
            </article>
            {" "}
            <article className="gcard light-art tilt rise">
              {" "}
              <span className="pill pill-b gcard-soon">
                In development
              </span>
              {" "}
              <div className="gcard-bg">
                <img src="/ds/bg-civiq.jpg" alt="CIVIQ" />
              </div>
              {" "}
              <span className="host">
                Civil &amp; infrastructure · Civil 3D
              </span>
              {" "}
              <img className="picon" src="/ds/ic-civiq.png" alt="" aria-hidden="true" />
              <h3>
                CIVIQ
              </h3>
              {" "}
              <p>
                Model-based takeoff for roads, drainage and earthworks, inside Civil 3D.
              </p>
              {" "}
              <p className="gprice">
                Release notes go live with the first build
              </p>
              {" "}
              <Link to="/product/civil3d" data-ds-page="civiq" className="ds-btn btn-o ds-btn-sm">
                Preview the roadmap{" "}
                <svg viewBox="0 0 24 24">
                  <use href="#i-arrow" />
                </svg>
              </Link>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      {/* NOT PRODUCTS — the three things people mistake for products, said plainly */}
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              Comes with the account
            </span>
            {" "}
            <h2>
              Six products.{" "}
              <span className="tone">
                Everything else is the studio
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              These three are not sold, not licensed and not priced. They arrive with whatever you buy, and two of them arrive before you buy anything at all.
            </p>
            {" "}
          </div>
          {" "}
          <div className="bento">
            {" "}
            <article className="bento-c tilt rise">
              {" "}
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-bolt" />
                </svg>
              </div>
              {" "}
              <h4>
                Ada
              </h4>
              {" "}
              <p>
                The assistant. She answers on this website now, and inside your account later. She reads your library and your projects, never the internet.
              </p>
              {" "}
              <Link to="/ada" data-ds-page="ada" className="ds-btn btn-o ds-btn-sm">
                What Ada does{" "}
                <svg viewBox="0 0 24 24">
                  <use href="#i-arrow" />
                </svg>
              </Link>
              {" "}
            </article>
            {" "}
            <article className="bento-c tilt rise">
              {" "}
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-phone" />
                </svg>
              </div>
              {" "}
              <h4>
                Your phone
              </h4>
              {" "}
              <p>
                The same account away from the desk. Drawings need a workstation; rates, quantities and budgets do not. No second licence, no second login.
              </p>
              {" "}
              <Link to="/mobile" data-ds-page="mobile" className="ds-btn btn-o ds-btn-sm">
                On your phone{" "}
                <svg viewBox="0 0 24 24">
                  <use href="#i-arrow" />
                </svg>
              </Link>
              {" "}
            </article>
            {" "}
            <article className="bento-c tilt rise">
              {" "}
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-screen" />
                </svg>
              </div>
              {" "}
              <h4>
                The Installer Hub
              </h4>
              {" "}
              <p>
                Where every licence installs, activates and updates from. One account, one place, however many products you end up with.
              </p>
              {" "}
              <Link to="/how-it-works" data-ds-page="how-it-works" className="ds-btn btn-o ds-btn-sm">
                How ADLM works{" "}
                <svg viewBox="0 0 24 24">
                  <use href="#i-arrow" />
                </svg>
              </Link>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      {/* WHICH ONE — a decision aid, not a repeat of the landing page */}
      {" "}
      <div className="frame frame-soft">
        {" "}
        <section className="sec band-dark amb">
          {" "}
          <div className="shell">
            {" "}
            <div className="sec-head mid rise">
              {" "}
              <span className="eyebrow">
                Not sure which
              </span>
              {" "}
              <h2>
                Start from the drawing{" "}
                <span className="grad">
                  you were given
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                Most people already know which of these describes their week.
              </p>
              {" "}
            </div>
            {" "}
            <div className="pick" id="pick">
              {" "}
              <article className="pick-c on" tabIndex="0">
                {" "}
                <span className="pick-n">
                  01
                </span>
                {" "}
                <div className="pick-art">
                  <img src="/ds/quiv-dashboard.jpg" alt="QUIV measuring elements inside Revit" loading="lazy" />
                </div>
                {" "}
                <div className="pick-body">
                  {" "}
                  <h4>
                    You were given a model
                  </h4>
                  {" "}
                  <p>
                    Revit hands you geometry. Measure the elements themselves with{" "}
                    <strong>
                      QUIV
                    </strong>
                    {" "}— the element ID stays on the bill line, so any query has an answer.
                  </p>
                  {" "}
                </div>
                {" "}
              </article>
              {" "}
              <article className="pick-c" tabIndex="0">
                {" "}
                <span className="pick-n">
                  02
                </span>
                {" "}
                <div className="pick-art">
                  <img src="/ds/heron-art.jpg" alt="HERON scaling and measuring a flat drawing" loading="lazy" />
                </div>
                {" "}
                <div className="pick-body">
                  {" "}
                  <h4>
                    You were given flat drawings
                  </h4>
                  {" "}
                  <p>
                    PDFs, scans, or a drawing photographed on site. Scale it once and measure it with{" "}
                    <strong>
                      HERON
                    </strong>
                    {" "}using the ADLM templates.
                  </p>
                  {" "}
                </div>
                {" "}
              </article>
              {" "}
              <article className="pick-c" tabIndex="0">
                {" "}
                <span className="pick-n">
                  03
                </span>
                {" "}
                <div className="pick-art">
                  <img src="/ds/bg-rategen.jpg" alt="RateGen building a rate from materials and labour" loading="lazy" />
                </div>
                {" "}
                <div className="pick-body">
                  {" "}
                  <h4>
                    You have quantities, not rates
                  </h4>
                  {" "}
                  <p>
                    If the measuring is done and the argument is about price,{" "}
                    <strong>
                      RateGen
                    </strong>
                    {" "}builds the rate from materials and labour you can show.
                  </p>
                  {" "}
                </div>
                {" "}
              </article>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </div>
      {" "}
      {/* FAQ */}
      {" "}
      <section className="sec-half blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "38px" }}>
            {" "}
            <span className="eyebrow">
              Questions
            </span>
            {" "}
            <h2>
              About the tools
            </h2>
            {" "}
          </div>
          {" "}
          <div className="faq rise">
            {" "}
            <details open={true}>
              {" "}
              <summary>
                Do I need all of them?
              </summary>
              {" "}
              <div className="faq-a">
                No. Most people buy one takeoff tool plus RateGen — the takeoff tool measures, RateGen prices. Add others when the work demands it.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Do I need Revit or PlanSwift already?
              </summary>
              {" "}
              <div className="faq-a">
                Yes for QUIV, Revit MEP and HERON — they are plugins that dock into software you already run. RateGen and Time Pro are standalone and need nothing else.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Can quantities from different tools end up in one bill?
              </summary>
              {" "}
              <div className="faq-a">
                Yes. Item codes and units are shared, so a wall measured in Revit and a wall measured on a PDF collect into the same bill line rather than two spreadsheets.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                What happens when I change machine?
              </summary>
              {" "}
              <div className="faq-a">
                Licences are per PC but assigned from your ADLM account, so you can move a seat to a new laptop yourself. Your rates and projects are already in the account.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                When will CIVIQ ship?
              </summary>
              {" "}
              <div className="faq-a">
                It is in active development for AutoCAD Civil 3D. Release notes appear on the What's New page the day the first build lands.
              </div>
              {" "}
            </details>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}{DsPromoSlot}{" "}
      <section className="cta">
        {" "}
        <div className="cta-bp">
        </div>
        <div className="cta-dots">
        </div>
        <div className="cta-g">
        </div>
        {" "}
        <h2>
          See it on{" "}
          <span className="grad">
            your project
          </span>
        </h2>
        {" "}
        <p className="ds-lede">
          We'll run the toolkit against one of your live jobs — your drawings, your rates.
        </p>
        {" "}
        <div className="hero-cta">
          {" "}
          <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
            Book a demo
          </Link>
          {" "}
          <Link to="/pricing" data-ds-page="pricing" className="ds-btn btn-o">
            See pricing
          </Link>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
