// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/rategen.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";
import DsPromoLive from "../DsPromoLive.jsx";

export default function DsRateGenPage({ d }) {
  const DsPromoSlot = <DsPromoLive />;
  return (
    <>
      <header className="phero">
        {" "}
        <div className="phero-bg">
          <img src="/ds/bg-rategen.jpg" alt="RateGen" />
        </div>
        {" "}
        <div className="phero-in">
          {" "}
          <span className="host">
            Rate build-ups · Desktop
          </span>
          {" "}
          <h1>
            {" "}
            <span className="w" style={{ "--i": "0" }}>
              Rates
            </span>
            {" "}
            <span className="w" style={{ "--i": "1" }}>
              you
            </span>
            {" "}
            <span className="w" style={{ "--i": "2" }}>
              can
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "3" }}>
              show
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "4" }}>
              your
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "5" }}>
              working
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "6" }}>
              for.
            </span>
            {" "}
          </h1>
          {" "}
          <p className="ds-lede">
            500+ materials, 200+ labour items, and a build-up behind every figure you quote.
          </p>
          {" "}
          <div className="hero-cta">
            {" "}
            <Link to="/purchase" data-ds-page="cart" className="ds-btn btn-p">
              Get RateGen
            </Link>
            {" "}
            <Link to="/pricing" data-ds-page="pricing" className="ds-btn btn-o">
              See pricing
            </Link>
            {" "}
          </div>
          {" "}
          <p className="phero-note">
            <span className="pulse">
            </span>
            Latest v2.5.0 · desktop, syncs to every plugin
          </p>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              Core features
            </span>
            {" "}
            <h2>
              What RateGen does{" "}
              <span className="tone">
                and how it does it
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="fgrid">
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz">
                  <div className="vz-panel">
                    {" "}
                    <div className="vz-row">
                      <span>
                        Cement · 6.4 bags
                      </span>
                      <b>
                        ₦6,400
                      </b>
                    </div>
                    {" "}
                    <div className="vz-row">
                      <span>
                        Sharp sand · 0.44 m³
                      </span>
                      <b>
                        ₦1,850
                      </b>
                    </div>
                    {" "}
                    <div className="vz-row">
                      <span>
                        Granite 20mm · 0.88 m³
                      </span>
                      <b>
                        ₦3,720
                      </b>
                    </div>
                    {" "}
                    <div className="vz-row hl">
                      <span>
                        Waste &amp; sundries · 3%
                      </span>
                      <b>
                        ₦412
                      </b>
                    </div>
                    {" "}
                    <div className="vz-row">
                      <span>
                        Labour · 0.6 day gang
                      </span>
                      <b>
                        ₦1,768
                      </b>
                    </div>
                    {" "}
                    <div className="vz-sum">
                      <span>
                        Rate / m³
                      </span>
                      <b>
                        ₦14,150
                      </b>
                    </div>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Traceability
                </span>
                {" "}
                <h4>
                  Every rate shows its working
                </h4>
                {" "}
                <p>
                  A rate is never a number you typed. It is materials, waste, labour output and a margin: each editable, each visible, each defensible in a meeting.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz">
                  <div className="vz-panel" style={{ marginBottom: "10px" }}>
                    {" "}
                    <div className="vz-row">
                      <span>
                        Search materials
                      </span>
                      <b>
                        512
                      </b>
                    </div>
                  </div>
                  {" "}
                  <div style={{ display: "flex", flexWrap: "wrap", gap: "7px", justifyContent: "center" }}>
                    {" "}
                    <span className="vz-chip">
                      Cement
                    </span>
                    <span className="vz-chip on">
                      Sandcrete block
                    </span>
                    {" "}
                    <span className="vz-chip">
                      Granite
                    </span>
                    <span className="vz-chip">
                      Rebar
                    </span>
                    {" "}
                    <span className="vz-chip">
                      POP
                    </span>
                    <span className="vz-chip">
                      Emulsion
                    </span>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Library depth
                </span>
                {" "}
                <h4>
                  500+ materials, 200+ labour items
                </h4>
                {" "}
                <p>
                  A starting library built for Nigerian construction, not converted from somewhere else. Add your own items and they behave exactly like the built-in ones.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz">
                  <div className="vz-locs">
                    {" "}
                    <div className="on">
                      <span>
                        South West
                      </span>
                      <b>
                        ₦14,150 / m³
                      </b>
                    </div>
                    {" "}
                    <div>
                      <span>
                        North Central
                      </span>
                      <b>
                        ₦15,140 / m³
                      </b>
                    </div>
                    {" "}
                    <div>
                      <span>
                        North East
                      </span>
                      <b>
                        ₦16,200 / m³
                      </b>
                    </div>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Localisation
                </span>
                {" "}
                <h4>
                  Prices that know where you are
                </h4>
                {" "}
                <p>
                  The same specification costs differently in the South West and the North East. Set your geopolitical zone once, on your ADLM profile, and every rate you see is priced through it: in naira, dollars or five other currencies.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz">
                  <div className="vz-sync">
                    {" "}
                    <span className="hub">
                      <svg viewBox="0 0 24 24">
                        <use href="#i-cloud" />
                      </svg>
                    </span>
                    {" "}
                    <span className="outs">
                      <span className="vz-chip on">
                        QUIV
                      </span>
                      <span className="vz-chip on">
                        HERON
                      </span>
                      {" "}
                      <span className="vz-chip on">
                        Revit MEP
                      </span>
                    </span>
                  </div>
                  {" "}
                  <div style={{ textAlign: "center", marginTop: "12px" }}>
                    <span className="vz-chip">
                      synced · v2.5.0
                    </span>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Shared library
                </span>
                {" "}
                <h4>
                  One library, every tool
                </h4>
                {" "}
                <p>
                  Change a rate once and it reaches QUIV, HERON and Revit MEP through your ADLM account. No copies, no version arguments.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="chat">
                  <div className="chat-bar">
                    {" "}
                    <span className="chat-txt">
                      Build a rate for 150mm blockwork wall, rendered both sides
                    </span>
                    {" "}
                    <span className="chat-send">
                      <svg viewBox="0 0 24 24">
                        <path d="M4 12h14m0 0l-5-5m5 5l-5 5" />
                      </svg>
                    </span>
                  </div>
                  {" "}
                  <div className="chat-reply">
                    <span className="chat-ai">
                      <svg viewBox="0 0 24 24">
                        <use href="#i-bolt" />
                      </svg>
                    </span>
                    <div className="chat-body">
                      {" "}
                      <div className="vz-row">
                        <span>
                          Blocks · 150mm
                        </span>
                        <b>
                          10 no / m²
                        </b>
                      </div>
                      {" "}
                      <div className="vz-row">
                        <span>
                          Mortar 1:6
                        </span>
                        <b>
                          0.02 m³
                        </b>
                      </div>
                      {" "}
                      <div className="vz-row">
                        <span>
                          Render · 2 sides
                        </span>
                        <b>
                          2.00 m²
                        </b>
                      </div>
                      {" "}
                      <div className="vz-sum">
                        <span>
                          Proposed rate
                        </span>
                        <b>
                          ₦9,480 / m²
                        </b>
                      </div>
                      {" "}
                      <span className="chat-tick">
                        <svg viewBox="0 0 24 24">
                          <use href="#i-check" />
                        </svg>
                        All items from your library, edit before saving
                      </span>
                      {" "}
                    </div>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Speed
                </span>
                {" "}
                <h4>
                  Build with AI when you're starting from nothing
                </h4>
                {" "}
                <p>
                  Describe an item of work in plain English and RateGen proposes a build-up from your own library, which you then check, edit and own. It suggests; you decide.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <div className="frame frame-soft">
        {" "}
        <section className="sec band-dark amb">
          {" "}
          <div className="shell">
            {" "}
            <div className="sec-head mid rise">
              {" "}
              <span className="eyebrow">
                The output
              </span>
              {" "}
              <h2>
                The number, and{" "}
                <span className="grad">
                  the argument behind it
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                When a client challenges a rate, you open the build-up rather than defend a guess.
              </p>
              {" "}
            </div>
            {" "}
            <div className="chain rise">
              {" "}
              <article className="chain-c">
                {" "}
                <span className="chain-n">
                  01
                </span>
                {" "}
                <h3>
                  What most people send
                </h3>
                {" "}
                <div className="frag">
                  {" "}
                  <div className="frag-t">
                    Bill line
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Blockwork 225mm
                    </span>
                    <span className="frag-v">
                      ₦15,120 / m²
                    </span>
                    {" "}
                  </div>
                  {" "}
                </div>
              </article>
              {" "}
              <span className="chain-link" aria-hidden="true">
              </span>
              {" "}
              <article className="chain-c">
                {" "}
                <span className="chain-n">
                  02
                </span>
                {" "}
                <h3>
                  What RateGen sends
                </h3>
                {" "}
                <div className="frag">
                  {" "}
                  <div className="frag-t">
                    Bill description
                  </div>
                  {" "}
                  <div className="pre">
                    Rate build-up · blockwork 225mm in cement mortar (1:6)
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Materials + waste + labour
                    </span>
                    <span className="frag-v">
                      ₦15,120 / m²
                    </span>
                    {" "}
                  </div>
                  {" "}
                </div>
              </article>
              {" "}
              <span className="chain-link" aria-hidden="true">
              </span>
              {" "}
              <article className="chain-c">
                {" "}
                <span className="chain-n">
                  03
                </span>
                {" "}
                <h3>
                  What the client receives
                </h3>
                {" "}
                <div className="frag">
                  {" "}
                  <div className="frag-t">
                    Rate build-up · exported
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Materials
                    </span>
                    <span className="frag-v">
                      ₦12,382
                    </span>
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Waste &amp; sundries · 3%
                    </span>
                    <span className="frag-v">
                      ₦412
                    </span>
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Labour · blocklayer gang
                    </span>
                    <span className="frag-v">
                      ₦1,768
                    </span>
                  </div>
                  {" "}
                  <div className="frag-sum">
                    <span>
                      Rate / m²
                    </span>
                    <span className="frag-v">
                      ₦15,120
                    </span>
                    {" "}
                  </div>
                  {" "}
                </div>
              </article>
              {" "}
            </div>
            {" "}
            <p className="chain-note">
              One source, one summary. Nothing is retyped between the measurement and the number you send.
            </p>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </div>
      {" "}
      <section className="sec-half blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise" style={{ marginBottom: "36px" }}>
            {" "}
            <span className="eyebrow">
              Compatibility
            </span>
            {" "}
            <h2>
              Where RateGen{" "}
              <span className="tone">
                fits in your setup
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="compat">
            {" "}
            <div className="compat-c rise">
              <h6>
                Platform
              </h6>
              {" "}
              <div className="big">
                Windows desktop
              </div>
              {" "}
              <div className="compat-tags">
                <span>
                  Standalone
                </span>
              </div>
            </div>
            {" "}
            <div className="compat-c rise">
              <h6>
                Feeds
              </h6>
              {" "}
              <div className="big">
                QUIV · HERON · MEP
              </div>
              {" "}
              <div className="compat-tags">
                <span>
                  Through your ADLM account
                </span>
              </div>
            </div>
            {" "}
            <div className="compat-c rise">
              <h6>
                Library
              </h6>
              {" "}
              <div className="big">
                500+ materials
              </div>
              {" "}
              <div className="compat-tags">
                <span>
                  200+ labour items
                </span>
              </div>
            </div>
            {" "}
            <div className="compat-c rise">
              <h6>
                Standards
              </h6>
              {" "}
              <div className="big">
                BESMM4R · NRM2
              </div>
              {" "}
              <div className="compat-tags">
                <span>
                  Location-based pricing
                </span>
              </div>
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half alt amb blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "36px" }}>
            {" "}
            <span className="eyebrow">
              Pricing
            </span>
            {" "}
            <h2>
              {d.monthly} a month,{" "}
              <span className="tone">
                per PC
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              {d.priceLine}
            </p>
            {" "}
            <div className="hero-cta" style={{ justifyContent: "center" }}>
              {" "}
              <Link to="/purchase" data-ds-page="cart" className="ds-btn btn-p">
                Get RateGen
              </Link>
              {" "}
              <Link to="/contact" data-ds-page="contact" className="ds-btn btn-o">
                Build a quote
              </Link>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half blend" id="updates">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "40px" }}>
            {" "}
            <span className="eyebrow">
              Release history
            </span>
            {" "}
            <h2>
              What's changed{" "}
              <span className="tone">
                over time
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              Every release, in plain English: what shipped, what improved, what was fixed.
            </p>
            {" "}
          </div>
          {" "}{d.releases}{" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "38px" }}>
            {" "}
            <span className="eyebrow">
              Questions
            </span>
            {" "}
            <h2>
              About RateGen
            </h2>
            {" "}
          </div>
          {" "}
          <div className="faq rise">
            {" "}
            <details open={true}>
              {" "}
              <summary>
                Can I use my own rates instead of the library?
              </summary>
              {" "}
              <div className="faq-a">
                Yes. Add your own materials and labour items, or edit the built-in ones. Custom items behave identically and sync the same way.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Does RateGen measure anything?
              </summary>
              {" "}
              <div className="faq-a">
                No. It prices. Measuring is QUIV, HERON or Revit MEP: RateGen is the library they all read from.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                How often are the built-in prices updated?
              </summary>
              {" "}
              <div className="faq-a">
                The library ships with a baseline and you maintain it against your own suppliers. Location factors help, but your own quotes always win.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Can a team share one library?
              </summary>
              {" "}
              <div className="faq-a">
                Yes. Rates sync through the ADLM account, so a firm can hold one library rather than six spreadsheets.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Is the AI build-up trustworthy?
              </summary>
              {" "}
              <div className="faq-a">
                It only proposes items that exist in your library, and nothing is saved until you accept it. Treat it as a first draft, not an answer.
              </div>
              {" "}
            </details>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}{DsPromoSlot}{" "}
      <section className="cta">
        {" "}
        <div className="cta-bp">
        </div>
        <div className="cta-dots">
        </div>
        <div className="cta-g">
        </div>
        {" "}
        <h2>
          See it on{" "}
          <span className="grad">
            your project
          </span>
        </h2>
        {" "}
        <p className="ds-lede">
          We'll run RateGen against one of your live jobs, your drawings, your rates, your bill format.
        </p>
        {" "}
        <div className="hero-cta">
          {" "}
          <Link to="/purchase" data-ds-page="cart" className="ds-btn btn-p">
            Get RateGen
          </Link>
          {" "}
          <Link to="/products" data-ds-page="products" className="ds-btn btn-o">
            All products
          </Link>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
