// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/solutions-firms.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";
import DsPromoLive from "../DsPromoLive.jsx";

export default function DsSolutionsFirms() {
  const DsPromoSlot = <DsPromoLive />;
  return (
    <>
      <header className="phero">
        {" "}
        <div className="phero-bg">
          <img src="/ds/sol-firms.jpg" alt="" />
        </div>
        {" "}
        <div className="phero-in">
          {" "}
          <span className="host">
            For firms &amp; consultancies
          </span>
          {" "}
          <h1>
            {" "}
            <span className="w" style={{ "--i": "0" }}>
              One
            </span>
            {" "}
            <span className="w" style={{ "--i": "1" }}>
              rate
            </span>
            {" "}
            <span className="w" style={{ "--i": "2" }}>
              library.
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "3" }}>
              Every
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "4" }}>
              surveyor
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "5" }}>
              on
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "6" }}>
              it.
            </span>
            {" "}
          </h1>
          {" "}
          <p className="ds-lede">
            The problem at firm scale isn't measuring. It's six people pricing the same item six different ways.
          </p>
          {" "}
          <div className="hero-cta">
            {" "}
            <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
              Book a demo
            </Link>
            {" "}
            <Link to="/pricing" data-ds-page="pricing" className="ds-btn btn-o">
              See pricing
            </Link>
            {" "}
          </div>
          {" "}
          <div className="statframe phero-stats rise">
            {" "}
            <div className="stat">
              {" "}
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-layers" />
                </svg>
              </div>
              {" "}
              <b>
                6
              </b>
              <span>
                products, one library
              </span>
            </div>
            {" "}
            <div className="stat">
              {" "}
              <div className="ico ico-a">
                <svg viewBox="0 0 24 24">
                  <use href="#i-clock" />
                </svg>
              </div>
              {" "}
              <b>
                5
              </b>
              <span>
                min to move a seat
              </span>
            </div>
            {" "}
            <div className="stat">
              {" "}
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-doc" />
                </svg>
              </div>
              {" "}
              <b>
                1
              </b>
              <span>
                bill format
              </span>
            </div>
            {" "}
            <div className="stat">
              {" "}
              <div className="ico ico-a">
                <svg viewBox="0 0 24 24">
                  <use href="#i-cloud" />
                </svg>
              </div>
              {" "}
              <b>
                30
              </b>
              <span>
                events delivered
              </span>
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="psplit rise">
            {" "}
            <div className="ps-art">
              <img src="/ds/ab-office.jpg" alt="" loading="lazy" />
            </div>
            {" "}
            <div className="ps-copy">
              {" "}
              <span className="eyebrow">
                The problem
              </span>
              {" "}
              <h2>
                What usually{" "}
                <span className="grad">
                  goes wrong
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                At firm scale the measuring is rarely what breaks. It is everything around it, six surveyors, six spreadsheets, and no single version of a rate anyone can point at.
              </p>
              {" "}
              <ul className="ps-list">
                {" "}
                <li>
                  {" "}
                  <span className="ps-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                  </span>
                  {" "}
                  <div>
                    <b>
                      Rates that disagree
                    </b>
                    <p>
                      Every surveyor keeps their own spreadsheet, so two bills for the same job never quite reconcile.
                    </p>
                  </div>
                  {" "}
                </li>
                {" "}
                <li>
                  {" "}
                  <span className="ps-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                  </span>
                  {" "}
                  <div>
                    <b>
                      Onboarding takes months
                    </b>
                    <p>
                      New starters learn your house method by osmosis, from whoever happens to be free.
                    </p>
                  </div>
                  {" "}
                </li>
                {" "}
                <li>
                  {" "}
                  <span className="ps-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                  </span>
                  {" "}
                  <div>
                    <b>
                      No audit trail
                    </b>
                    <p>
                      When a client challenges a figure, finding where it came from becomes its own project.
                    </p>
                  </div>
                  {" "}
                </li>
                {" "}
              </ul>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              What we do about it
            </span>
            {" "}
            <h2>
              How ADLM{" "}
              <span className="tone">
                actually helps
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="mbento mb3">
            {" "}
            <article className="mtile m-art m-w2 tilt rise">
              {" "}
              <img src="/ds/sol-database.jpg" alt="" loading="lazy" />
              {" "}
              <div className="mt">
                <span className="ico" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                </span>
                {" "}
                <h4>
                  A single shared library
                </h4>
                {" "}
                <p style={{ maxWidth: "44ch" }}>
                  RateGen holds one library for the whole practice. Change a rate once and every open budget re-prices to it.
                </p>
              </div>
              {" "}
            </article>
            {" "}
            <article className="mtile solid tilt rise">
              {" "}
              <div className="mid">
                {" "}
                <span className="ico" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                </span>
                {" "}
                <h4>
                  Seats you manage yourself
                </h4>
                {" "}
                <p style={{ maxWidth: "44ch" }}>
                  Assign and move licences from your ADLM account as people join, leave or change laptop.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="mtile m-art tilt rise">
              {" "}
              <img src="/ds/sol-shared-export.jpg" alt="" loading="lazy" />
              {" "}
              <div className="mt">
                <span className="ico" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                </span>
                {" "}
                <h4>
                  One bill format
                </h4>
                {" "}
                <p style={{ maxWidth: "44ch" }}>
                  Everyone exports the same QS-format bill, so your output looks like your practice.
                </p>
              </div>
              {" "}
            </article>
            {" "}
            <article className="mtile ds-accent m-w2 tilt rise">
              {" "}
              <div className="mid">
                {" "}
                <span className="ico ico-a" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                </span>
                {" "}
                <h4>
                  Training built in
                </h4>
                {" "}
                <p style={{ maxWidth: "44ch" }}>
                  On-site training on your own projects, so the method lands with the tool: thirty events delivered so far.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="plx">
        {" "}
        <div className="plx-bg">
          <img src="/ds/ls-crane.jpg" alt="" />
        </div>
        {" "}
        <div className="plx-in rise">
          {" "}
          <span className="eyebrow">
            Rollout
          </span>
          {" "}
          <h2>
            Deployed across a practice,{" "}
            <span className="grad">
              not installed one desk at a time
            </span>
          </h2>
          {" "}
          <p className="ds-lede" style={{ marginTop: "18px" }}>
            Larger teams get an onboarding plan, seat allocation and on-site training rather than a download link.
          </p>
          {" "}
          <div className="hero-cta" style={{ justifyContent: "flex-start" }}>
            {" "}
            <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
              Talk to us
            </Link>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "38px" }}>
            {" "}
            <span className="eyebrow">
              Questions
            </span>
            <h2>
              Common questions
            </h2>
            {" "}
          </div>
          {" "}
          <div className="faq rise">
            {" "}
            <details open={true}>
              {" "}
              <summary>
                How does multi-seat pricing work?
              </summary>
              {" "}
              <div className="faq-a">
                Licences are per PC and priced per product. Tell us the mix and the headcount and we'll come back with a number and a rollout plan.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Can we keep our own rates?
              </summary>
              {" "}
              <div className="faq-a">
                Yes. You should. The built-in library is a starting point; most firms replace it with their own within weeks.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Who administers the seats?
              </summary>
              {" "}
              <div className="faq-a">
                You do, from the ADLM account. No ticket needed to move a licence to a new machine.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Do you help with the rollout?
              </summary>
              {" "}
              <div className="faq-a">
                Yes. Larger deployments get an onboarding plan and on-site training rather than a download link.
              </div>
              {" "}
            </details>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec sform-sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sform">
            {" "}
            <div className="sform-copy">
              {" "}
              <span className="eyebrow">
                Talk to us
              </span>
              {" "}
              <h2>
                Tell us how your{" "}
                <span className="grad">
                  practice works
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                Seat counts, shared rate libraries, the bill format you have to hand over. We will tell you honestly whether ADLM fits.
              </p>
              {" "}
              <ul className="sform-pts">
                {" "}
                <li>
                  <span className="ico ico-sm">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                  </span>
                  A real surveyor replies, not a bot
                </li>
                {" "}
                <li>
                  <span className="ico ico-sm">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-clock" />
                    </svg>
                  </span>
                  Usually within one working day
                </li>
                {" "}
                <li>
                  <span className="ico ico-sm">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-cloud" />
                    </svg>
                  </span>
                  No obligation, no drip campaign
                </li>
                {" "}
              </ul>
              {" "}
              <div className="sform-meta">
                {" "}
                <a href="mailto:admin@adlmstudio.net">
                  admin@adlmstudio.net
                </a>
                {" "}
                <span>
                  Lagos, Nigeria
                </span>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <form className="sform-card" action="/checkout/thanks" method="get">
              {" "}
              <input type="hidden" name="topic" value="Firms &amp; consultancies" />
              {" "}
              <div className="ds-field">
                {" "}
                <label htmlFor="sf-name">
                  Your name
                </label>
                {" "}
                <input id="sf-name" name="name" type="text" autoComplete="name" placeholder="Ada Okonkwo" required={true} />
                {" "}
              </div>
              {" "}
              <div className="ds-field">
                {" "}
                <label htmlFor="sf-email">
                  Work email
                </label>
                {" "}
                <input id="sf-email" name="email" type="email" autoComplete="email" placeholder="you@firm.com" required={true} />
                {" "}
              </div>
              {" "}
              <div className="ds-field">
                {" "}
                <label htmlFor="sf-org">
                  Organisation{" "}
                  <span className="opt">
                    optional
                  </span>
                </label>
                {" "}
                <input id="sf-org" name="org" type="text" autoComplete="organization" placeholder="Firm, school or agency" />
                {" "}
              </div>
              {" "}
              <div className="ds-field">
                {" "}
                <label htmlFor="sf-msg">
                  What do you need?
                </label>
                {" "}
                <textarea id="sf-msg" name="message" rows="4" placeholder="What you measure, what you hand over, and where it hurts." required={true}>
                </textarea>
                {" "}
              </div>
              {" "}
              <button type="submit" className="ds-btn btn-p btn-full">
                Send the message
              </button>
              {" "}
              <p className="sform-note">
                We reply from a real address. No list, no reselling.
              </p>
              {" "}
            </form>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}{DsPromoSlot}{" "}
      <section className="cta">
        {" "}
        <div className="cta-bp">
        </div>
        <div className="cta-dots">
        </div>
        <div className="cta-g">
        </div>
        {" "}
        <h2>
          Let's talk about{" "}
          <span className="grad">
            your situation
          </span>
        </h2>
        {" "}
        <p className="ds-lede">
          Tell us how your team works today and we'll tell you honestly whether we help.
        </p>
        {" "}
        <div className="hero-cta">
          {" "}
          <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
            Talk to us
          </Link>
          {" "}
          <Link to="/pricing" data-ds-page="pricing" className="ds-btn btn-o">
            See pricing
          </Link>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
