// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/solutions-institutions.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";
import DsPromoLive from "../DsPromoLive.jsx";

export default function DsSolutionsInstitutions() {
  const DsPromoSlot = <DsPromoLive />;
  return (
    <>
      <header className="phero">
        {" "}
        <div className="phero-bg">
          <img src="/ds/sol-engineer.jpg" alt="" />
        </div>
        {" "}
        <div className="phero-in">
          {" "}
          <span className="host">
            For institutions
          </span>
          {" "}
          <h1>
            {" "}
            <span className="w" style={{ "--i": "0" }}>
              Training
            </span>
            {" "}
            <span className="w" style={{ "--i": "1" }}>
              a
            </span>
            {" "}
            <span className="w" style={{ "--i": "2" }}>
              whole
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "3" }}>
              room
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "4" }}>
              at
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "5" }}>
              a
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "6" }}>
              time.
            </span>
            {" "}
          </h1>
          {" "}
          <p className="ds-lede">
            Chapter workshops, university programmes and departmental training: delivered on site, on your own projects.
          </p>
          {" "}
          <div className="hero-cta">
            {" "}
            <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
              Request a programme
            </Link>
            {" "}
            <Link to="/learn#events" data-ds-page="learn" className="ds-btn btn-o">
              See past events
            </Link>
            {" "}
          </div>
          {" "}
          <div className="statframe phero-stats rise">
            {" "}
            <div className="stat">
              {" "}
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-layers" />
                </svg>
              </div>
              {" "}
              <b>
                30
              </b>
              <span>
                events delivered
              </span>
            </div>
            {" "}
            <div className="stat">
              {" "}
              <div className="ico ico-a">
                <svg viewBox="0 0 24 24">
                  <use href="#i-clock" />
                </svg>
              </div>
              {" "}
              <b>
                3,100+
              </b>
              <span>
                professionals trained
              </span>
            </div>
            {" "}
            <div className="stat">
              {" "}
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-doc" />
                </svg>
              </div>
              {" "}
              <b>
                25+
              </b>
              <span>
                organisations
              </span>
            </div>
            {" "}
            <div className="stat">
              {" "}
              <div className="ico ico-a">
                <svg viewBox="0 0 24 24">
                  <use href="#i-cloud" />
                </svg>
              </div>
              {" "}
              <b>
                10+
              </b>
              <span>
                countries reached
              </span>
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="psplit rise">
            {" "}
            <div className="ps-art">
              <img src="/ds/sol-institutions.jpg" alt="" loading="lazy" />
            </div>
            {" "}
            <div className="ps-copy">
              {" "}
              <span className="eyebrow">
                The problem
              </span>
              {" "}
              <h2>
                What usually{" "}
                <span className="grad">
                  goes wrong
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                Training is easy to book and hard to make stick. Sessions fail for the same three reasons, long before anyone opens the software.
              </p>
              {" "}
              <ul className="ps-list">
                {" "}
                <li>
                  {" "}
                  <span className="ps-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                  </span>
                  {" "}
                  <div>
                    <b>
                      Generic training doesn't land
                    </b>
                    <p>
                      A vendor demo is not a curriculum, and a room of professionals can tell the difference immediately.
                    </p>
                  </div>
                  {" "}
                </li>
                {" "}
                <li>
                  {" "}
                  <span className="ps-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                  </span>
                  {" "}
                  <div>
                    <b>
                      Mixed ability in one room
                    </b>
                    <p>
                      Some have never opened Revit; some run BIM already. One pace fails both.
                    </p>
                  </div>
                  {" "}
                </li>
                {" "}
                <li>
                  {" "}
                  <span className="ps-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                  </span>
                  {" "}
                  <div>
                    <b>
                      Nothing survives the session
                    </b>
                    <p>
                      Everyone leaves impressed and nobody changes how they work on Monday.
                    </p>
                  </div>
                  {" "}
                </li>
                {" "}
              </ul>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              What we do about it
            </span>
            {" "}
            <h2>
              How ADLM{" "}
              <span className="tone">
                actually helps
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="mbento mb3">
            {" "}
            <article className="mtile solid m-w2 tilt rise">
              {" "}
              <div className="mid">
                {" "}
                <span className="ico" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                </span>
                {" "}
                <h4>
                  A programme, not a demo
                </h4>
                {" "}
                <p style={{ maxWidth: "44ch" }}>
                  Structured across sessions with practical tasks between them and a defined outcome, the NIQS Foundation ran two full days.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="mtile m-art tilt rise">
              {" "}
              <img src="/ds/sol-zheng.jpg" alt="" loading="lazy" />
              {" "}
              <div className="mt">
                <span className="ico" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                </span>
                {" "}
                <h4>
                  Delivered where you are
                </h4>
                {" "}
                <p style={{ maxWidth: "44ch" }}>
                  On site, online, or hybrid. We have run all three, including a Nigeria–Tanzania collaboration.
                </p>
              </div>
              {" "}
            </article>
            {" "}
            <article className="mtile ds-accent tilt rise">
              {" "}
              <div className="mid">
                {" "}
                <span className="ico ico-a" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                </span>
                {" "}
                <h4>
                  Built on your own work
                </h4>
                {" "}
                <p style={{ maxWidth: "44ch" }}>
                  Sessions use the institution's own drawings and projects wherever possible.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="mtile m-art m-w2 tilt rise">
              {" "}
              <img src="/ds/ab-crew.jpg" alt="" loading="lazy" />
              {" "}
              <div className="mt">
                <span className="ico" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                </span>
                {" "}
                <h4>
                  A record you can check
                </h4>
                {" "}
                <p style={{ maxWidth: "44ch" }}>
                  NIQS chapters, NIOB, Federal Airport Authority, JABU, Rivers State University, Yaba Tech.
                </p>
              </div>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="plx">
        {" "}
        <div className="plx-bg">
          <img src="/ds/ev3.jpg" alt="" />
        </div>
        {" "}
        <div className="plx-in rise">
          {" "}
          <span className="eyebrow">
            Scale
          </span>
          {" "}
          <h2>
            From a department of six{" "}
            <span className="grad">
              to a conference of 1,480
            </span>
          </h2>
          {" "}
          <p className="ds-lede" style={{ marginTop: "18px" }}>
            The Big 5 Construct Nigeria panel drew 1,480 attendees. A departmental session might be eight people. Both get a programme built for the room.
          </p>
          {" "}
          <div className="hero-cta" style={{ justifyContent: "flex-start" }}>
            {" "}
            <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
              Talk to us
            </Link>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "38px" }}>
            {" "}
            <span className="eyebrow">
              Questions
            </span>
            <h2>
              Common questions
            </h2>
            {" "}
          </div>
          {" "}
          <div className="faq rise">
            {" "}
            <details open={true}>
              {" "}
              <summary>
                What size cohort works best?
              </summary>
              {" "}
              <div className="faq-a">
                Anything from a departmental team of six to a chapter workshop of two hundred. The format changes with the number, and we'll tell you honestly what suits.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Can you deliver a hybrid programme?
              </summary>
              {" "}
              <div className="faq-a">
                Yes. The NIQS Foundation Digital Frontiers programme ran onsite in Abuja and online simultaneously.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                How is it priced?
              </summary>
              {" "}
              <div className="faq-a">
                On cohort size, duration and location. Ask and we'll quote.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Do attendees get licences?
              </summary>
              {" "}
              <div className="faq-a">
                Training and licences are separate, but we routinely quote them together for institutional programmes.
              </div>
              {" "}
            </details>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec sform-sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sform">
            {" "}
            <div className="sform-copy">
              {" "}
              <span className="eyebrow">
                Talk to us
              </span>
              {" "}
              <h2>
                Plan a programme{" "}
                <span className="grad">
                  for your people
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                Chapter workshops, departmental training and university programmes: delivered on site, on your own projects.
              </p>
              {" "}
              <ul className="sform-pts">
                {" "}
                <li>
                  <span className="ico ico-sm">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                  </span>
                  A real surveyor replies, not a bot
                </li>
                {" "}
                <li>
                  <span className="ico ico-sm">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-clock" />
                    </svg>
                  </span>
                  Usually within one working day
                </li>
                {" "}
                <li>
                  <span className="ico ico-sm">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-cloud" />
                    </svg>
                  </span>
                  No obligation, no drip campaign
                </li>
                {" "}
              </ul>
              {" "}
              <div className="sform-meta">
                {" "}
                <a href="mailto:admin@adlmstudio.net">
                  admin@adlmstudio.net
                </a>
                {" "}
                <span>
                  Lagos, Nigeria
                </span>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <form className="sform-card" action="/checkout/thanks" method="get">
              {" "}
              <input type="hidden" name="topic" value="Institutions" />
              {" "}
              <div className="ds-field">
                {" "}
                <label htmlFor="sf-name">
                  Your name
                </label>
                {" "}
                <input id="sf-name" name="name" type="text" autoComplete="name" placeholder="Ada Okonkwo" required={true} />
                {" "}
              </div>
              {" "}
              <div className="ds-field">
                {" "}
                <label htmlFor="sf-email">
                  Work email
                </label>
                {" "}
                <input id="sf-email" name="email" type="email" autoComplete="email" placeholder="you@firm.com" required={true} />
                {" "}
              </div>
              {" "}
              <div className="ds-field">
                {" "}
                <label htmlFor="sf-org">
                  Organisation{" "}
                  <span className="opt">
                    optional
                  </span>
                </label>
                {" "}
                <input id="sf-org" name="org" type="text" autoComplete="organization" placeholder="Firm, school or agency" />
                {" "}
              </div>
              {" "}
              <div className="ds-field">
                {" "}
                <label htmlFor="sf-msg">
                  What do you need?
                </label>
                {" "}
                <textarea id="sf-msg" name="message" rows="4" placeholder="What you measure, what you hand over, and where it hurts." required={true}>
                </textarea>
                {" "}
              </div>
              {" "}
              <button type="submit" className="ds-btn btn-p btn-full">
                Send the message
              </button>
              {" "}
              <p className="sform-note">
                We reply from a real address. No list, no reselling.
              </p>
              {" "}
            </form>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}{DsPromoSlot}{" "}
      <section className="cta">
        {" "}
        <div className="cta-bp">
        </div>
        <div className="cta-dots">
        </div>
        <div className="cta-g">
        </div>
        {" "}
        <h2>
          Let's talk about{" "}
          <span className="grad">
            your situation
          </span>
        </h2>
        {" "}
        <p className="ds-lede">
          Tell us how your team works today and we'll tell you honestly whether we help.
        </p>
        {" "}
        <div className="hero-cta">
          {" "}
          <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
            Talk to us
          </Link>
          {" "}
          <Link to="/pricing" data-ds-page="pricing" className="ds-btn btn-o">
            See pricing
          </Link>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
