// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/solutions-students.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";
import DsPromoLive from "../DsPromoLive.jsx";

export default function DsSolutionsStudents() {
  const DsPromoSlot = <DsPromoLive />;
  return (
    <>
      <header className="phero">
        {" "}
        <div className="phero-bg">
          <img src="/ds/sol-students.jpg" alt="" />
        </div>
        {" "}
        <div className="phero-in">
          {" "}
          <span className="host">
            For students &amp; early career
          </span>
          {" "}
          <h1>
            {" "}
            <span className="w" style={{ "--i": "0" }}>
              Leave
            </span>
            {" "}
            <span className="w" style={{ "--i": "1" }}>
              university
            </span>
            {" "}
            <span className="w" style={{ "--i": "2" }}>
              able
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "3" }}>
              to
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "4" }}>
              do
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "5" }}>
              the
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "6" }}>
              job.
            </span>
            {" "}
          </h1>
          {" "}
          <p className="ds-lede">
            A six-week certificated course, a free lesson library, and a capstone project you can show an employer.
          </p>
          {" "}
          <div className="hero-cta">
            {" "}
            <Link to="/learn#courses" data-ds-page="learn" className="ds-btn btn-p">
              Browse courses
            </Link>
            {" "}
            <Link to="/learn#lessons" data-ds-page="learn" className="ds-btn btn-o">
              Free lessons
            </Link>
            {" "}
          </div>
          {" "}
          <div className="statframe phero-stats rise">
            {" "}
            <div className="stat">
              {" "}
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-layers" />
                </svg>
              </div>
              {" "}
              <b>
                6
              </b>
              <span>
                weeks, self-paced
              </span>
            </div>
            {" "}
            <div className="stat">
              {" "}
              <div className="ico ico-a">
                <svg viewBox="0 0 24 24">
                  <use href="#i-clock" />
                </svg>
              </div>
              {" "}
              <b>
                15+
              </b>
              <span>
                free lessons
              </span>
            </div>
            {" "}
            <div className="stat">
              {" "}
              <div className="ico">
                <svg viewBox="0 0 24 24">
                  <use href="#i-doc" />
                </svg>
              </div>
              {" "}
              <b>
                1
              </b>
              <span>
                capstone project
              </span>
            </div>
            {" "}
            <div className="stat">
              {" "}
              <div className="ico ico-a">
                <svg viewBox="0 0 24 24">
                  <use href="#i-cloud" />
                </svg>
              </div>
              {" "}
              <b>
                3
              </b>
              <span>
                universities trained
              </span>
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="psplit rise">
            {" "}
            <div className="ps-art">
              <img src="/ds/ab-build.jpg" alt="" loading="lazy" />
            </div>
            {" "}
            <div className="ps-copy">
              {" "}
              <span className="eyebrow">
                The problem
              </span>
              {" "}
              <h2>
                What usually{" "}
                <span className="grad">
                  goes wrong
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                You leave school able to measure and unable to prove it. The gap between the syllabus and the first day on a real project is where most graduates lose a year.
              </p>
              {" "}
              <ul className="ps-list">
                {" "}
                <li>
                  {" "}
                  <span className="ps-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                  </span>
                  {" "}
                  <div>
                    <b>
                      Theory without the tools
                    </b>
                    <p>
                      You graduate knowing the principles of measurement and nothing about the software the job runs on.
                    </p>
                  </div>
                  {" "}
                </li>
                {" "}
                <li>
                  {" "}
                  <span className="ps-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                  </span>
                  {" "}
                  <div>
                    <b>
                      No portfolio
                    </b>
                    <p>
                      Every graduate has a degree. Very few have a coordinated model and a priced bill to show.
                    </p>
                  </div>
                  {" "}
                </li>
                {" "}
                <li>
                  {" "}
                  <span className="ps-ic">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                  </span>
                  {" "}
                  <div>
                    <b>
                      Software you can't afford
                    </b>
                    <p>
                      Learning on trial versions that expire halfway through a project.
                    </p>
                  </div>
                  {" "}
                </li>
                {" "}
              </ul>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              What we do about it
            </span>
            {" "}
            <h2>
              How ADLM{" "}
              <span className="tone">
                actually helps
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="mbento mb3">
            {" "}
            <article className="mtile ds-accent m-w2 tilt rise">
              {" "}
              <div className="mid">
                {" "}
                <span className="ico ico-a" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                </span>
                {" "}
                <h4>
                  A structured six-week roadmap
                </h4>
                {" "}
                <p style={{ maxWidth: "44ch" }}>
                  BIM foundations → 3D → 4D → 5D → analytics → capstone, with weekly assessments to keep you moving.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="mtile m-art tilt rise">
              {" "}
              <img src="/ds/ln-analysts.jpg" alt="" loading="lazy" />
              {" "}
              <div className="mt">
                <span className="ico" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                </span>
                {" "}
                <h4>
                  A capstone worth showing
                </h4>
                {" "}
                <p style={{ maxWidth: "44ch" }}>
                  A coordinated model, clash reports, a 4D simulation and a priced bill.
                </p>
              </div>
              {" "}
            </article>
            {" "}
            <article className="mtile m-art tilt rise">
              {" "}
              <img src="/ds/sol-engineer.jpg" alt="" loading="lazy" />
              {" "}
              <div className="mt">
                <span className="ico" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                </span>
                {" "}
                <h4>
                  Free lessons to start
                </h4>
                {" "}
                <p style={{ maxWidth: "44ch" }}>
                  Fifteen walkthroughs, no sign-in and no payment.
                </p>
              </div>
              {" "}
            </article>
            {" "}
            <article className="mtile solid m-w2 tilt rise">
              {" "}
              <div className="mid">
                {" "}
                <span className="ico" style={{ marginBottom: "16px" }}>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                </span>
                {" "}
                <h4>
                  Visibility if you're good
                </h4>
                {" "}
                <p style={{ maxWidth: "44ch" }}>
                  Top projects each cohort are featured on ADLM channels, credibility before your first job.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="plx">
        {" "}
        <div className="plx-bg">
          <img src="/ds/ls-frame.jpg" alt="" />
        </div>
        {" "}
        <div className="plx-in rise">
          {" "}
          <span className="eyebrow">
            Where we teach
          </span>
          {" "}
          <h2>
            JABU, Rivers State,{" "}
            <span className="grad">
              Yaba Tech, and yours
            </span>
          </h2>
          {" "}
          <p className="ds-lede" style={{ marginTop: "18px" }}>
            We run university programmes across Nigeria. If your department wants one, put us in touch with them.
          </p>
          {" "}
          <div className="hero-cta" style={{ justifyContent: "flex-start" }}>
            {" "}
            <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
              Talk to us
            </Link>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "38px" }}>
            {" "}
            <span className="eyebrow">
              Questions
            </span>
            <h2>
              Common questions
            </h2>
            {" "}
          </div>
          {" "}
          <div className="faq rise">
            {" "}
            <details open={true}>
              {" "}
              <summary>
                Is there a student discount?
              </summary>
              {" "}
              <div className="faq-a">
                Talk to us, cohort pricing for a university group is usually very different from the list price.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Do I need my own laptop and software?
              </summary>
              {" "}
              <div className="faq-a">
                You need a machine that runs Revit. Autodesk student licences are free and are what most people use.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                How long does it really take?
              </summary>
              {" "}
              <div className="faq-a">
                Six weeks at a steady pace. Self-paced means you can go slower, and most people do around exams.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Will this get me a job?
              </summary>
              {" "}
              <div className="faq-a">
                It gives you something concrete to show. We have trained at JABU, Rivers State University and Yaba Tech, and employers here know the tools.
              </div>
              {" "}
            </details>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec sform-sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sform">
            {" "}
            <div className="sform-copy">
              {" "}
              <span className="eyebrow">
                Talk to us
              </span>
              {" "}
              <h2>
                Ask about the{" "}
                <span className="grad">
                  next cohort
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                Course dates, student pricing and what the capstone actually involves. Ask anything before you enrol.
              </p>
              {" "}
              <ul className="sform-pts">
                {" "}
                <li>
                  <span className="ico ico-sm">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-check" />
                    </svg>
                  </span>
                  A real surveyor replies, not a bot
                </li>
                {" "}
                <li>
                  <span className="ico ico-sm">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-clock" />
                    </svg>
                  </span>
                  Usually within one working day
                </li>
                {" "}
                <li>
                  <span className="ico ico-sm">
                    <svg viewBox="0 0 24 24">
                      <use href="#i-cloud" />
                    </svg>
                  </span>
                  No obligation, no drip campaign
                </li>
                {" "}
              </ul>
              {" "}
              <div className="sform-meta">
                {" "}
                <a href="mailto:admin@adlmstudio.net">
                  admin@adlmstudio.net
                </a>
                {" "}
                <span>
                  Lagos, Nigeria
                </span>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <form className="sform-card" action="/checkout/thanks" method="get">
              {" "}
              <input type="hidden" name="topic" value="Students &amp; early career" />
              {" "}
              <div className="ds-field">
                {" "}
                <label htmlFor="sf-name">
                  Your name
                </label>
                {" "}
                <input id="sf-name" name="name" type="text" autoComplete="name" placeholder="Ada Okonkwo" required={true} />
                {" "}
              </div>
              {" "}
              <div className="ds-field">
                {" "}
                <label htmlFor="sf-email">
                  Work email
                </label>
                {" "}
                <input id="sf-email" name="email" type="email" autoComplete="email" placeholder="you@firm.com" required={true} />
                {" "}
              </div>
              {" "}
              <div className="ds-field">
                {" "}
                <label htmlFor="sf-org">
                  Organisation{" "}
                  <span className="opt">
                    optional
                  </span>
                </label>
                {" "}
                <input id="sf-org" name="org" type="text" autoComplete="organization" placeholder="Firm, school or agency" />
                {" "}
              </div>
              {" "}
              <div className="ds-field">
                {" "}
                <label htmlFor="sf-msg">
                  What do you need?
                </label>
                {" "}
                <textarea id="sf-msg" name="message" rows="4" placeholder="What you measure, what you hand over, and where it hurts." required={true}>
                </textarea>
                {" "}
              </div>
              {" "}
              <button type="submit" className="ds-btn btn-p btn-full">
                Send the message
              </button>
              {" "}
              <p className="sform-note">
                We reply from a real address. No list, no reselling.
              </p>
              {" "}
            </form>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}{DsPromoSlot}{" "}
      <section className="cta">
        {" "}
        <div className="cta-bp">
        </div>
        <div className="cta-dots">
        </div>
        <div className="cta-g">
        </div>
        {" "}
        <h2>
          Let's talk about{" "}
          <span className="grad">
            your situation
          </span>
        </h2>
        {" "}
        <p className="ds-lede">
          Tell us how your team works today and we'll tell you honestly whether we help.
        </p>
        {" "}
        <div className="hero-cta">
          {" "}
          <Link to="/contact" data-ds-page="contact" className="ds-btn btn-p">
            Talk to us
          </Link>
          {" "}
          <Link to="/pricing" data-ds-page="pricing" className="ds-btn btn-o">
            See pricing
          </Link>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
