// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/splash-rategen.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";

export default function DsSplashRateGen() {
  return (
    <>
      {/* One product splash on its own, for review. splash.js mounts itself
     when it finds this element. */}
      {" "}
      <div id="splash" data-product="rategen" data-version="2.9.2">
      </div>
    </>
  );
}
