// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/thanks.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";

export default function DsThanks() {
  return (
    <>
      <section className="sec" style={{ paddingTop: "150px" }}>
        {" "}
        <div className="shell">
          {" "}
          <div className="flowsteps">
            {" "}
            <div className="done">
              <i>
                ✓
              </i>
              Cart
            </div>
            {" "}
            <s>
            </s>
            {" "}
            <div className="done">
              <i>
                ✓
              </i>
              Account
            </div>
            {" "}
            <s>
            </s>
            {" "}
            <div className="done">
              <i>
                ✓
              </i>
              Payment
            </div>
            {" "}
            <s>
            </s>
            {" "}
            <div className="on">
              <i>
                4
              </i>
              Install
            </div>
            {" "}
          </div>
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "38px" }}>
            {" "}
            <span className="eyebrow">
              Step 4 of 4 · done
            </span>
            {" "}
            <h2>
              Your licences{" "}
              <span className="grad">
                are active
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              Receipt sent to your email. Here is exactly what happens next.
            </p>
            {" "}
          </div>
          {" "}
          <div className="chk">
            {" "}
            <div className="panel rise">
              {" "}
              <h3>
                Install your products
              </h3>
              {" "}
              <p className="ds-sub">
                One download puts everything you own on this machine.
              </p>
              {" "}
              <div className="line">
                {" "}
                <img src="/ds/ic-quiv.png" alt="" />
                {" "}
                <div>
                  <b>
                    QUIV × 2 seats
                  </b>
                  <span>
                    Ready to activate
                  </span>
                </div>
                {" "}
                <div className="amt2">
                  <span className="pill pill-a">
                    Active
                  </span>
                </div>
                {" "}
              </div>
              {" "}
              <div className="line">
                {" "}
                <img src="/ds/ic-rategen.png" alt="" />
                {" "}
                <div>
                  <b>
                    RateGen × 2 seats
                  </b>
                  <span>
                    Ready to activate
                  </span>
                </div>
                {" "}
                <div className="amt2">
                  <span className="pill pill-a">
                    Active
                  </span>
                </div>
                {" "}
              </div>
              {" "}
              <div className="line">
                {" "}
                <img src="/ds/ic-heron.png" alt="" />
                {" "}
                <div>
                  <b>
                    HERON × 1 seat
                  </b>
                  <span>
                    Ready to activate
                  </span>
                </div>
                {" "}
                <div className="amt2">
                  <span className="pill pill-a">
                    Active
                  </span>
                </div>
                {" "}
              </div>
              {" "}
              <Link to="/how-it-works" data-ds-page="how-it-works" className="ds-btn btn-p btn-full" style={{ marginTop: "22px" }}>
                Download the Installer Hub{" "}
                <svg viewBox="0 0 24 24">
                  <use href="#i-down" />
                </svg>
              </Link>
              {" "}
              <p className="small" style={{ marginTop: "12px" }}>
                Windows · 64-bit. Sign in with the account you just created and your products install themselves.
              </p>
              {" "}
            </div>
            {" "}
            <div className="panel rise">
              {" "}
              <h3>
                What happens next
              </h3>
              {" "}
              <p className="ds-sub">
                Four steps, then you're measuring.
              </p>
              {" "}
              <ul className="ticks">
                {" "}
                <li>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                  Download and run the Installer Hub
                </li>
                {" "}
                <li>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                  Sign in with your new ADLM account
                </li>
                {" "}
                <li>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                  The Hub installs everything your subscription covers
                </li>
                {" "}
                <li>
                  <svg viewBox="0 0 24 24">
                    <use href="#i-check" />
                  </svg>
                  Open Revit or PlanSwift, the panel is already there
                </li>
                {" "}
              </ul>
              {" "}
              <Link to="/login" data-ds-page="login" className="ds-btn btn-p btn-full" style={{ marginTop: "20px" }}>
                Sign in to your account
              </Link>
              {" "}
              <p className="small" style={{ marginTop: "14px" }}>
                Stuck?{" "}
                <Link to="/contact#support" data-ds-page="contact" style={{ color: "var(--action)" }}>
                  Support replies the same working day
                </Link>
                .
              </p>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <div className="frame frame-soft">
        {" "}
        <section className="sec-half band-dark amb">
          {" "}
          <div className="shell">
            {" "}
            <div className="sec-head mid rise" style={{ marginBottom: "0" }}>
              {" "}
              <span className="eyebrow">
                While you install
              </span>
              {" "}
              <h2>
                Get the most{" "}
                <span className="grad">
                  out of it quickly
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                Free guides and lessons, no sign-in needed.
              </p>
              {" "}
              <div className="hero-cta" style={{ justifyContent: "center" }}>
                {" "}
                <Link to="/learn#guides" data-ds-page="learn" className="ds-btn btn-p">
                  Read the guides
                </Link>
                {" "}
                <Link to="/learn#lessons" data-ds-page="learn" className="ds-btn btn-o">
                  Watch the lessons
                </Link>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </div>
    </>
  );
}
