// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/timepro.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";
import DsPromoLive from "../DsPromoLive.jsx";

export default function DsTimeProPage({ d }) {
  const DsPromoSlot = <DsPromoLive />;
  return (
    <>
      <header className="phero light-art">
        {" "}
        <div className="phero-bg">
          <img src="/ds/bg-timepro.jpg" alt="Time Pro" />
        </div>
        {" "}
        <div className="phero-in">
          {" "}
          <span className="host">
            Site productivity · Desktop &amp; mobile
          </span>
          {" "}
          <h1>
            {" "}
            <span className="w" style={{ "--i": "0" }}>
              Programmes
            </span>
            {" "}
            <span className="w" style={{ "--i": "1" }}>
              built
            </span>
            {" "}
            <span className="w" style={{ "--i": "2" }}>
              from
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "3" }}>
              what
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "4" }}>
              site
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "5" }}>
              actually
            </span>
            {" "}
            <span className="w grad" style={{ "--i": "6" }}>
              did.
            </span>
            {" "}
          </h1>
          {" "}
          <p className="ds-lede">
            Log the output, get durations you can defend, then export the programme.
          </p>
          {" "}
          <div className="hero-cta">
            {" "}
            <Link to="/purchase" data-ds-page="cart" className="ds-btn btn-p">
              Get Time Pro
            </Link>
            {" "}
            <Link to="/pricing" data-ds-page="pricing" className="ds-btn btn-o">
              See pricing
            </Link>
            {" "}
          </div>
          {" "}
          <p className="phero-note">
            <span className="pulse">
            </span>
            Latest v1.1.0 · desktop and mobile
          </p>
          {" "}
        </div>
        {" "}
      </header>
      {" "}
      <section className="sec">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise">
            {" "}
            <span className="eyebrow">
              Core features
            </span>
            {" "}
            <h2>
              What Time Pro does{" "}
              <span className="tone">
                and how it does it
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="fgrid">
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz">
                  <div className="vz-panel">
                    {" "}
                    <div className="vz-row">
                      <span>
                        Mon · blocklaying
                      </span>
                      <b>
                        18.4 m²
                      </b>
                    </div>
                    {" "}
                    <div className="vz-row">
                      <span>
                        Tue · blocklaying
                      </span>
                      <b>
                        21.2 m²
                      </b>
                    </div>
                    {" "}
                    <div className="vz-row hl">
                      <span>
                        Wed · rain, half day
                      </span>
                      <b>
                        9.6 m²
                      </b>
                    </div>
                    {" "}
                    <div className="vz-row">
                      <span>
                        Thu · blocklaying
                      </span>
                      <b>
                        20.8 m²
                      </b>
                    </div>
                    {" "}
                    <div className="vz-sum">
                      <span>
                        Average / day
                      </span>
                      <b>
                        17.5 m²
                      </b>
                    </div>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Site record
                </span>
                {" "}
                <h4>
                  Daily output, logged where it happens
                </h4>
                {" "}
                <p>
                  Record what each trade achieved that day, on the phone, on site. Weather and crew size are captured alongside so the numbers mean something later.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz">
                  <div className="vz-bars">
                    {" "}
                    <i style={{ height: "52%" }}>
                    </i>
                    <i style={{ height: "68%" }}>
                    </i>
                    <i style={{ height: "44%" }}>
                    </i>
                    {" "}
                    <i className="hot" style={{ height: "84%" }}>
                    </i>
                    <i style={{ height: "72%" }}>
                    </i>
                    <i style={{ height: "61%" }}>
                    </i>
                  </div>
                  {" "}
                  <div style={{ display: "flex", gap: "7px", justifyContent: "center", marginTop: "12px" }}>
                    {" "}
                    <span className="vz-chip">
                      book rate 14 m²
                    </span>
                    <span className="vz-chip on">
                      your rate 17.5 m²
                    </span>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Evidence
                </span>
                {" "}
                <h4>
                  Real output rates, not book rates
                </h4>
                {" "}
                <p>
                  After a few weeks you are planning from your own crews on your own sites, rather than from a productivity table written for somewhere else.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz" style={{ display: "flex", justifyContent: "center", gap: "20px", alignItems: "center" }}>
                  {" "}
                  <div className="vz-ring">
                    <span>
                      12d
                    </span>
                  </div>
                  {" "}
                  <div className="vz-panel" style={{ flex: "1" }}>
                    {" "}
                    <div className="vz-row">
                      <span>
                        Quantity
                      </span>
                      <b>
                        210 m²
                      </b>
                    </div>
                    {" "}
                    <div className="vz-row">
                      <span>
                        Output
                      </span>
                      <b>
                        17.5 m²/day
                      </b>
                    </div>
                    {" "}
                    <div className="vz-sum">
                      <span>
                        Crew
                      </span>
                      <b>
                        6 no
                      </b>
                    </div>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Planning
                </span>
                {" "}
                <h4>
                  Durations and crew size fall out of it
                </h4>
                {" "}
                <p>
                  Give it a quantity and it tells you how long that takes your team, and what crew gets it done by a date: arithmetic you can show the client.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz">
                  <div className="vz-gantt">
                    {" "}
                    <div>
                      <span>
                        Substructure
                      </span>
                      <i className="hot" style={{ width: "30%" }}>
                      </i>
                    </div>
                    {" "}
                    <div>
                      <span>
                        Frame
                      </span>
                      <i className="hot" style={{ width: "44%", marginLeft: "22%" }}>
                      </i>
                    </div>
                    {" "}
                    <div>
                      <span>
                        Blockwork
                      </span>
                      <i style={{ width: "38%", marginLeft: "44%" }}>
                      </i>
                    </div>
                    {" "}
                    <div>
                      <span>
                        Finishes
                      </span>
                      <i style={{ width: "30%", marginLeft: "66%" }}>
                      </i>
                    </div>
                  </div>
                  {" "}
                  <div style={{ display: "flex", justifyContent: "center", marginTop: "12px" }}>
                    {" "}
                    <span className="vz-chip on">
                      .mpp · opens first time
                    </span>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Programme
                </span>
                {" "}
                <h4>
                  Straight into Microsoft Project
                </h4>
                {" "}
                <p>
                  Export a programme that opens first time, with durations already priced, no retyping the schedule into a planning tool afterwards.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
            <article className="fcard tilt rise">
              {" "}
              <div className="fviz">
                {" "}
                <div className="vz" style={{ maxWidth: "600px" }}>
                  <div className="vz-cols">
                    {" "}
                    <div className="vz-col">
                      Days logged
                      <b>
                        184
                      </b>
                    </div>
                    {" "}
                    <div className="vz-col">
                      Rain days
                      <b>
                        21
                      </b>
                    </div>
                    {" "}
                    <div className="vz-col">
                      Output vs plan
                      <b>
                        +4%
                      </b>
                    </div>
                  </div>
                  {" "}
                  <div style={{ display: "flex", justifyContent: "center", marginTop: "12px" }}>
                    {" "}
                    <span className="vz-chip on">
                      exportable as a dated record
                    </span>
                  </div>
                </div>
                {" "}
              </div>
              {" "}
              <div className="fcard-body">
                {" "}
                <span className="fcard-tag">
                  Disputes
                </span>
                {" "}
                <h4>
                  The record that settles the argument
                </h4>
                {" "}
                <p>
                  When a delay claim arrives, the daily log is already there: what was done, by how many people, in what weather. Evidence rather than recollection.
                </p>
                {" "}
              </div>
              {" "}
            </article>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <div className="frame frame-soft">
        {" "}
        <section className="sec band-dark amb">
          {" "}
          <div className="shell">
            {" "}
            <div className="sec-head mid rise">
              {" "}
              <span className="eyebrow">
                The output
              </span>
              {" "}
              <h2>
                A programme with{" "}
                <span className="grad">
                  evidence underneath it
                </span>
              </h2>
              {" "}
              <p className="ds-lede">
                Every duration traces back to days your own crews actually worked.
              </p>
              {" "}
            </div>
            {" "}
            <div className="chain rise">
              {" "}
              <article className="chain-c">
                {" "}
                <span className="chain-n">
                  01
                </span>
                {" "}
                <h3>
                  What a book rate says
                </h3>
                {" "}
                <div className="frag">
                  {" "}
                  <div className="frag-t">
                    Published output
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Blocklaying
                    </span>
                    <span className="frag-v">
                      14.0 m²/day
                    </span>
                    {" "}
                  </div>
                  {" "}
                </div>
              </article>
              {" "}
              <span className="chain-link" aria-hidden="true">
              </span>
              {" "}
              <article className="chain-c">
                {" "}
                <span className="chain-n">
                  02
                </span>
                {" "}
                <h3>
                  What your site says
                </h3>
                {" "}
                <div className="frag">
                  {" "}
                  <div className="frag-t">
                    Bill description
                  </div>
                  {" "}
                  <div className="pre">
                    Averaged across 42 logged days, crew of 6, this project
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Blocklaying
                    </span>
                    <span className="frag-v">
                      17.5 m²/day
                    </span>
                    {" "}
                  </div>
                  {" "}
                </div>
              </article>
              {" "}
              <span className="chain-link" aria-hidden="true">
              </span>
              {" "}
              <article className="chain-c">
                {" "}
                <span className="chain-n">
                  03
                </span>
                {" "}
                <h3>
                  What the client receives
                </h3>
                {" "}
                <div className="frag">
                  {" "}
                  <div className="frag-t">
                    Programme · exported
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Substructure
                    </span>
                    <span className="frag-v">
                      18 days
                    </span>
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Frame &amp; upper floors
                    </span>
                    <span className="frag-v">
                      34 days
                    </span>
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Blockwork
                    </span>
                    <span className="frag-v">
                      22 days
                    </span>
                  </div>
                  {" "}
                  <div className="frag-r">
                    <span className="frag-k">
                      Finishes
                    </span>
                    <span className="frag-v">
                      28 days
                    </span>
                  </div>
                  {" "}
                  <div className="frag-sum">
                    <span>
                      Duration to practical completion
                    </span>
                    <span className="frag-v">
                      102 days
                    </span>
                    {" "}
                  </div>
                  {" "}
                </div>
              </article>
              {" "}
            </div>
            {" "}
            <p className="chain-note">
              One source, one summary. Nothing is retyped between the measurement and the number you send.
            </p>
            {" "}
          </div>
          {" "}
        </section>
        {" "}
      </div>
      {" "}
      <section className="sec-half blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head rise" style={{ marginBottom: "36px" }}>
            {" "}
            <span className="eyebrow">
              Compatibility
            </span>
            {" "}
            <h2>
              Where Time Pro{" "}
              <span className="tone">
                fits in your setup
              </span>
            </h2>
            {" "}
          </div>
          {" "}
          <div className="compat">
            {" "}
            <div className="compat-c rise">
              <h6>
                Platform
              </h6>
              {" "}
              <div className="big">
                Windows &amp; mobile
              </div>
              {" "}
              <div className="compat-tags">
                <span>
                  Syncs through your account
                </span>
              </div>
            </div>
            {" "}
            <div className="compat-c rise">
              <h6>
                Exports
              </h6>
              {" "}
              <div className="big">
                Microsoft Project
              </div>
              {" "}
              <div className="compat-tags">
                <span>
                  Excel · dated log
                </span>
              </div>
            </div>
            {" "}
            <div className="compat-c rise">
              <h6>
                Records
              </h6>
              {" "}
              <div className="big">
                Output · crew · weather
              </div>
              {" "}
              <div className="compat-tags">
                <span>
                  Per trade, per day
                </span>
              </div>
            </div>
            {" "}
            <div className="compat-c rise">
              <h6>
                Works offline
              </h6>
              {" "}
              <div className="big">
                Yes
              </div>
              {" "}
              <div className="compat-tags">
                <span>
                  Syncs when you reconnect
                </span>
              </div>
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half alt amb blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "36px" }}>
            {" "}
            <span className="eyebrow">
              Pricing
            </span>
            {" "}
            <h2>
              {d.monthly} a month,{" "}
              <span className="tone">
                per PC
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              {d.priceLine}
            </p>
            {" "}
            <div className="hero-cta" style={{ justifyContent: "center" }}>
              {" "}
              <Link to="/purchase" data-ds-page="cart" className="ds-btn btn-p">
                Get Time Pro
              </Link>
              {" "}
              <Link to="/contact" data-ds-page="contact" className="ds-btn btn-o">
                Build a quote
              </Link>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half blend" id="updates">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "40px" }}>
            {" "}
            <span className="eyebrow">
              Release history
            </span>
            {" "}
            <h2>
              What's changed{" "}
              <span className="tone">
                over time
              </span>
            </h2>
            {" "}
            <p className="ds-lede">
              Every release, in plain English: what shipped, what improved, what was fixed.
            </p>
            {" "}
          </div>
          {" "}{d.releases}{" "}
        </div>
        {" "}
      </section>
      {" "}
      <section className="sec-half blend">
        {" "}
        <div className="shell">
          {" "}
          <div className="sec-head mid rise" style={{ marginBottom: "38px" }}>
            {" "}
            <span className="eyebrow">
              Questions
            </span>
            {" "}
            <h2>
              About Time Pro
            </h2>
            {" "}
          </div>
          {" "}
          <div className="faq rise">
            {" "}
            <details open={true}>
              {" "}
              <summary>
                Do I need the mobile app?
              </summary>
              {" "}
              <div className="faq-a">
                No, but it is where the value is. Logging on site beats reconstructing the week from memory on Friday.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Does it replace my planning software?
              </summary>
              {" "}
              <div className="faq-a">
                No. It produces the durations and exports a programme, Microsoft Project stays where you plan and track.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                How long before the output rates are useful?
              </summary>
              {" "}
              <div className="faq-a">
                A few weeks of consistent logging on one trade is usually enough to beat a published rate.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                Can the site team log without a licence each?
              </summary>
              {" "}
              <div className="faq-a">
                Logging is tied to your account's seats. Talk to us about how many people actually need to record.
              </div>
              {" "}
            </details>
            {" "}
            <details>
              {" "}
              <summary>
                What if the site has no signal?
              </summary>
              {" "}
              <div className="faq-a">
                It records offline and syncs when a connection comes back.
              </div>
              {" "}
            </details>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      {" "}{DsPromoSlot}{" "}
      <section className="cta">
        {" "}
        <div className="cta-bp">
        </div>
        <div className="cta-dots">
        </div>
        <div className="cta-g">
        </div>
        {" "}
        <h2>
          See it on{" "}
          <span className="grad">
            your project
          </span>
        </h2>
        {" "}
        <p className="ds-lede">
          We'll run Time Pro against one of your live jobs, your drawings, your rates, your bill format.
        </p>
        {" "}
        <div className="hero-cta">
          {" "}
          <Link to="/purchase" data-ds-page="cart" className="ds-btn btn-p">
            Get Time Pro
          </Link>
          {" "}
          <Link to="/products" data-ds-page="products" className="ds-btn btn-o">
            All products
          </Link>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
