// GENERATED by client/scripts/port-ds-html.mjs — do not edit by hand.
// Ported from RichardEnoch/adlm-studio-site src/verify.html
// Re-run the script to pick up his changes; hand edits here are lost.
import React from "react";
import { Link } from "react-router-dom";

export default function DsVerify() {
  return (
    <>
      <section className="auth2">
        {" "}
        <div className="auth2-art">
          {" "}
          <img className="bg" src="/ds/ls-steel.jpg" alt="" />
          {" "}
          <div className="auth2-art-in">
            {" "}
            <Link className="lg" to="/" aria-label="ADLM Studio home">
              <img src="/ds/logo-dark.svg" alt="ADLM Studio" />
            </Link>
            {" "}
            <h2>
              Six digits,{" "}
              <span>
                then you're through.
              </span>
            </h2>
            {" "}
            <p>
              We check the address before you pay, because everything you buy is issued to it: the licence, the invoices, and any certificate you earn.
            </p>
            {" "}
            <ul className="auth2-pts">
              {" "}
              <li>
                A wrong address means a licence nobody can reach
              </li>
              {" "}
              <li>
                It is how we send a receipt the moment payment clears
              </li>
              {" "}
              <li>
                It is the address you will sign in with on every machine
              </li>
              {" "}
            </ul>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
        <div className="auth2-form">
          {" "}
          <div className="auth2-card">
            {" "}
            <div className="flowsteps sm">
              {" "}
              <div className="done">
                <i>
                  ✓
                </i>
                Cart
              </div>
              {" "}
              <s>
              </s>
              {" "}
              <div className="on">
                <i>
                  2
                </i>
                Account
              </div>
              {" "}
              <s>
              </s>
              {" "}
              <div>
                <i>
                  3
                </i>
                Payment
              </div>
              {" "}
              <s>
              </s>
              {" "}
              <div>
                <i>
                  4
                </i>
                Install
              </div>
              {" "}
            </div>
            {" "}
            <h1>
              Check your email
            </h1>
            {" "}
            <p className="ds-sub">
              We sent a six-digit code to{" "}
              <b id="vf-mail">
                your work address
              </b>
              .{" "}
              <Link to="/signup" data-ds-page="signup" id="vf-change">
                Use a different one
              </Link>
            </p>
            {" "}
            <form id="vf-form" noValidate={true}>
              {" "}
              <div className="vf-code" id="vf-code" role="group" aria-label="Six-digit verification code">
                {" "}
                <input type="text" inputmode="numeric" autoComplete="one-time-code" maxLength="1" aria-label="Digit 1" />
                {" "}
                <input type="text" inputmode="numeric" maxLength="1" aria-label="Digit 2" />
                {" "}
                <input type="text" inputmode="numeric" maxLength="1" aria-label="Digit 3" />
                {" "}
                <input type="text" inputmode="numeric" maxLength="1" aria-label="Digit 4" />
                {" "}
                <input type="text" inputmode="numeric" maxLength="1" aria-label="Digit 5" />
                {" "}
                <input type="text" inputmode="numeric" maxLength="1" aria-label="Digit 6" />
                {" "}
              </div>
              {" "}
              <p className="vf-msg" id="vf-msg" role="status">
              </p>
              {" "}
              <button type="submit" className="ds-btn btn-p btn-full">
                Verify and continue
              </button>
              {" "}
            </form>
            {" "}
            <p className="vf-resend">
              Nothing yet?{" "}
              <button type="button" id="vf-again" className="linkish">
                Send it again
              </button>
              {" "}
              <span id="vf-wait">
              </span>
            </p>
            {" "}
            <p className="authfoot">
              Check your spam folder before asking us. It is almost always there. Still stuck?{" "}
              <Link to="/contact#support" data-ds-page="contact">
                Contact support
              </Link>
            </p>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
    </>
  );
}
