// Loads his beyondbim.css and renders nothing.
//
// Same reason as DsLearnStyles and DsDocStyles: Vite needs a static import to
// code-split a stylesheet, and 30 KB for one cohort page should not be paid
// for by every visitor to the home page.
//
// It is a component rather than an import inside DsBeyondBim.jsx because that
// page is GENERATED by scripts/port-ds-html.mjs — anything written into it by
// hand is gone the next time he changes the page and it is re-ported.
import "../styles/ds-beyondbim.css";

export default function DsBeyondBimStyles() {
  return null;
}
