// server/scripts/work-board.seed.mjs
//
// Everything in flight across ADLM on 22 Sep 2026, from a run through every
// open Claude session and every product repo. Loaded by work-board.mjs seed.
//
// Work already under way before the proposal-first rule is "grandfathered":
// it keeps moving, and Richard can still comment or ask for a design pass.
// Fixes and infrastructure are "not-required". Nothing here invents a
// business case: where one is missing, `pending` says so.
//
// Re-running the seed refreshes summary / progress / pending / blockedOn /
// refs only. Stage, decision, design and comments are set once, on insert,
// so nothing Richard decides on the board is ever overwritten by a re-seed.

export const AS_OF = "22 Sep 2026";

export const SEED = [
  // ── The release gate and how releases reach customers ────────────────────
  {
    key: "release-gate",
    title: "Release gate: nothing reaches customers without Richard's sign-off",
    products: ["platform", "infra"],
    kind: "infra",
    stage: "testing",
    summary: "Every plugin release waits at the Release sign-off desk; website changes are staged at preview.adlmstudio.net first.",
    progress: "Sign-off desk live on main (PRs #17, #18). preview.adlmstudio.net serves the release branch, HTTPS up since 04:24 UTC 22 Sep; signed-out visitors see only the staff wall. Locked 3-year audit bucket in stack AdlmReleaseGate.",
    pending: "PR #20 (lock the production environment even before the approver accepts) needs review. Then Richard is made the required approver on API deploys.",
    blockedOn: "Richard: accept the GitHub invite for RichardEnoch, then review PR #20.",
    refs: "AdlmWeb PR #20 (feat/release-gate) · docs/RELEASE_GATE.md",
    design: { status: "not-needed" },
  },
  {
    key: "plugin-release-scripts",
    title: "Release scripts say 'staged, awaiting sign-off' instead of 'live'",
    products: ["installer-hub", "rategen", "quiv", "heron", "mep"],
    kind: "infra",
    stage: "testing",
    progress: "Installer Hub package scripts report staged builds from the gate; announce-release.ps1 refuses versions still awaiting sign-off; RateGen push-installer-update handles the gate.",
    pending: "Give Richard access to the ADLMInstaller repo so he can review the two PRs. GitHub refused a read-only invite: it is a private repo on a personal account, where every collaborator gets write access.",
    blockedOn: "Adedolapo: invite Richard with write access, or move the repo into an ADLM GitHub organisation (which has a real read-only role).",
    refs: "ADLMInstallerHub claude/build-all-packages · ADLMInstallerHub-guard fix/hub-block-install-while-host-running · ADLMRateGenPublicBuild may30-version",
    design: { status: "not-needed" },
  },
  {
    key: "hotfix-review-fixes",
    title: "Hotfix: download names keep their letters; WhatsApp code tied to its number",
    products: ["website"],
    kind: "fix",
    stage: "awaiting-signoff",
    summary: "Two live bugs found while reviewing the redesign branch. Assignment downloads lose every letter r ('Chapte epot.docx'); a WhatsApp code could verify a different number.",
    progress: "Fixed with tests; 608 server tests pass; the Lambda bundle builds.",
    pending: "Merge PR #19. Merging deploys the API, which also needs approval on the production environment.",
    blockedOn: "PR #19 review",
    refs: "AdlmWeb PR #19 (hotfix/review-fixes)",
    design: { status: "not-needed" },
  },
  {
    key: "admin-roles-editor",
    title: "Launch build: admins can assign roles and edit role areas again",
    products: ["website"],
    kind: "fix",
    stage: "awaiting-signoff",
    summary: "On the launch build /admin/roles is a read-only register, and the classic role editor had no route. After go-live nobody could give a person a role (for example Tech Support, PR #28) or change what a role reaches.",
    progress: "The classic editor is routed at /admin/roles/edit (admins only) and linked from the register as 'Edit roles'. Lint is clean and the client build passes. Opened 25 Sep against release.",
    pending: "Richard approves PR #29 into release. Then one signed-in check on preview.adlmstudio.net: Roles, Edit roles, give someone Tech Support. Afterwards, an editor drawn in his design, which also confirms and audits area changes (today those save at once, unconfirmed and unaudited).",
    blockedOn: "PR #29 review",
    refs: "AdlmWeb PR #29 (fix/admin-roles-editor -> release) · client/src/ds/DsAdminRoles.jsx · client/src/pages/AdminRoles.jsx · server/routes/admin.roles.js",
    design: { status: "needed", surfaces: "Roles editor in his admin grammar: create and delete a role, the area matrix, assigning people, a confirmation and an audit line on every change, a warning before the last administrator loses access" },
  },

  // ── Richard's redesign ───────────────────────────────────────────────────
  {
    key: "redesign-port",
    title: "Richard's redesign brought into the live site (review items R01 to R22 + his 17 Sep update)",
    products: ["website"],
    kind: "design",
    stage: "building",
    summary: "Porting his static rebuild onto the real app with real data: black theme, feedback toasts, the projects restructure (My tools, gallery, workspace tabs), certificates with QR verification, assignments, the composer signature.",
    progress: "47 commits on the review branch. A session is working on it right now.",
    pending: "Finish the P0 port and the R-items. Parts of the projects restructure need data we do not have yet (the plan lists them as Q1). Then open a PR for Richard to review on preview.adlmstudio.net.",
    blockedOn: "",
    refs: "ADLMWebsite-review fix/richard-review-sep16 (PLAN.md) · Richard's repo RichardEnoch/adlm-studio-site",
    design: { status: "adopted", link: "https://adlm-studio.vercel.app", notes: "It is his design. The port does not change it." },
  },
  {
    key: "redesign-open-items",
    title: "Redesign open items that need a decision or a backend (about 20)",
    products: ["website", "platform"],
    kind: "design",
    stage: "in-design",
    summary: "Section 7 of his PROJECT-SUMMARY.md: roughly 20 items where the design is done or nearly done, and what is missing is a decision or a backend.",
    progress: "97 built pages (66 marketing and app, 31 admin), live at adlm-studio.vercel.app.",
    pending: "Go through section 7 together and put each item on this board as a proposal, so it gets a business case and a yes or no.",
    blockedOn: "Adedolapo and Richard: a joint pass",
    refs: "ADLMWebNewUI/PROJECT-SUMMARY.md §7",
    design: { status: "in-progress", link: "https://adlm-studio.vercel.app" },
  },

  // ── QUIV (Revit) ─────────────────────────────────────────────────────────
  {
    key: "quiv-4-redesign",
    title: "QUIV 4.0: rebuild the Revit plugin on Richard's plugin design, saving to ADLM Cloud",
    products: ["quiv", "website"],
    kind: "feature",
    stage: "proposed",
    progress: "Built ahead of approval at the owner's request, tested in Revit 2026 by Adedolapo (26 Sep). The panel is Richard's design end to end: dock sign-in from his splash, Home, New project, take-off list, the three-step Item screen for all 20 elements, auto take-off with confidence and accept, Review and save, light and dark. The QUIV 3 engine is unchanged underneath; no QUIV 3 page appears in the panel. Builds for Revit 2024, 2026 and 2027; 342 tests green, CI green. 26 Sep: pushed as RevitPluginArch#3 with the 3.1.11 hotfix merged in and the version set to 4.0.0, then staged at the release desk for Richard only (candidate 6ab7cc94, plugin DLL 4.0.0.0). A first staging had packaged the 3.1.11 DLLs from the main checkout; it was caught before anyone installed it and superseded, and the release scripts now refuse a mismatched DLL (da6ac8f, on the Installer Hub master via ADLMInstaller#5; PR #3 closed 27 Sep as already merged, Richard asked to review it there). Richard emailed 27 Sep.",
    pending: "Richard installs 4.0.0 from his Hub, tests, then approves or sends back at /admin/releases. AdlmWeb#50 must be deployed first so 4.0.0 goes to firms first. Then merge RevitPluginArch#3. Outside his design and needing his design or sign-off: raft option, External works group, foundation none/multiple (none drops Substructure and Frame), remove-from-list with Undo, auto take-off Stop and clock, Sign out, theme switch, Create account on the sign-in, the RateGen card on Review. Still to design: full bill and budget, exports, RateGen mapping, client bill fill (no longer reachable in the panel).",
    refs: "RevitPluginArch#3 feat/quiv-4 dd6cd89 (worktree nw/RevitPluginArch-quiv4). Staged candidate 6ab7cc944903e767f131b76c. Hub release-script fix da6ac8f on ADLMInstallerHub master (via ADLMInstaller#5).",
    design: { status: "needed", link: "https://adlm-studio.vercel.app/plugin-quiv", surfaces: "The items above marked outside the design; the full bill, budget, exports, RateGen mapping and client bill fill." },
  },
  {
    key: "quiv-custom-rate-plant",
    title: "QUIV prices a website-built custom rate below its published rate (plant line dropped)",
    products: ["quiv"],
    kind: "fix",
    stage: "awaiting-signoff",
    summary: "RateCompositionParser read a custom rate's materials[] + labour[] and never breakdown[], so a plant line was invisible and the ceiling clamped the rate down (13,500/m2 published, 12,500 priced). Mirrors the website fix of 22 Sep (f1e7674), including the kept 'Not itemised' remainder.",
    progress: "Fixed, 6 new tests, 325/325 green; Release builds for Revit 2024, 2025/26 and 2027 with 0 errors, nothing deployed. Staged as a PR, not released.",
    pending: "Richard's sign-off, then merge to QUIV main, version bump and package through the Installer Hub release scripts. Richard is not a collaborator on RevitPluginArch, so GitHub cannot request his review there.",
    refs: "github.com/adedola12/RevitPluginArch/pull/4 (fix/custom-rate-plant-breakdown, c4691eb, worktree nw/RevitPluginArch-r5)",
  },
  // Richard's 22 Sep desktop designs (his 596e9cb..ca0e6c3). The QUIV splash is
  // inside quiv-4-redesign and HERON side one inside the HERON 3.0 proposal.
  {
    key: "installer-hub-redesign",
    title: "Installer Hub rebuilt on Richard's desktop design: splash that becomes the sign-in, and account pages",
    products: ["installer-hub"],
    kind: "feature",
    stage: "proposed",
    progress: "Built ahead of approval at the owner's request (27-28 Sep). Hub 2.0.0 on Richard's hub.html design: the splash that becomes the sign-in (Figma frame), Windows title bar, rail, Dashboard (Needs you, This PC with detected Revit/PlanSwift/Excel/Civil 3D/Archicad, Installed on this PC), Installation Center (filters, search, state-first cards, step progress, Update all), Free software, Subscriptions, Install history (new local log, CSV export), Profile (Organisation, Role, Zone, Member since from /me/profile), Settings (Light/Dark/Match Windows, relink, cache, diagnostic report), Help and contact, in-app toasts and confirm cards, light and dark, small screens (rail folds to icons). Also: ADLM software only (no courses or feature grants), no install folder shown, one Hub per PC, version 2.0.0. Admin: software gallery (upload a ZIP only, install steps built in, versions and roll back), free software gallery, each staff area its own page. Private preview build uploaded 28 Sep 22:58 WAT (installerHubUrl unchanged); Richard asked to install and test it (task #72, 29 Sep).",
    pending: "Richard's test of the Hub 2.0 flows on the test sheet, then his approve or decline of this proposal. After approval: merge to master and set installerHubUrl to the 2.0 package so customers get it. Not in his design yet: keyboard shortcuts button and sheet (hub-shortcuts-design), the staff area (hub-admin-redesign).",
    refs: "ADLMInstaller branch feat/hub-2-redesign (ddae412, PR #7). Design: adlm-studio-site hub.html, hub.js, splash.js (ca0e6c3). Preview package: https://pub-5729692f58b94673b184370d3c32150a.r2.dev/adlm/installer-hub/1790632654801-ADLMInstallerHub-v2.0.0-preview-20260928.zip",
    design: { status: "needed", link: "https://adlm-studio.vercel.app/hub", surfaces: "Splash + sign-in card, title bar, rail (full and icon-only), Dashboard, Installation Center, Free software, Subscriptions, Install history, Profile, Settings, Help, toasts and confirm cards, offline banner. Built to the design; placeholder only for the keyboard shortcuts button and the staff pages." },
    progress: "Built ahead of approval at the owner's request (27-29 Sep). Hub 2.0.0 on Richard's hub.html design: the splash that becomes the sign-in, Windows title bar, rail, Dashboard, Installation Center, Free software, Subscriptions, Install history, Profile, Settings, Help and contact, toasts and confirm cards, light and dark, small screens. Also: ADLM software only (no courses), one Hub per PC, network signal in the header, Open on installed products (hub-open-button). 29 Sep: finished and tested: 47 automated checks (upload guard, software-only filter, install history, the install engine run into a temp folder, launcher), every screen rendered in light, dark and small windows. Ships as a setup .exe (Inno Setup, 51 MB); install and uninstall tested. Private preview on Richard's checklist (task #79).",
    pending: "Richard's test on the Hub 2.0 checklist (he must be invited as a Contributor for his answers to save), then his approve or decline. After approval: merge ADLMInstaller #7 to master, build the setup .exe from master, and upload it with scripts/upload-hub-release.mjs, which replaces the Hub for paid accounts within five minutes. Not in his design yet: hub-shortcuts-design, hub-admin-redesign, hub-open-button.",
    refs: "ADLMInstaller branch feat/hub-2-redesign (78a994c, PR #7). Design: adlm-studio-site hub.html, hub.js, splash.js (ca0e6c3). Checklist: https://claude.ai/artifact/9LxAJEdcYzDb1uqaAtZb56",
    design: { status: "needed", link: "https://adlm-studio.vercel.app/hub", surfaces: "Splash + sign-in card, title bar, rail (full and icon-only), Dashboard, Installation Center, Free software, Subscriptions, Install history, Profile, Settings, Help, toasts and confirm cards, offline banner. Built to the design; placeholder only for the keyboard shortcuts button, the staff pages and Open." },
  },
  {
    key: "hub-shortcuts-design",
    title: "Installer Hub 2.0: design the keyboard shortcuts button and the shortcuts sheet",
    products: ["installer-hub"],
    kind: "design",
    stage: "building",
    progress: "Built with placeholder styling in Hub 2.0: a Keyboard shortcuts button at the rail foot (full and icon-only rail) that opens the shared shortcuts sheet, also on F1 and Ctrl+/. In the Hub 2.0 preview; listed on the test sheet as not in the design. Design ask sent (task #56).",
    progress: "Built with placeholder styling in Hub 2.0: a Keyboard shortcuts button at the rail foot (full and icon-only rail) that opens the shared shortcuts sheet, also on F1 and Ctrl+/. On the Hub 2.0 checklist as not in the design. Design ask sent (task #56).",
    pending: "Richard's design of the button and the sheet, light and dark.",
    refs: "ADLMInstaller feat/hub-2-redesign: Views/DashboardView.xaml (rail foot), Services/KeyboardShortcuts.cs (sheet).",
    design: { status: "needed", surfaces: "Rail foot: Keyboard shortcuts button beside Sign out, full and icon-only rail. The shortcuts sheet window, light and dark." },
  },
  {
    key: "hub-admin-redesign",
    title: "Installer Hub 2.0: redesign the admin section (Admin Studio and Release sign-off)",
    products: ["installer-hub"],
    kind: "improvement",
    stage: "proposed",
    progress: "Interim build at the owner's request (28 Sep), on the Hub 2.0 components: each staff area is its own rail page (Software, Installations with the pending count, Devices, Free software editor, Manifest editor, Release sign-off). Software is a gallery with a card per product; releasing is only choosing the ZIP (the Hub carries each product's install steps, refuses another product's file, reads the version, fingerprints it and stages it for sign-off); Versions lists every upload with Roll back. Free software works the same, with Add / Edit and the standard free-app install built in. Design ask sent (task #71).",
    pending: "Richard's approve or decline of this proposal, and his design of the staff pages in the Hub 2.0 language. Richard's account is not an admin, so he sees these as screenshots or via an admin account.",
    refs: "ADLMInstaller feat/hub-2-redesign: ViewModels/AdminReleasesViewModel.cs, Views/Hub/SoftwareGallery.xaml, FreeSoftwareGallery.xaml, SoftwareModals.xaml, Views/AdminWorkspaceView.xaml.",
    design: { status: "needed", surfaces: "Software gallery and cards, Upload new version modal, Versions and Roll back modal, Installations list, Devices, Free software gallery and its Add / Edit modal, Manifest editor, Release sign-off. Light and dark." },
    progress: "Interim build at the owner's request (28-29 Sep), on the Hub 2.0 components: each staff area is its own rail page (Software, Installations, Devices, Free software editor, Manifest editor, Release sign-off). Software is a gallery; releasing is only choosing the ZIP (install steps built in, another product's file refused, version read from the name, fingerprinted, staged for sign-off); Versions lists every upload with Roll back. Free software works the same. Richard's Design Access sees these pages on server-masked sample data. Design ask sent (task #71).",
    pending: "Richard's approve or decline of this proposal, and his design of the staff pages in the Hub 2.0 language.",
    refs: "ADLMInstaller feat/hub-2-redesign: ViewModels/AdminReleasesViewModel.cs, Views/Hub/SoftwareGallery.xaml, FreeSoftwareGallery.xaml, SoftwareModals.xaml, Views/AdminWorkspaceView.xaml.",
    design: { status: "needed", surfaces: "Software gallery and cards, Upload new version modal, Versions and Roll back modal, Installations list, Devices, Free software gallery and its Add / Edit modal, Manifest editor, Release sign-off. Light and dark." },
  },
  {
    key: "hub-open-button",
    title: "Installer Hub 2.0: Open button to start any installed ADLM software from the Hub",
    products: ["installer-hub"],
    kind: "feature",
    stage: "proposed",
    progress: "Built at the owner's request (29 Sep). Installed cards read Open and More; with an update waiting, Update, Open and More (Repair moved under More). Open starts HERON, RateGen, Time Pro and free tools themselves, and Revit (QUIV, MEP), Civil 3D (CIVIQ) or Archicad at the version the plugin is registered in, as the signed-in user (an elevated Hub asks Explorer to start it). 9 tests. On the Hub 2.0 checklist as not in the design; business case filed and emailed to the approver.",
    pending: "Richard's approve or decline, and his design of the Open button.",
    refs: "ADLMInstaller feat/hub-2-redesign (78a994c): Services/AppLauncher.cs, Views/Hub/CenterPage.xaml, Views/Hub/FreePage.xaml.",
    design: { status: "needed", link: "https://adlm-studio.vercel.app/hub", surfaces: "Installation Center card actions (Open / Update / More), Free software card (Open once installed), the Opening toast." },
  },
  {
    key: "rategen-splash-signin",
    title: "Rate Gen launch: the splash becomes the sign-in (Richard's design)",
    products: ["rategen"],
    kind: "feature",
    stage: "proposed",
    progress: "Built into RateGen 3.0.0 (owner's instruction, 1 Oct 2026): SplashCard is the sign-in, named loading steps. Staged on the Installer Hub for Richard; on the RateGen 3.0 test sheet (cards Splash and Install).",
    pending: "Richard's approval of this proposal, and his verdict on the RateGen 3.0 test sheet. Forgot-password card not built yet.",
    refs: "ADLMRateGen-SingleUser PR #4 (feat/rategen-suite-ui): Controls/SplashCard.xaml, SplashWindow.xaml, View/SignInUserControl.xaml. Test sheet https://claude.ai/artifact/WN7viscRd8mRzSya2ZSPNs. Design: adlm-studio-site splash-rategen.html (ca0e6c3).",
    design: { status: "needed", link: "https://adlm-studio.vercel.app/splash-rategen", surfaces: "Rate Gen splash and sign-in windows, replaced by one card; forgot-password card." },
  },
  {
    key: "quiv-takeoff-timing",
    title: "QUIV 4.0: record how long auto take-off (and a manual take-off) really takes, for marketing figures",
    products: ["quiv", "website"],
    kind: "feature",
    stage: "proposed",
    progress: "Built ahead of approval at the owner's request. Reuses the existing Takeoff Time Log (/telemetry/takeoff-sessions, baselines, Time saved dashboard) instead of a new collection. QUIV 4.0 sends one record per auto take-off run (mode auto) and one per hand-measured take-off at its first cloud save (mode assisted): timings and counts only, model as a one-way hash, offline outbox. Server: the summary filters and groups by mode, reports medianItems, and leaves ADLM staff out by default. Server side merged (AdlmWeb#33). Privacy policy section merged 27 Sep (AdlmWeb#43). Deleting an account now deletes its take-off records, plus a script for requests (AdlmWeb#46, merged). The 50 test sessions on Adedolapo's account were erased 26 Sep.",
    pending: "Richard's approval. The privacy page is only public once AdlmWeb#54 merges (/privacy was Page not found). The mode filter on the admin Time saved page needs Richard's design. The QUIV side ships with QUIV 4.0.",
    refs: "AdlmWeb#33, #43, #46 (merged) · QUIV RevitPluginArch#3.",
    design: { status: "needed", surfaces: "Admin Time saved page: an auto / hand-measured filter and the median elements figure." },
  },
  {
    key: "release-rollout-firms-first",
    title: "Releases go to firms with more than 5 seats first, and to everyone else three months later",
    products: ["platform", "website", "installer-hub"],
    kind: "improvement",
    stage: "proposed",
    progress: "Built ahead of approval at the owner's request (26 Sep). Approving a plugin release sends it to firms with more than 5 organisation seats (added up across products and accounts). Single users stay on the live build until the approver presses Release to everyone, which unlocks three months later, with a reminder email. Hotfixes can go to everyone. Release emails follow the rollout. 17 new tests, including a real-database run. 27 Sep: run end to end locally against a seeded database and every button pressed on /admin/releases; three small fixes pushed (firm names as spelt, product name in the take-back email, locked button dimmed). Filed on the board 26 Sep; Richard emailed 27 Sep.",
    pending: "Richard's approval, then merging and deploying AdlmWeb#50. It must deploy before QUIV 4.0.0 is approved, or 4.0.0 goes to everyone under the old rule.",
    refs: "AdlmWeb#50 feat/release-rollout 7c1fe33 (worktree ADLMWebsite-rollout).",
    design: { status: "needed", surfaces: "/admin/releases: the 'With firms, waiting for everyone' section and the hotfix switch on pending releases. Possibly an early-access label in the Installer Hub." },
  },
  {
    key: "public-legal-pages",
    title: "The privacy, terms and licensing pages were Page not found on the live site",
    products: ["website"],
    kind: "fix",
    stage: "testing",
    summary: "Every footer and the sign-up form link /privacy, /terms and /licensing, but those pages exist only in Richard's redesign, staff-only under /preview until launch.",
    progress: "Fixed 27 Sep: the three pages are served publicly in the redesign's shell, like /certificate, and nothing else of the redesign is exposed. Checked locally signed out: all three render, none links to /preview, and unknown paths are still Page not found. Richard emailed 27 Sep.",
    pending: "Richard's review and merge of AdlmWeb#54.",
    refs: "AdlmWeb#54 fix/public-legal-pages e5321da (worktree ADLMWebsite-legal).",
    design: { status: "not-needed" },
  },
  {
    key: "client-bill-fill",
    title: "Client bill fill: import any firm's own BoQ, and AI fills the quantities from QUIV",
    products: ["quiv", "ai-service"],
    kind: "feature",
    stage: "building",
    decision: "grandfathered",
    summary: "Every firm has its own bill format. ADLM should fill theirs instead of forcing its template.",
    progress: "The AI fill endpoint has been live since 19 Sep. The reader was then audited sheet by sheet against the cells of about 730 real client workbooks (582 local, the rest from the Drive folder, 40 firms): 39 confirmed defects, all fixed. It no longer fills the RATE column of an unpriced bill, refuses price lists and tables that are not bills, keeps one unit vocabulary (Lin.M, Sq M, Nos, L.Sum, ditto marks), treats a repeated header row and a swapped unit/qty row as unfillable, joins multi-row SMM items, and nests bill > element > floor context. Workbooks with at least one fillable bill sheet went 501 to 526; 386 tests green.",
    pending: "The page has never been opened inside Revit — that is the next step, on a real client bill. 44 audit findings from three Drive groups are still being re-checked. Twelve product decisions are waiting on Adedolapo and Richard: which quantity column to fill on a bill measured per block or phase, what to do with a typical-floor multiplier, whether to overwrite a QS's own dimension formulas, and whether to auto-convert the 40-odd .xls bills. After QUIV: HERON, then MEP and CIVIQ. The AI branch is live but not merged, so a deploy from main would drop it.",
    blockedOn: "",
    refs: "QUIV nw/ feat/client-bill-fill · adlm-ai-service-boqfill feat/boq-fill",
    design: { status: "needed", surfaces: "QUIV: import a bill, map its columns, review the AI matches, write the quantities back." },
  },
  {
    key: "quiv-popups",
    title: "QUIV popups: right size, and close with the keyboard",
    products: ["quiv"],
    kind: "fix",
    stage: "building",
    progress: "In progress in a session right now.",
    pending: "Finish, then test inside Revit.",
    refs: "QUIV nw/ checkout",
    design: { status: "not-needed" },
  },
  {
    key: "quiv-takeoff-speed",
    title: "QUIV auto take-off speed and the take-off list editing bug",
    products: ["quiv"],
    kind: "fix",
    stage: "testing",
    progress: "The fix is built. The last full run, on 12 Sep, planned 551 steps and took 21 minutes. It rebuilt the bill grid 1,330 times.",
    pending: "Run an auto take-off on the tower model and compare it with 12 Sep. Curtain Wall averaged 39 seconds per step and needs a check.",
    blockedOn: "Adedolapo: one auto take-off run in Revit",
    refs: "QUIV nw/ checkout",
    design: { status: "not-needed" },
  },

  // ── HERON (PlanSwift) ────────────────────────────────────────────────────
  {
    key: "heron-auto-takeoff",
    title: "HERON AI auto take-off (beta channel only)",
    products: ["heron"],
    kind: "feature",
    stage: "building",
    decision: "grandfathered",
    progress: "It squares the outline and measures its own error. The public build hides it; beta machines see it.",
    pending: "Decide when it leaves beta. The version numbers disagree: the csproj says 3.0.0, the zips are 2.9.x and Installer.iss says 2.9.1.",
    refs: "ADLMPlanswiftApp claude/sleepy-ritchie-rwshbh",
    design: { status: "needed", surfaces: "Auto take-off panel: pick items, show confidence, accept or reject" },
  },

  // ── Across every product ─────────────────────────────────────────────────
  {
    key: "keyboard-shortcuts",
    title: "Keyboard shortcuts in every ADLM product, with an F1 / Ctrl+/ help sheet",
    products: ["quiv", "heron", "mep", "rategen", "installer-hub", "website"],
    kind: "feature",
    stage: "testing",
    decision: "grandfathered",
    summary: "The same keys mean the same thing everywhere: Ctrl+1..9 sections, Ctrl+F search, Ctrl+S save, F5 sync, Ctrl+E export. The web uses Alt+1..9 because the browser owns Ctrl.",
    progress: "All 5 desktop builds are clean and the QUIV tests pass. The web version was checked in the browser.",
    pending: "Not committed in any repo. Not yet tried inside Revit or PlanSwift. The session stopped at the usage limit on 21 Sep.",
    refs: "Uncommitted in QUIV nw/, HERON, MEP, RateGen public build, Installer Hub, ADLMWebsite",
    design: { status: "needed", surfaces: "The shortcut help sheet, and the header help button" },
  },
  {
    key: "network-indicator",
    title: "Network signal bars in all 7 products",
    products: ["quiv", "heron", "mep", "rategen", "installer-hub", "website", "mobile"],
    kind: "feature",
    stage: "testing",
    decision: "grandfathered",
    summary: "Four bars from the measured round trip to the ADLM server, so a slow sync can be told apart from a broken one.",
    progress: "Shipped in HERON 2.9.3 on 12 Sep. Built and tested in the other six.",
    pending: "Installer Hub: committed in Hub 2.0 (feat/hub-2-redesign), ships with it. Still uncommitted in QUIV, MEP, RateGen, web and mobile. Commit them, then ship with each product's next release.",
    refs: "See the network-indicator note; QUIV lives in the nw/ checkout",
    design: { status: "needed", surfaces: "Header indicator: bars, 'No server', 'Offline'" },
  },
  {
    key: "calibrated-material-defaults",
    title: "Material conversion defaults calibrated from real client build-ups",
    products: ["website", "quiv", "heron"],
    kind: "improvement",
    stage: "building",
    decision: "grandfathered",
    summary: "Quantity-to-material factors (bags per m3, blocks per m2 and so on) taken from how QS firms actually build their rates, not assumed.",
    progress: "Under way on its own branch.",
    pending: "The session stopped at the usage limit on 21 Sep in the middle of the work. 3 files are uncommitted.",
    refs: "ADLMWebsite-calib feat/calibrated-material-defaults",
    design: { status: "not-needed" },
  },
  {
    key: "sample-projects",
    title: "Read-only sample projects for learning, in every product with a cloud view",
    products: ["quiv", "heron", "mep", "civiq", "archicad", "website"],
    kind: "feature",
    stage: "testing",
    decision: "grandfathered",
    summary: "Every subscriber gets four worked projects in their product, each with its bill, budget, valuations and programme, and a 3D model where the product has one, so they learn on real-looking data. The user guide screenshots will come from these too.",
    progress: "Built for all five products (20 samples): QUIV and HERON duplexes by foundation type, Revit MEP services for the same duplexes, four CIVIQ roads (asphalt, concrete, interlock, laterite), and ArchiCAD duplexes with their BoQ versions. Every IFC model passes web-ifc; the server tests pass. Samples also show on the /work tool pages and the ArchiCAD landing page.",
    pending: "Needs approval to write the samples to the production database and R2. Then review, merge and the API deploy.",
    blockedOn: "Adedolapo: approve the seed against production",
    refs: "ADLMWebsite-samples feat/sample-projects (3 commits)",
    design: { status: "needed", surfaces: "The 'Learning samples' row on /projects/:tool, /work/tool/:t and /archicad; the read-only banner on an opened sample and on the ArchiCAD BoQ page" },
  },
  {
    key: "takeoff-time-log",
    title: "Takeoff Time Log: hours saved per firm, user and product",
    products: ["quiv", "heron", "website"],
    kind: "feature",
    stage: "testing",
    decision: "grandfathered",
    progress: "Pushed on feature branches in all three repos on 10 Sep. The admin page is at /admin/time-saved.",
    pending: "Merge and release. The saved-time rates are stated assumptions until they are calibrated against real use.",
    refs: "feat/takeoff-time-log (website, HERON, QUIV)",
    design: { status: "needed", surfaces: "Admin Time saved page; a customer-facing 'hours saved' figure if we want one" },
  },

  // ── Website, mail and learning ───────────────────────────────────────────
  {
    key: "video-notifications",
    title: "Email subscribers when a new ADLM video goes up",
    products: ["website"],
    kind: "feature",
    stage: "testing",
    decision: "grandfathered",
    progress: "Merged to main on 15 Sep. The SSM parameters are set.",
    pending: "Deploy the scheduled poll (VideoPollFn). Its workflow is disabled. The back catalogue is already marked as sent, so the first mail goes out with the next upload.",
    refs: "docs/VIDEO_NOTIFICATIONS.md",
    design: { status: "needed", surfaces: "The new-video email" },
  },
  {
    key: "weekly-release-digest",
    title: "Weekly digest of product releases for subscribers",
    products: ["website"],
    kind: "feature",
    stage: "building",
    decision: "grandfathered",
    progress: "Model, builder, email and tests written.",
    pending: "18 files uncommitted. It has to respect the release gate: a release that has not been signed off is not in the digest.",
    refs: "ADLMWebsite-digest feat/weekly-release-digest",
    design: { status: "needed", surfaces: "The digest email" },
  },
  {
    key: "mail-compliance-gate",
    title: "Bulk mail gate: circuit breaker, daily cap and a bulk token",
    products: ["website", "infra"],
    kind: "infra",
    stage: "building",
    progress: "The gate engine is written: sendBulk, a circuit breaker and a daily cap.",
    pending: "2 unpushed commits and 1 uncommitted file. Mail stays SES-only.",
    refs: "_mailgate-wt feat/mail-compliance-gate",
    design: { status: "not-needed" },
  },
  {
    key: "ysa-checkin",
    title: "YSA learner check-in email: Wednesday 23 Sep, 10:00 WAT",
    products: ["website"],
    kind: "content",
    stage: "building",
    progress: "43 recipients are queued and 53 of 53 payers are unlocked. A reminder is set for 23 Sep 10:00 WAT.",
    pending: "On Wednesday, say 'send the check-in' in a live session. Nothing sends before that. From then on, the weekly slot is Wednesday about 10:00 WAT.",
    blockedOn: "Adedolapo: the go on Wednesday",
    refs: "Session 'YSA demo video section'",
    design: { status: "not-needed" },
  },
  {
    key: "user-guides",
    title: "ADLM software user guides (PDF), and the email that sends them",
    products: ["platform"],
    kind: "content",
    stage: "building",
    progress: "The guide email and the send script are drafted.",
    pending: "They are uncommitted in the main ADLMWebsite checkout. The guide screenshots are waiting for the sample projects.",
    refs: "server/scripts/send-user-guides.mjs, server/util/guideEmail.js (uncommitted)",
    design: { status: "needed", surfaces: "The guide PDF layout, and the guide email" },
  },
  {
    key: "signup-guard",
    title: "Sign-up protection against the bot wave",
    products: ["website"],
    kind: "fix",
    stage: "testing",
    progress: "Built.",
    pending: "1 unpushed commit. Push it, open a PR, and stage it on preview.",
    refs: "ADLMWebsite-hotfix fix/signup-guard",
    design: { status: "not-needed" },
  },
  {
    key: "cors-logging",
    title: "Log the requests CORS refuses, so blocked users are visible",
    products: ["website", "infra"],
    kind: "fix",
    stage: "testing",
    progress: "Built.",
    pending: "1 unpushed commit. The marketplace session stopped at the usage limit in the middle of a CORS change that depends on this.",
    refs: "ADLMWebsite-corslog fix/log-cors-rejections",
    design: { status: "not-needed" },
  },
  {
    key: "device-seat",
    title: "One PC is one seat, even when the Installer Hub and QUIV hash it differently",
    products: ["installer-hub", "quiv", "website"],
    kind: "fix",
    stage: "shipped",
    progress: "On main (51be171).",
    pending: "",
    refs: "fix/device-scheme-aware-binding",
    design: { status: "not-needed" },
  },
  {
    key: "old-open-prs",
    title: "Old open pull requests to merge or close",
    products: ["website"],
    kind: "infra",
    stage: "on-hold",
    progress: "",
    pending: "#14 QUIV 3.1.11 changelog, #8 WhatsApp AI brief (naira quotable), #6 remove the legacy bundle discounts, #3 correct the NGN to USD rate (pricing), #1 the feature reference. They date from June to August. Each one needs a yes or a close.",
    refs: "github.com/adedola12/AdlmWeb/pulls",
    design: { status: "not-needed" },
  },

  // ── Other products ───────────────────────────────────────────────────────
  {
    key: "qs-takeoff-app",
    title: "QS Takeoff: the standalone take-off app",
    products: ["qs-app"],
    kind: "feature",
    stage: "building",
    decision: "grandfathered",
    summary: "A standalone take-off app that works on drawings without PlanSwift, with templates, formulas, markups, reports and bill and budget builders. It is a separate product from Time Pro.",
    progress: "Resuming: Adedolapo decided on 6 Oct 2026 that the app goes ahead. The last commit was on 30 Jun: saved take-off markups persist and redraw, and PlanSwift tokens are mapped. Since then: reports, the bill builder, the budget builder, estimating, editable material constants and markup node editing, all merged to master on 6 Oct 2026. A new feature, an IFC engine that imports, merges and aligns IFC models for QUIV-style take-off, is proposed as its own item (qs-takeoff-ifc-engine) and waits for approval.",
    pending: "Try the Bill & Budget tab in the running app; it has only been built, not tested by hand. Write the app's business case here: price, who buys it instead of HERON, and what it costs to support. The IFC engine is not built until Richard approves qs-takeoff-ifc-engine.",
    blockedOn: "Richard: approve or decline the IFC engine proposal (qs-takeoff-ifc-engine)",
    refs: "github.com/adedola12/QSApp master (all work pushed and merged 6 Oct 2026, QSApp#1) · proposed shared library source/repos/ADLM.IfcEngine",
    design: { status: "needed", surfaces: "The whole app: workspace, measurement setup, templates, reports" },
  },
  {
    key: "adlm-market",
    title: "ADLM Market: marketplace rebuild with a RateGen price index and forecast",
    products: ["marketplace", "rategen", "ai-service"],
    kind: "feature",
    stage: "building",
    decision: "grandfathered",
    summary: "A staff-only internal build for now. Phase 1.5 covers the RateGen price index, price trends, supplier calls and a price forecast.",
    progress: "Staff-only build on its own branch. A live price forecast exists behind a data gate.",
    pending: "Neither branch has a remote. The session stopped at the usage limit in the middle of a CORS change on 21 Sep. It needs a business case before it goes beyond staff: who pays and for what.",
    refs: "mernsite-1 rebuild/ai-marketplace · adlm-ai-service-forecast feat/price-forecast",
    design: { status: "needed" },
  },
  {
    key: "mep-correctness",
    title: "Revit MEP Suite: correctness pass (phase A)",
    products: ["mep"],
    kind: "fix",
    stage: "building",
    progress: "The last commit was on 6 Aug.",
    pending: "34 files are uncommitted. They mix this pass with the network indicator and keyboard shortcuts. Sort them, commit them and test.",
    refs: "ADLMRvtMEPPlugin phase-a-correctness",
    design: { status: "not-needed" },
  },
  {
    key: "ai-service-main",
    title: "AI service: the live branches are not on main",
    products: ["ai-service", "infra"],
    kind: "infra",
    stage: "testing",
    progress: "Live on AWS: main plus the caller library, breakdown fill and boq-fill. It runs on the direct Anthropic API because Bedrock is still blocked for the account.",
    pending: "Merge the three branches to main. A deploy from main today would silently remove client bill fill.",
    refs: "adlm-ai-service, adlm-ai-service-boqfill",
    design: { status: "not-needed" },
  },
  {
    key: "archicad",
    title: "QUIV for ArchiCAD",
    products: ["archicad"],
    kind: "feature",
    stage: "on-hold",
    decision: "grandfathered",
    progress: "The connector, the backend, the costing engine and 4 pages are built. It was checked against ArchiCAD 28 with a test building.",
    pending: "The connector folder is not under git. Then test end to end with live rates and a real client project.",
    refs: "source/repos/quiv-archicad (no git) + ADLMWebsite /api/archicad",
    design: { status: "needed" },
  },
  {
    key: "mobile-billing",
    title: "Mobile app: billing, renewal and profile",
    products: ["mobile"],
    kind: "feature",
    stage: "on-hold",
    decision: "grandfathered",
    progress: "The last commit was on 11 Aug: EAS build profiles and device-testing notes.",
    pending: "The branch has no remote, and 6 files are uncommitted.",
    refs: "adlm-mobile feat/billing-renewal-profile",
    design: { status: "needed" },
  },
  {
    key: "whatsapp-bot",
    title: "WhatsApp sales bot: sync qualified chats to the Notion CRM",
    products: ["whatsapp-bot"],
    kind: "feature",
    stage: "on-hold",
    decision: "grandfathered",
    progress: "Phase 2 is done: qualified chats sync to Notion (12 Aug).",
    pending: "No remote, and 14 files are uncommitted.",
    refs: "source/repos/ADLMWhatsAppBot",
    design: { status: "not-needed" },
  },
  {
    key: "work-board",
    title: "This board: approval before build, and a design track beside the code",
    products: ["platform"],
    kind: "infra",
    stage: "testing",
    summary: "From 22 Sep 2026, every new feature or button starts here as a proposal with its business case. Richard approves it before it is designed or built. He designs while it is coded.",
    progress: "Built on its own branch, with tests. The API side is live, so proposals are already filed and emailed. Fix 27 Sep: the approver's proposal email is held until /admin/work is in the live site (on 26 Sep Richard's \"Open the work board\" button opened a 404, because the page is not merged yet). Held proposals go out in one email once it is.",
    pending: "Review and merge PR #22; that puts the page live. Then run `work-board.mjs notify-held --apply` for anything held, and redeploy the API (after `cdk diff`) so the board's own propose route holds too.",
    blockedOn: "Richard: approve PR #22.",
    refs: "AdlmWeb PR #22 (feat/work-board, fix 6085fa0) · docs/WORK_BOARD.md",
    design: { status: "needed", surfaces: "This board: summary tiles, the proposal form, the decision buttons, the design track" },
  },
  {
    key: "r2-model-drift-alerts",
    title: "Model drift alerts: warn when the Revit / ArchiCAD model has changed since the last take-off saved on the web",
    products: ["quiv", "archicad", "website"],
    kind: "feature",
    stage: "proposed",
    summary: "When a model linked to a cloud project changes after its last take-off (elements added, removed or resized), tell the QS before they price, value or certify from a stale bill. Phase 1 (desktop): QUIV compares the open model with the project's saved element IDs and quantities, shows the difference, and reports a drift summary to the website. Phase 2 (web): the project page and the /work dashboard show a 'Model changed since last take-off' badge, and the owner gets one SES email. ArchiCAD follows the same contract. DESKTOP DEPENDENCY: the detection must run in the plugins, because the website stores no model versions.",
    progress: "Built locally on 27 Sep 2026 while approval is pending, NOT pushed. Website (AdlmWeb feat/r2-model-drift-alerts): POST /projects/:key/:id/model-drift + /dismiss, drift cleared on the next take-off save, ModelDriftEvent log for the success metric, one owner email via SES, badge data on the project, gallery, merged parts and /me/work-overview, placeholder chips; server and client tests pass. QUIV (RevitPluginArch feat/model-drift-alerts): bounded, cancellable check on project open (removed / resized / added, per bill line), local baseline after each save, Bill banner with 'Not a real change'; builds for Revit 2024-2027, 331 tests pass.",
    pending: "Richard: approve, and design the surfaces. Then push both branches, open PRs, website ships before the QUIV release. ArchiCAD: its plugin (source/repos/quiv-archicad) is not under git and sends no model fingerprint yet, so it needs a model stamp first. Privacy policy needs a 'Model change checks' paragraph (Richard's ds/pages).",
    blockedOn: "Richard: approval (work board).",
    refs: "AdlmWeb feat/r2-model-drift-alerts · RevitPluginArch feat/model-drift-alerts · server/services/modelDrift.js · QUIV Services/ModelDrift",
    design: {
      status: "needed",
      surfaces: "QUIV: drift panel on model open (what changed, per bill line; 'retake affected lines', 'not a real change'). Web: 'Model changed since last take-off' badge on the project header, projects gallery and /work dashboard 'Needs a decision' table; owner email. ArchiCAD: same panel later.",
    },
  },
];
