// server/scripts/work-board.seed.mjs
//
// Everything in flight across ADLM on 22 Sep 2026, from a run through every
// open Claude session and every product repo. Loaded by work-board.mjs seed.
//
// Work already under way before the proposal-first rule is "grandfathered":
// it keeps moving, and Richard can still comment or ask for a design pass.
// Fixes and infrastructure are "not-required". Nothing here invents a
// business case: where one is missing, `pending` says so.
//
// Re-running the seed refreshes summary / progress / pending / blockedOn /
// refs only. Stage, decision, design and comments are set once, on insert,
// so nothing Richard decides on the board is ever overwritten by a re-seed.

export const AS_OF = "22 Sep 2026";

export const SEED = [
  // ── The release gate and how releases reach customers ────────────────────
  {
    key: "release-gate",
    title: "Release gate: nothing reaches customers without Richard's sign-off",
    products: ["platform", "infra"],
    kind: "infra",
    stage: "testing",
    summary: "Every plugin release waits at the Release sign-off desk; website changes are staged at preview.adlmstudio.net first.",
    progress: "Sign-off desk live on main (PRs #17, #18). preview.adlmstudio.net serves the release branch, HTTPS up since 04:24 UTC 22 Sep; signed-out visitors see only the staff wall. Locked 3-year audit bucket in stack AdlmReleaseGate.",
    pending: "PR #20 (lock the production environment even before the approver accepts) needs review. Then Richard is made the required approver on API deploys.",
    blockedOn: "Richard: accept the GitHub invite for RichardEnoch, then review PR #20.",
    refs: "AdlmWeb PR #20 (feat/release-gate) · docs/RELEASE_GATE.md",
    design: { status: "not-needed" },
  },
  {
    key: "plugin-release-scripts",
    title: "Release scripts say 'staged, awaiting sign-off' instead of 'live'",
    products: ["installer-hub", "rategen", "quiv", "heron", "mep"],
    kind: "infra",
    stage: "testing",
    progress: "Installer Hub package scripts report staged builds from the gate; announce-release.ps1 refuses versions still awaiting sign-off; RateGen push-installer-update handles the gate.",
    pending: "Give Richard access to the ADLMInstaller repo so he can review the two PRs. GitHub refused a read-only invite: it is a private repo on a personal account, where every collaborator gets write access.",
    blockedOn: "Adedolapo: invite Richard with write access, or move the repo into an ADLM GitHub organisation (which has a real read-only role).",
    refs: "ADLMInstallerHub claude/build-all-packages · ADLMInstallerHub-guard fix/hub-block-install-while-host-running · ADLMRateGenPublicBuild may30-version",
    design: { status: "not-needed" },
  },
  {
    key: "hotfix-review-fixes",
    title: "Hotfix: download names keep their letters; WhatsApp code tied to its number",
    products: ["website"],
    kind: "fix",
    stage: "awaiting-signoff",
    summary: "Two live bugs found while reviewing the redesign branch. Assignment downloads lose every letter r ('Chapte epot.docx'); a WhatsApp code could verify a different number.",
    progress: "Fixed with tests; 608 server tests pass; the Lambda bundle builds.",
    pending: "Merge PR #19. Merging deploys the API, which also needs approval on the production environment.",
    blockedOn: "PR #19 review",
    refs: "AdlmWeb PR #19 (hotfix/review-fixes)",
    design: { status: "not-needed" },
  },
  {
    key: "admin-roles-editor",
    title: "Launch build: admins can assign roles and edit role areas again",
    products: ["website"],
    kind: "fix",
    stage: "awaiting-signoff",
    summary: "On the launch build /admin/roles is a read-only register, and the classic role editor had no route. After go-live nobody could give a person a role (for example Tech Support, PR #28) or change what a role reaches.",
    progress: "The classic editor is routed at /admin/roles/edit (admins only) and linked from the register as 'Edit roles'. Lint is clean and the client build passes. Opened 25 Sep against release.",
    pending: "Richard approves PR #29 into release. Then one signed-in check on preview.adlmstudio.net: Roles, Edit roles, give someone Tech Support. Afterwards, an editor drawn in his design, which also confirms and audits area changes (today those save at once, unconfirmed and unaudited).",
    blockedOn: "PR #29 review",
    refs: "AdlmWeb PR #29 (fix/admin-roles-editor -> release) · client/src/ds/DsAdminRoles.jsx · client/src/pages/AdminRoles.jsx · server/routes/admin.roles.js",
    design: { status: "needed", surfaces: "Roles editor in his admin grammar: create and delete a role, the area matrix, assigning people, a confirmation and an audit line on every change, a warning before the last administrator loses access" },
  },

  // ── Richard's redesign ───────────────────────────────────────────────────
  {
    key: "redesign-port",
    title: "Richard's redesign brought into the live site (review items R01 to R22 + his 17 Sep update)",
    products: ["website"],
    kind: "design",
    stage: "building",
    summary: "Porting his static rebuild onto the real app with real data: black theme, feedback toasts, the projects restructure (My tools, gallery, workspace tabs), certificates with QR verification, assignments, the composer signature.",
    progress: "47 commits on the review branch. A session is working on it right now.",
    pending: "Finish the P0 port and the R-items. Parts of the projects restructure need data we do not have yet (the plan lists them as Q1). Then open a PR for Richard to review on preview.adlmstudio.net.",
    blockedOn: "",
    refs: "ADLMWebsite-review fix/richard-review-sep16 (PLAN.md) · Richard's repo RichardEnoch/adlm-studio-site",
    design: { status: "adopted", link: "https://adlm-studio.vercel.app", notes: "It is his design. The port does not change it." },
  },
  {
    key: "redesign-open-items",
    title: "Redesign open items that need a decision or a backend (about 20)",
    products: ["website", "platform"],
    kind: "design",
    stage: "in-design",
    summary: "Section 7 of his PROJECT-SUMMARY.md: roughly 20 items where the design is done or nearly done, and what is missing is a decision or a backend.",
    progress: "97 built pages (66 marketing and app, 31 admin), live at adlm-studio.vercel.app.",
    pending: "Go through section 7 together and put each item on this board as a proposal, so it gets a business case and a yes or no.",
    blockedOn: "Adedolapo and Richard: a joint pass",
    refs: "ADLMWebNewUI/PROJECT-SUMMARY.md §7",
    design: { status: "in-progress", link: "https://adlm-studio.vercel.app" },
  },

  // ── QUIV (Revit) ─────────────────────────────────────────────────────────
  {
    key: "client-bill-fill",
    title: "Client bill fill: import any firm's own BoQ, and AI fills the quantities from QUIV",
    products: ["quiv", "ai-service"],
    kind: "feature",
    stage: "building",
    decision: "grandfathered",
    summary: "Every firm has its own bill format. ADLM should fill theirs instead of forcing its template.",
    progress: "The AI fill endpoint has been live since 19 Sep. The reader was then audited sheet by sheet against the cells of about 730 real client workbooks (582 local, the rest from the Drive folder, 40 firms): 39 confirmed defects, all fixed. It no longer fills the RATE column of an unpriced bill, refuses price lists and tables that are not bills, keeps one unit vocabulary (Lin.M, Sq M, Nos, L.Sum, ditto marks), treats a repeated header row and a swapped unit/qty row as unfillable, joins multi-row SMM items, and nests bill > element > floor context. Workbooks with at least one fillable bill sheet went 501 to 526; 386 tests green.",
    pending: "The page has never been opened inside Revit — that is the next step, on a real client bill. 44 audit findings from three Drive groups are still being re-checked. Twelve product decisions are waiting on Adedolapo and Richard: which quantity column to fill on a bill measured per block or phase, what to do with a typical-floor multiplier, whether to overwrite a QS's own dimension formulas, and whether to auto-convert the 40-odd .xls bills. After QUIV: HERON, then MEP and CIVIQ. The AI branch is live but not merged, so a deploy from main would drop it.",
    blockedOn: "",
    refs: "QUIV nw/ feat/client-bill-fill · adlm-ai-service-boqfill feat/boq-fill",
    design: { status: "needed", surfaces: "QUIV: import a bill, map its columns, review the AI matches, write the quantities back." },
  },
  {
    key: "quiv-popups",
    title: "QUIV popups: right size, and close with the keyboard",
    products: ["quiv"],
    kind: "fix",
    stage: "building",
    progress: "In progress in a session right now.",
    pending: "Finish, then test inside Revit.",
    refs: "QUIV nw/ checkout",
    design: { status: "not-needed" },
  },
  {
    key: "quiv-takeoff-speed",
    title: "QUIV auto take-off speed and the take-off list editing bug",
    products: ["quiv"],
    kind: "fix",
    stage: "testing",
    progress: "The fix is built. The last full run, on 12 Sep, planned 551 steps and took 21 minutes. It rebuilt the bill grid 1,330 times.",
    pending: "Run an auto take-off on the tower model and compare it with 12 Sep. Curtain Wall averaged 39 seconds per step and needs a check.",
    blockedOn: "Adedolapo: one auto take-off run in Revit",
    refs: "QUIV nw/ checkout",
    design: { status: "not-needed" },
  },

  // ── HERON (PlanSwift) ────────────────────────────────────────────────────
  {
    key: "heron-auto-takeoff",
    title: "HERON AI auto take-off (beta channel only)",
    products: ["heron"],
    kind: "feature",
    stage: "building",
    decision: "grandfathered",
    progress: "It squares the outline and measures its own error. The public build hides it; beta machines see it.",
    pending: "Decide when it leaves beta. The version numbers disagree: the csproj says 3.0.0, the zips are 2.9.x and Installer.iss says 2.9.1.",
    refs: "ADLMPlanswiftApp claude/sleepy-ritchie-rwshbh",
    design: { status: "needed", surfaces: "Auto take-off panel: pick items, show confidence, accept or reject" },
  },

  // ── Across every product ─────────────────────────────────────────────────
  {
    key: "keyboard-shortcuts",
    title: "Keyboard shortcuts in every ADLM product, with an F1 / Ctrl+/ help sheet",
    products: ["quiv", "heron", "mep", "rategen", "installer-hub", "website"],
    kind: "feature",
    stage: "testing",
    decision: "grandfathered",
    summary: "The same keys mean the same thing everywhere: Ctrl+1..9 sections, Ctrl+F search, Ctrl+S save, F5 sync, Ctrl+E export. The web uses Alt+1..9 because the browser owns Ctrl.",
    progress: "All 5 desktop builds are clean and the QUIV tests pass. The web version was checked in the browser.",
    pending: "Not committed in any repo. Not yet tried inside Revit or PlanSwift. The session stopped at the usage limit on 21 Sep.",
    refs: "Uncommitted in QUIV nw/, HERON, MEP, RateGen public build, Installer Hub, ADLMWebsite",
    design: { status: "needed", surfaces: "The shortcut help sheet, and the header help button" },
  },
  {
    key: "network-indicator",
    title: "Network signal bars in all 7 products",
    products: ["quiv", "heron", "mep", "rategen", "installer-hub", "website", "mobile"],
    kind: "feature",
    stage: "testing",
    decision: "grandfathered",
    summary: "Four bars from the measured round trip to the ADLM server, so a slow sync can be told apart from a broken one.",
    progress: "Shipped in HERON 2.9.3 on 12 Sep. Built and tested in the other six.",
    pending: "Uncommitted in QUIV, MEP, RateGen, Installer Hub, web and mobile. Commit them, then ship with each product's next release.",
    refs: "See the network-indicator note; QUIV lives in the nw/ checkout",
    design: { status: "needed", surfaces: "Header indicator: bars, 'No server', 'Offline'" },
  },
  {
    key: "calibrated-material-defaults",
    title: "Material conversion defaults calibrated from real client build-ups",
    products: ["website", "quiv", "heron"],
    kind: "improvement",
    stage: "building",
    decision: "grandfathered",
    summary: "Quantity-to-material factors (bags per m3, blocks per m2 and so on) taken from how QS firms actually build their rates, not assumed.",
    progress: "Under way on its own branch.",
    pending: "The session stopped at the usage limit on 21 Sep in the middle of the work. 3 files are uncommitted.",
    refs: "ADLMWebsite-calib feat/calibrated-material-defaults",
    design: { status: "not-needed" },
  },
  {
    key: "sample-projects",
    title: "Read-only sample duplex projects for learning (strip, pad and strip, raft, pile)",
    products: ["quiv", "heron", "website"],
    kind: "feature",
    stage: "testing",
    decision: "grandfathered",
    summary: "Every subscriber gets four worked duplex projects, each with its model, bill, budget and valuations, so they learn on real-looking data. The user guide screenshots will come from these too.",
    progress: "The generator and the read-only guards are built.",
    pending: "Needs approval to write the samples to the production database and R2. Then the API deploy and the merge. After that: MEP, CIVIQ, ArchiCAD.",
    blockedOn: "Adedolapo: approve the seed against production",
    refs: "ADLMWebsite-samples feat/sample-projects (1 unpushed commit)",
    design: { status: "needed", surfaces: "Where samples appear in the project gallery, and the 'sample, read-only' badge" },
  },
  {
    key: "takeoff-time-log",
    title: "Takeoff Time Log: hours saved per firm, user and product",
    products: ["quiv", "heron", "website"],
    kind: "feature",
    stage: "testing",
    decision: "grandfathered",
    progress: "Pushed on feature branches in all three repos on 10 Sep. The admin page is at /admin/time-saved.",
    pending: "Merge and release. The saved-time rates are stated assumptions until they are calibrated against real use.",
    refs: "feat/takeoff-time-log (website, HERON, QUIV)",
    design: { status: "needed", surfaces: "Admin Time saved page; a customer-facing 'hours saved' figure if we want one" },
  },

  // ── Website, mail and learning ───────────────────────────────────────────
  {
    key: "video-notifications",
    title: "Email subscribers when a new ADLM video goes up",
    products: ["website"],
    kind: "feature",
    stage: "testing",
    decision: "grandfathered",
    progress: "Merged to main on 15 Sep. The SSM parameters are set.",
    pending: "Deploy the scheduled poll (VideoPollFn). Its workflow is disabled. The back catalogue is already marked as sent, so the first mail goes out with the next upload.",
    refs: "docs/VIDEO_NOTIFICATIONS.md",
    design: { status: "needed", surfaces: "The new-video email" },
  },
  {
    key: "weekly-release-digest",
    title: "Weekly digest of product releases for subscribers",
    products: ["website"],
    kind: "feature",
    stage: "building",
    decision: "grandfathered",
    progress: "Model, builder, email and tests written.",
    pending: "18 files uncommitted. It has to respect the release gate: a release that has not been signed off is not in the digest.",
    refs: "ADLMWebsite-digest feat/weekly-release-digest",
    design: { status: "needed", surfaces: "The digest email" },
  },
  {
    key: "mail-compliance-gate",
    title: "Bulk mail gate: circuit breaker, daily cap and a bulk token",
    products: ["website", "infra"],
    kind: "infra",
    stage: "building",
    progress: "The gate engine is written: sendBulk, a circuit breaker and a daily cap.",
    pending: "2 unpushed commits and 1 uncommitted file. Mail stays SES-only.",
    refs: "_mailgate-wt feat/mail-compliance-gate",
    design: { status: "not-needed" },
  },
  {
    key: "ysa-checkin",
    title: "YSA learner check-in email: Wednesday 23 Sep, 10:00 WAT",
    products: ["website"],
    kind: "content",
    stage: "building",
    progress: "43 recipients are queued and 53 of 53 payers are unlocked. A reminder is set for 23 Sep 10:00 WAT.",
    pending: "On Wednesday, say 'send the check-in' in a live session. Nothing sends before that. From then on, the weekly slot is Wednesday about 10:00 WAT.",
    blockedOn: "Adedolapo: the go on Wednesday",
    refs: "Session 'YSA demo video section'",
    design: { status: "not-needed" },
  },
  {
    key: "user-guides",
    title: "ADLM software user guides (PDF), and the email that sends them",
    products: ["platform"],
    kind: "content",
    stage: "building",
    progress: "The guide email and the send script are drafted.",
    pending: "They are uncommitted in the main ADLMWebsite checkout. The guide screenshots are waiting for the sample projects.",
    refs: "server/scripts/send-user-guides.mjs, server/util/guideEmail.js (uncommitted)",
    design: { status: "needed", surfaces: "The guide PDF layout, and the guide email" },
  },
  {
    key: "signup-guard",
    title: "Sign-up protection against the bot wave",
    products: ["website"],
    kind: "fix",
    stage: "testing",
    progress: "Built.",
    pending: "1 unpushed commit. Push it, open a PR, and stage it on preview.",
    refs: "ADLMWebsite-hotfix fix/signup-guard",
    design: { status: "not-needed" },
  },
  {
    key: "cors-logging",
    title: "Log the requests CORS refuses, so blocked users are visible",
    products: ["website", "infra"],
    kind: "fix",
    stage: "testing",
    progress: "Built.",
    pending: "1 unpushed commit. The marketplace session stopped at the usage limit in the middle of a CORS change that depends on this.",
    refs: "ADLMWebsite-corslog fix/log-cors-rejections",
    design: { status: "not-needed" },
  },
  {
    key: "device-seat",
    title: "One PC is one seat, even when the Installer Hub and QUIV hash it differently",
    products: ["installer-hub", "quiv", "website"],
    kind: "fix",
    stage: "shipped",
    progress: "On main (51be171).",
    pending: "",
    refs: "fix/device-scheme-aware-binding",
    design: { status: "not-needed" },
  },
  {
    key: "old-open-prs",
    title: "Old open pull requests to merge or close",
    products: ["website"],
    kind: "infra",
    stage: "on-hold",
    progress: "",
    pending: "#14 QUIV 3.1.11 changelog, #8 WhatsApp AI brief (naira quotable), #6 remove the legacy bundle discounts, #3 correct the NGN to USD rate (pricing), #1 the feature reference. They date from June to August. Each one needs a yes or a close.",
    refs: "github.com/adedola12/AdlmWeb/pulls",
    design: { status: "not-needed" },
  },

  // ── Other products ───────────────────────────────────────────────────────
  {
    key: "qs-takeoff-app",
    title: "QS Takeoff: the standalone take-off app",
    products: ["qs-app"],
    kind: "feature",
    stage: "on-hold",
    decision: "grandfathered",
    summary: "A standalone take-off app that works on drawings without PlanSwift, with templates, formulas, markups, reports and bill and budget builders. It is a separate product from Time Pro.",
    progress: "The last commit was on 30 Jun: saved take-off markups persist and redraw, and PlanSwift tokens are mapped. There is work from 2 Jul on reports, the bill builder, the budget builder and estimating.",
    pending: "20 commits have never been pushed, and 27 files are uncommitted. Push them so the work cannot be lost. Before building resumes, write its business case here: price, who buys it instead of HERON, and what it costs to support.",
    blockedOn: "Adedolapo: decide whether and when it resumes",
    refs: "source/repos/QSApp (master, no remote push since June)",
    design: { status: "needed", surfaces: "The whole app: workspace, measurement setup, templates, reports" },
  },
  {
    key: "adlm-market",
    title: "ADLM Market: marketplace rebuild with a RateGen price index and forecast",
    products: ["marketplace", "rategen", "ai-service"],
    kind: "feature",
    stage: "building",
    decision: "grandfathered",
    summary: "A staff-only internal build for now. Phase 1.5 covers the RateGen price index, price trends, supplier calls and a price forecast.",
    progress: "Staff-only build on its own branch. A live price forecast exists behind a data gate.",
    pending: "Neither branch has a remote. The session stopped at the usage limit in the middle of a CORS change on 21 Sep. It needs a business case before it goes beyond staff: who pays and for what.",
    refs: "mernsite-1 rebuild/ai-marketplace · adlm-ai-service-forecast feat/price-forecast",
    design: { status: "needed" },
  },
  {
    key: "mep-correctness",
    title: "Revit MEP Suite: correctness pass (phase A)",
    products: ["mep"],
    kind: "fix",
    stage: "building",
    progress: "The last commit was on 6 Aug.",
    pending: "34 files are uncommitted. They mix this pass with the network indicator and keyboard shortcuts. Sort them, commit them and test.",
    refs: "ADLMRvtMEPPlugin phase-a-correctness",
    design: { status: "not-needed" },
  },
  {
    key: "ai-service-main",
    title: "AI service: the live branches are not on main",
    products: ["ai-service", "infra"],
    kind: "infra",
    stage: "testing",
    progress: "Live on AWS: main plus the caller library, breakdown fill and boq-fill. It runs on the direct Anthropic API because Bedrock is still blocked for the account.",
    pending: "Merge the three branches to main. A deploy from main today would silently remove client bill fill.",
    refs: "adlm-ai-service, adlm-ai-service-boqfill",
    design: { status: "not-needed" },
  },
  {
    key: "archicad",
    title: "QUIV for ArchiCAD",
    products: ["archicad"],
    kind: "feature",
    stage: "on-hold",
    decision: "grandfathered",
    progress: "The connector, the backend, the costing engine and 4 pages are built. It was checked against ArchiCAD 28 with a test building.",
    pending: "The connector folder is not under git. Then test end to end with live rates and a real client project.",
    refs: "source/repos/quiv-archicad (no git) + ADLMWebsite /api/archicad",
    design: { status: "needed" },
  },
  {
    key: "mobile-billing",
    title: "Mobile app: billing, renewal and profile",
    products: ["mobile"],
    kind: "feature",
    stage: "on-hold",
    decision: "grandfathered",
    progress: "The last commit was on 11 Aug: EAS build profiles and device-testing notes.",
    pending: "The branch has no remote, and 6 files are uncommitted.",
    refs: "adlm-mobile feat/billing-renewal-profile",
    design: { status: "needed" },
  },
  {
    key: "whatsapp-bot",
    title: "WhatsApp sales bot: sync qualified chats to the Notion CRM",
    products: ["whatsapp-bot"],
    kind: "feature",
    stage: "on-hold",
    decision: "grandfathered",
    progress: "Phase 2 is done: qualified chats sync to Notion (12 Aug).",
    pending: "No remote, and 14 files are uncommitted.",
    refs: "source/repos/ADLMWhatsAppBot",
    design: { status: "not-needed" },
  },
  {
    key: "work-board",
    title: "This board: approval before build, and a design track beside the code",
    products: ["platform"],
    kind: "infra",
    stage: "testing",
    summary: "From 22 Sep 2026, every new feature or button starts here as a proposal with its business case. Richard approves it before it is designed or built. He designs while it is coded.",
    progress: "Built on its own branch, with tests.",
    pending: "Review the PR on preview.adlmstudio.net, merge it, then seed this list into production.",
    refs: "feat/work-board · docs/WORK_BOARD.md",
    design: { status: "needed", surfaces: "This board: summary tiles, the proposal form, the decision buttons, the design track" },
  },
];
